<?php

namespace Bilan_Social\Bundle\ConsoBundle\Repository;

/**
 * BscGpeecNbAgentsTituEmpPermaParFoncEtAgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BscDgclJoursCarenceRepository extends \Doctrine\ORM\EntityRepository {

}
