<?php

namespace Bilan_Social\Bundle\ConsoBundle\Repository;
use Bilan_Social\Bundle\CoreBundle\Repository\AbstractRepository;

/**
 * BscGpeecNiveauDiplomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BscHanditorialModeEntreesRepository extends AbstractRepository {

    public function getResultsForExport($idsBsc) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('ref.lbMotiarri, SUM(bsch.modeEntreeH) AS modeEntreeH, SUM(bsch.modeEntreeF) AS modeEntreeF')
                ->from($this->_entityName, 'bsch')
                ->join('ReferencielBundle:RefMotifArrivee', 'ref', 'WITH', 'bsch.refMotifArrivee = ref.idMotiarri')
                ->where('bsch.bilanSocialConsolide IN (:idsBsc)')
                ->setParameter('idsBsc', $idsBsc)
                ->groupBy('bsch.refMotifArrivee');
        try {
            $result = $qb->getQuery()->getResult();
            $result = $this->utf8_encode($result);
        }
        catch (NoResultException $e) {
            // Pas de enquete active consolidé pour la collectivite
            $result = null;
        }

        return $result;
    }

}
