<?php

namespace Bilan_Social\Bundle\ConsoBundle\Repository;
use Bilan_Social\Bundle\CoreBundle\Repository\AbstractRepository;

/**
 * BscHanditorialQuestionsGeneralesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BscHanditorialQuestionsGeneralesRepository extends AbstractRepository {

    /*public function getResultsForExport($idsBsc) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('SUM(bsch.rA61) AS rA61, SUM(bsch.rA71) AS rA71, SUM(bsch.rA81) AS rA81, SUM(bsch.rA9) AS rA9, SUM(bsch.rA91) AS rA91, SUM(bsch.rA10) AS rA10, SUM(bsch.rA101) AS rA101')
                ->from($this->_entityName, 'bsch')
                ->where('bsch.bilanSocialConsolide IN (:idsBsc)')
                ->setParameter('idsBsc', $idsBsc);
        try {
            $result = $qb->getQuery()->getSingleResult();
            $result = $this->utf8_encode($result);
        }
        catch (NoResultException $e) {
            // Pas de enquete active consolidé pour la collectivite
            $result = null;
        }

        return $result;
    }*/

    public function getQA3($idsBsc) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('bsch.qA3')
                ->from($this->_entityName, 'bsch')
                ->where('bsch.bilanSocialConsolide = :idsBsc')
                ->setParameter('idsBsc', $idsBsc);
        try {
            $result = $qb->getQuery()->getOneOrNullResult();
        }
        catch (NoResultException $e) {
            // Pas de enquete active consolidé pour la collectivite
            $result = null;
        }

        return $result;
    }

    public function getQA17($idsBsc) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('bsch.qA17')
                ->from($this->_entityName, 'bsch')
                ->where('bsch.bilanSocialConsolide = :idsBsc')
                ->setParameter('idsBsc', $idsBsc);
        try {
            $result = $qb->getQuery()->getOneOrNullResult();
        }
        catch (NoResultException $e) {
            // Pas de enquete active consolidé pour la collectivite
            $result = null;
        }

        return $result;
    }

}
