<?php

namespace Bilan_Social\Bundle\ConsoBundle\Repository;
use Bilan_Social\Bundle\CoreBundle\Repository\AbstractRepository;

/**
 * BscHanditorialAncienneteAgentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BscHanditorialAncienneteAgentsRepository extends AbstractRepository {

    public function getResultsForExport($idsBsc) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('
        COALESCE(SUM(bsch.moinsUnAnH),0) AS moinsUnAnH, 
        COALESCE(SUM(bsch.moinsUnAnF),0) AS moinsUnAnF, 
        COALESCE(SUM(bsch.entreUnEtTroisH),0) AS entreUnEtTroisH, 
        COALESCE(SUM(bsch.entreUnEtTroisF),0) AS entreUnEtTroisF, 
        COALESCE(SUM(bsch.entreQuatreEtSixH),0) AS entreQuatreEtSixH, 
        COALESCE(SUM(bsch.entreQuatreEtSixF),0) AS entreQuatreEtSixF, 
        COALESCE(SUM(bsch.entreSeptEtDouzeH),0) AS entreSeptEtDouzeH, 
        COALESCE(SUM(bsch.entreSeptEtDouzeF),0) AS entreSeptEtDouzeF, 
        COALESCE(SUM(bsch.plusDouzeH),0) AS plusDouzeH, 
        COALESCE(SUM(bsch.plusDouzeF),0) AS plusDouzeF')
                ->from($this->_entityName, 'bsch')
                ->where('bsch.bilanSocialConsolide IN (:idsBsc)')
                ->setParameter('idsBsc', $idsBsc);
        try {
            $result = $qb->getQuery()->getSingleResult();
            $result = $this->utf8_encode($result);
        }
        catch (NoResultException $e) {
            // Pas de enquete active consolidé pour la collectivite
            $result = '';
        }

        return $result;
    }

}
