<?php

namespace Bilan_Social\Bundle\ConsoBundle\Repository;
use Bilan_Social\Bundle\CoreBundle\Repository\AbstractRepository;

/**
 * BscHanditorialMetiersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BscHanditorialMetiersRepository extends AbstractRepository {

    public function getResultsForExport($idsBsc) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('ref as refMetier, SUM(bsch.metierH) AS metierH, SUM(bsch.metierF) AS metierF')
                ->from($this->_entityName, 'bsch')
                ->join('ReferencielBundle:RefMetier', 'ref', 'WITH', 'bsch.refMetier = ref.idMetier')
                ->where('bsch.bilanSocialConsolide IN (:idsBsc)')
                ->setParameter('idsBsc', $idsBsc)
                ->groupBy('bsch.refMetier');
        $qb2 = $this->_em->createQueryBuilder();
        $qb2->select("ref as refMetier, 0 AS metierH, 0 AS metierF")
            ->from('ReferencielBundle:RefMetier', 'ref')
            ->where('ref.blVali = 0')
            ->orderBy('ref.nmOrdre');
        try {
            $result = $this->unionQbs($qb2,$qb,'refMetier');
            //$result = $qb->getQuery()->getResult();
            //$result = $this->utf8_encode($result);
        }
        catch (NoResultException $e) {
            // Pas de enquete active consolidé pour la collectivite
            $result = null;
        }

        return $result;
    }

}
