<?php

namespace Bilan_Social\Bundle\ConsoBundle\Repository;
use Bilan_Social\Bundle\CoreBundle\Repository\AbstractRepository;

/**
 * BscHanditorialAvisInaptitudesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BscHanditorialMesureInaptitudesAvantRepository extends AbstractRepository {

    public function getResultsForExport($idsBsc) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('ref.lbMesureboeth, SUM(bsch.mesureInaptitudeAvantH) AS mesureInaptitudeAvantH, SUM(bsch.mesureInaptitudeAvantF) AS mesureInaptitudeAvantF')
                ->from($this->_entityName, 'bsch')
                ->join('ReferencielBundle:RefMesureBoeth', 'ref', 'WITH', 'bsch.refMesureBoeth = ref.idMesureboeth')
                ->where('bsch.bilanSocialConsolide IN (:idsBsc)')
                ->setParameter('idsBsc', $idsBsc)
                ->groupBy('bsch.refMesureBoeth');
        try {
            $result = $qb->getQuery()->getResult();
            $result = $this->utf8_encode($result);
        }
        catch (NoResultException $e) {
            // Pas de enquete active consolidé pour la collectivite
            $result = null;
        }

        return $result;
    }

}
