<?php

namespace Bilan_Social\Bundle\ConsoBundle\Repository;
use Bilan_Social\Bundle\CoreBundle\Repository\AbstractRepository;

/**
 * BscRassctNbAccidentTravailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BscRassctNbAccidentTravailRepository extends AbstractRepository {

    public function getResultsForExport($idsBsc) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('ref.lbTypeActi, SUM(bsch.rNbAccidentsSurvenus) AS rNbAccidentsSurvenus, SUM(bsch.rNbJourArretAccidents) AS rNbJourArretAccidents')
                ->from($this->_entityName, 'bsch')
                ->join('ReferencielBundle:RefTypeActivite', 'ref', 'WITH', 'bsch.refTypeActivite = ref.idTypeActi')
                ->where('bsch.bilanSocialConsolide IN (:idsBsc)')
                ->setParameter('idsBsc', $idsBsc)
                ->groupBy('bsch.refTypeActivite');

        $qb2 = $this->_em->createQueryBuilder();
        $qb2->select("ref.lbTypeActi, 0 AS rNbAccidentsSurvenus, 0 AS rNbJourArretAccidents")
            #->addSelect('reff')
            ->from('ReferencielBundle:RefTypeActivite', 'ref')
            ->where('ref.blVali = 0')
            ->orderBy('ref.nmOrdre');
        try {
            $result = $this->unionQbs($qb2,$qb,array('lbTypeActi'));
            /*$result = $qb->getQuery()->getResult();
            $result = $this->utf8_encode($result);*/
        }
        catch (NoResultException $e) {
            // Pas de enquete active consolidé pour la collectivite
            $result = null;
        }

        return $result;
    }

}
