<?php

namespace Bilan_Social\Bundle\ConsoBundle\Repository;
use Bilan_Social\Bundle\CoreBundle\Repository\AbstractRepository;

/**
 * BscRassctNatureLesionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BscRassctNatureLesionRepository extends AbstractRepository {

    public function getResultsForExport($idsBsc) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('ref.lbNaturelesi AS lbNatureLesi, SUM(bsch.rNbAccidentAvecArret) AS rNbAccidentAvecArret, SUM(bsch.rNbAccidentSansArret) AS rNbAccidentSansArret, SUM(bsch.rNbJourArret) AS rNbJourArret')
                ->from($this->_entityName, 'bsch')
                ->join('ReferencielBundle:RefNatureLesion', 'ref', 'WITH', 'bsch.refNatureLesion = ref.idNaturelesi')
                ->where('bsch.bilanSocialConsolide IN (:idsBsc)')
                ->setParameter('idsBsc', $idsBsc)
                ->groupBy('bsch.refNatureLesion');

        $qb2 = $this->_em->createQueryBuilder();
        $qb2->select("ref.lbNaturelesi AS lbNatureLesi, 0 AS rNbAccidentAvecArret, 0 AS rNbAccidentSansArret, 0 AS rNbJourArret")
            #->addSelect('reff')
            ->from('ReferencielBundle:RefNatureLesion', 'ref')
            ->where('ref.blVali = 0')
            ->orderBy('ref.nmOrdre');
        try {
            $result = $this->unionQbs($qb2,$qb,array('lbNatureLesi'));
            /*$result = $qb->getQuery()->getResult();
            $result = $this->utf8_encode($result);*/
        }
        catch (NoResultException $e) {
            // Pas de enquete active consolidé pour la collectivite
            $result = null;
        }

        return $result;
    }

}
