<?php

namespace Bilan_Social\Bundle\ConsoBundle\Repository;
use Bilan_Social\Bundle\CoreBundle\Repository\AbstractRepository;

/**
 * BscRassctElementMaterielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BscRassctElementMaterielRepository extends AbstractRepository {

    public function getResultsForExport($idsBsc) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('ref.lbElementmat AS lbElementMat, SUM(bsch.rNbAccident) AS rNbAccident, SUM(bsch.rNbJourArret) AS rNbJourArret')
                ->from($this->_entityName, 'bsch')
                ->join('ReferencielBundle:RefElementMateriel', 'ref', 'WITH', 'bsch.refElementMateriel = ref.idElementmat')
                ->where('bsch.bilanSocialConsolide IN (:idsBsc)')
                ->setParameter('idsBsc', $idsBsc)
                ->groupBy('bsch.refElementMateriel');

        $qb2 = $this->_em->createQueryBuilder();
        $qb2->select("ref.lbElementmat AS lbElementMat, 0 AS rNbAccident, 0 AS rNbJourArret")
            #->addSelect('reff')
            ->from('ReferencielBundle:RefElementMateriel', 'ref')
            ->where('ref.blVali = 0')
            ->orderBy('ref.nmOrdre');
        try {
            $result = $this->unionQbs($qb2,$qb,array('lbElementMat'));
            /*$result = $qb->getQuery()->getResult();
            $result = $this->utf8_encode($result);*/
        }
        catch (NoResultException $e) {
            // Pas de enquete active consolidé pour la collectivite
            $result = null;
        }

        return $result;
    }

}
