<?php

namespace Bilan_Social\Bundle\ConsoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SocialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ind2263Repository extends EntityRepository
{



}
