<?php

namespace Bilan_Social\Bundle\ReferencielBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Bilan_Social\Bundle\UserBundle\Repository\UserRepository;
use Doctrine\ORM\NoResultException;
use Bilan_Social\Bundle\CoreBundle\Repository\AbstractRepository;
/**
 * RefCycleTravailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefCycleTravailRepository extends RefAbstractRepository {




    public function findAllWithOrder() {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('ct')
                ->from($this->_entityName, 'ct')
                ->where('ct.blVali = 0')
                ->addOrderBy('ct.lbGroupeCycltrav', 'DESC')
                ;

        try {
            $ce = $qb->getQuery()->getResult();
        }
        catch (NoResultException $e) {
            return null;
        }

        return $ce;

    }


}
