<?php

namespace Bilan_Social\Bundle\ReferencielBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Bilan_Social\Bundle\CoreBundle\Repository\AbstractRepository;
/**
 * RefCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefCategorieRepository extends RefAbstractRepository
{

    public function findByAllWithOrder() {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('c')
                ->from($this->_entityName, 'c')
                ->where('c.blCons = 1')
                ->andWhere('c.blVali = 0')
                ->addOrderBy('c.idCate', 'ASC')
        ;

        try {
            $ce = $qb->getQuery()->getResult();
        } catch (NoResultException $e) {
            // Pas de bilan pour cette enquete et coll
            return null;
        }

        return $ce;
    }

    public function findAllCategorieByBlCons($blCons) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('c')
                ->from($this->_entityName, 'c')
                ->where('c.blCons = :blCons')
                ->andWhere('c.blVali = 0')
                ->setParameter('blCons', $blCons);

        try {
            $cat = $qb->getQuery()->getResult();
        } catch (NoResultException $e) {
            // Pas de bilan pour cette enquete et coll
            return null;
        }
        return $cat;
    }
}
