<?php

namespace Bilan_Social\Bundle\ReferencielBundle\Repository;

/**
 * RefCourtierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefCourtierRepository extends \Doctrine\ORM\EntityRepository
{
}
