<?php

namespace Bilan_Social\Bundle\ReferencielBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Bilan_Social\Bundle\CoreBundle\Repository\AbstractRepository;
/**
 * RefDomaineProfessionnelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefDomaineProfessionnelRepository extends RefAbstractRepository {

    public function getAllWithOrder($domainepro = null) {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('rdp')
                ->from($this->_entityName, 'rdp')
                ->where('rdp.blVali = 0')
        ;


        if ($domainepro != null) {
            $qb->innerJoin('rfm.RefFamilleMetier', 'rdp', 'rdp.idDomaineProfessionnel = rfm.idDomaineProfessionnel');
            $qb->andWhere('rfm.RefFamilleMetier = :domainepro')
                    ->setParameter('domainepro', $domainepro);
        }
        try {

            $ce = $qb->getQuery()->getResult();
        }
        catch (NoResultException $e) {
            // Pas de bilan pour cette enquete et coll
            return null;
        }

        return $ce;
    }

}
