<?php

namespace Bilan_Social\Bundle\ReferencielBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Bilan_Social\Bundle\CoreBundle\Repository\AbstractRepository;
/**
 * RefEmploiFonctionnelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefEmploiFonctionnelRepository extends RefAbstractRepository
{

    public function findOneByInCdN4ds($cdN4ds) {
        $code = '%-'.$cdN4ds.'-%';
        $qb = $this->_em->createQueryBuilder();
        $qb->select('ef')
                ->from($this->_entityName, 'ef')
                ->where('ef.blVali = 0')
                ->andWhere('concat(concat(\'-\', ef.cdMotiN4ds), \'-\' ) LIKE :code')
                ->setParameter('code', $code)
                ;

        try {
            $ef = $qb->getQuery()->getSingleResult();
        }
        catch (NoResultException $e) {
            return null;
        }

        return $ef;

    }


}
