<?php

namespace Bilan_Social\Bundle\ReferencielBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Bilan_Social\Bundle\CoreBundle\Repository\AbstractRepository;
/**
 * RefFamilleMetierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefFamilleMetierRepository extends RefAbstractRepository {

    public function getAllWithOrder($domainepro = null) {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('rfm')
                ->from($this->_entityName, 'rfm')
        ;


        if ($domainepro != null) {
            $qb->join('rfm.refDomaineProfessionnel', 'rdp')
                    ->where('rfm.blVali = 0');
            $qb->andWhere('rdp.idDomaineProfessionnel = :domainepro')
                    ->setParameter('domainepro', $domainepro);
        }


        try {

            $ce = $qb->getQuery()->getResult();
        }
        catch (NoResultException $e) {
            // Pas de bilan pour cette enquete et coll
            return null;
        }

        return $ce;
    }

    public function findByAllWithOrder() {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('f')
                ->from($this->_entityName, 'f')
                ->andWhere('f.blVali = 0')
                ->addOrderBy('f.idFamilleMetier', 'ASC')
        ;

        try {
            $ce = $qb->getQuery()->getResult();
        }
        catch (NoResultException $e) {
            // Pas de bilan pour cette enquete et coll
            return null;
        }

        return $ce;
    }

}
