<?php

namespace Bilan_Social\Bundle\ReferencielBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Bilan_Social\Bundle\CoreBundle\Repository\AbstractRepository;
/**
 * RefCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefFiliereRepository extends RefAbstractRepository
{

    public function findAllFiliereByBlCons($blCons) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('f')
                ->from($this->_entityName, 'f')
                ->where('f.blCons = :blCons')
                ->andWhere('f.blVali = 0')
                ->setParameter('blCons', $blCons);

        try {
            $filieres = $qb->getQuery()->getResult();
        } catch (NoResultException $e) {
            // Pas de bilan pour cette enquete et coll
            return null;
        }
        return $filieres;
    }

    public function findByAllWithOrder() {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('f')
                ->from($this->_entityName, 'f')
                ->where('f.blCons = 1')
                ->andWhere('f.blVali = 0')
                ->addOrderBy('f.idFili', 'ASC')
        ;

        try {
            $ce = $qb->getQuery()->getResult();
        } catch (NoResultException $e) {
            // Pas de bilan pour cette enquete et coll
            return null;
        }

        return $ce;
    }


    public function findByAllExceptAotmWithOrder() {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('f')
                ->from($this->_entityName, 'f')
                ->where('f.blCons = 1')
                ->andWhere('f.blVali = 0')
                ->andWhere("f.cdFili != 'AOTM'")
                ->andWhere("f.cdFili != ' H'")
                ->andWhere("f.cdFili != 'HH'")
                ->addOrderBy('f.idFili', 'ASC')
        ;

        try {
            $ce = $qb->getQuery()->getResult();
        } catch (NoResultException $e) {
            // Pas de bilan pour cette enquete et coll
            return null;
        }

        return $ce;
    }

    public function findByAllExceptAotmHorsFiliWithOrder() {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('f')
                ->from($this->_entityName, 'f')
                ->where('f.blCons = 1')
                ->andWhere('f.blVali = 0')
                ->andWhere("f.cdFili != 'AOTM'")
                ->andWhere("f.cdFili != ' H'")
                ->andWhere("f.cdFili != 'H'")
                ->andWhere("f.cdFili != 'HH'")
                ->addOrderBy('f.idFili', 'ASC')
        ;

        try {
            $ce = $qb->getQuery()->getResult();
        } catch (NoResultException $e) {
            // Pas de bilan pour cette enquete et coll
            return null;
        }

        return $ce;
    }
}
