<?php

namespace Bilan_Social\Bundle\ReferencielBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Bilan_Social\Bundle\CoreBundle\Repository\AbstractRepository;
/**
 * RefMouvinteanneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefMouvinteanneRepository extends RefAbstractRepository
{
    public function findAllMouvementInterneAnneeByStatut($status) {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('mia')
                ->from($this->_entityName, 'mia')
                ->innerJoin('mia.statutMouvInteAnne', 's', 'mia.statutMouvInteAnne = s.idStat')
                ->where('mia.blVali = 0')
                ->andWhere('s.idStat = :idstatut')
                ->setParameter('idstatut', $status)

        ;

        try {
            $ce = $qb->getQuery()->getResult();
        } catch (NoResultException $e) {
            return null;
        }

        return $ce;
    }
}
