<?php

namespace Bilan_Social\Bundle\ReferencielBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Bilan_Social\Bundle\CoreBundle\Repository\AbstractRepository;
/**
 * RefStageTitularisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefStageTitularisationRepository extends RefAbstractRepository {

    public function findByLoiSauvadet($idStageTitu) {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('st')
                ->from($this->_entityName, 'st')
        ->where('st.blVali = 0');

        if (!empty($idStageTitu)) {
            $qb->andWhere('st.idStagtitu = :idStagtitu')
                    ->andWhere('st.cdStagtitu = :cdStagtitu')
                ->setParameter('idStagtitu', $idStageTitu)
                ->setParameter('cdStagtitu', 'SAUVADET');
        }

        $blSauvadet = false;
        try {
            $st = $qb->getQuery()->getResult();
            if (!empty($st)) {
                $blSauvadet = true;
            }
        } catch (NoResultException $e) {
            // Pas de bilan pour cette enquete et coll
            return null;
        }
        return $blSauvadet;
    }

}

