<?php

namespace Bilan_Social\Bundle\ReferencielBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Bilan_Social\Bundle\CoreBundle\Repository\AbstractRepository;
/**
 * RefSanctionDisciplinaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefSanctionDisciplinaireRepository extends RefAbstractRepository {

    public function findByTitulaire() {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('rs')
            ->from($this->_entityName, 'rs')
            ->where('rs.blVali = 0')
            ->andWhere('(rs.bl614G1 = true) OR (rs.bl614G2 = true) or (rs.bl614G3 = true) or (rs.bl614G4 = true)');
        try {
            $ce = $qb->getQuery()->getResult();
        } catch (NoResultException $e) {
            return null;
        }

        return $ce;
    }

    public function findByStagiaire() {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('rs')
            ->from($this->_entityName, 'rs')
            ->where('rs.blVali = 0')
            ->andWhere('rs.bl614G5 = true');
        try {
            $ce = $qb->getQuery()->getResult();
        } catch (NoResultException $e) {
            return null;
        }

        return $ce;
    }

    public function findByContractuel() {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('rs')
            ->from($this->_entityName, 'rs')
            ->where('rs.blVali = 0')
            ->andWhere('rs.bl614G6 = true');
        try {
            $ce = $qb->getQuery()->getResult();
        } catch (NoResultException $e) {
            return null;
        }

        return $ce;
    }
}
