<?php

namespace Bilan_Social\Bundle\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Bilan_Social\Bundle\UserBundle\Entity\User;

/**
 * IncoherenceLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncoherenceLogRepository extends EntityRepository {

    public function removeOlderIncoherence(User $user, $formClass) {
        $qb = $this->_em->createQueryBuilder();
        $qb->delete($this->_entityName, 'i')
                ->where('i.user = :user')
                ->andWhere('i.form = :form')
                ->setParameter('user', $user)
                ->setParameter('form', $formClass);

        return $qb->getQuery()->execute();
    }

    public function removeOlderIncoherenceBilan($idBilan) {

        $qb = $this->_em->createQueryBuilder()
              ->select('i')
              ->from($this->_entityName, 'i');

        $qb->join('i.bilanSocialConsolide', 'b')
           ->addSelect('b')
           ->where('b.idBilasocicons = :bilan')
                ->setParameter('bilan',$idBilan);

        $results =  $qb->getQuery()->getResult();


        foreach ($results as $result) {
             $this->_em->remove($result);
        }

    }

}
