<?php

namespace Bilan_Social\Bundle\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SocialStep2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialStep2Repository extends EntityRepository {

}
