DELIMITER $$

DROP PROCEDURE IF EXISTS apa2cons_ind213
$$

CREATE PROCEDURE apa2cons_ind213(idBilaSociCons INT, idColl INT, idEnqu INT)
COMMENT ''
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
BEGIN


  ### Création et remplissage de la table temporaire
  DROP TEMPORARY TABLE IF EXISTS temp_apa2cons_ind213;
  CREATE TEMPORARY TABLE temp_apa2cons_ind213 (INDEX(Q1))
    ENGINE = MEMORY
    AS (
      SELECT        
        bsa.CD_SEXE AS Q1,
		CASE WHEN   TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) < 25 
				THEN 1
			 WHEN   TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) >= 25 
				AND TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) <= 29
				THEN 2
			 WHEN   TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) >= 30
				AND TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) <= 34
				THEN 3
			 WHEN   TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) >= 35 
				AND TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) <= 39
				THEN 4
			 WHEN   TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) >= 40 
				AND TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) <= 44
				THEN 5
			 WHEN   TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) >= 45 
				AND TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) <= 49
				THEN 6
			 WHEN   TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) >= 50 
				AND TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) <= 54
				THEN 7
			 WHEN   TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) >= 55 
				AND TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) <= 59
				THEN 8
			 WHEN   TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) >= 60 
				AND TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) <= 64
				THEN 9
			 ELSE 10 END AS ID_TRANAGE,
		aaa.ID_MOTIABSE,
		count(DISTINCT aaa.ID_BILASOCIAGEN) AS NB_FONC,
		sum(aaa.NB_ARRE) AS NB_ARRE,
		sum(aaa.NB_JOURABSE) AS NB_JOURABSE
      FROM bilan_social_agent AS bsa
        JOIN ref_statut AS rs ON bsa.ID_STAT = rs.ID_STAT  # Q2        
		JOIN absence_arret_agent AS aaa  ON bsa.ID_BILASOCIAGEN = aaa.ID_BILASOCIAGEN
      WHERE bsa.ID_COLL = idColl
		AND aaa.NB_JOURABSE > 0
        AND bsa.ID_ENQU = idEnqu
		AND rs.CD_STAT = 'CONTNONPERM'   # Q2
        AND bsa.BL_AGENABSE = 1       # Q20.1        
		AND bsa.LB_DATENAIS IS NOT NULL
	  GROUP BY Q1, bsa.lb_datenais, aaa.ID_MOTIABSE
		
    );
	

  ### Remplissage 
  INSERT INTO ind_213_1 (ID_BILASOCICONS, ID_MOTIABSE, R_21311, R_21312, R_21313, R_21314, R_21315, R_21316)
  SELECT idBilaSociCons, ma.ID_MOTIABSE, 
    SUM(CASE WHEN t.Q1 = 1 THEN t.NB_FONC ELSE 0 END) AS R_21311,
    SUM(CASE WHEN t.Q1 = 2 THEN t.NB_FONC ELSE 0 END) AS R_21312,
	SUM(CASE WHEN t.Q1 = 1 THEN t.NB_JOURABSE ELSE 0 END) AS R_21313,
	SUM(CASE WHEN t.Q1 = 2 THEN t.NB_JOURABSE ELSE 0 END) AS R_21314,
	SUM(CASE WHEN t.Q1 = 1 THEN t.NB_ARRE ELSE 0 END) AS R_21315,
	SUM(CASE WHEN t.Q1 = 2 THEN t.NB_ARRE ELSE 0 END) AS R_21316
  FROM ref_motif_absence ma 
  LEFT JOIN temp_apa2cons_ind213 t on t.ID_MOTIABSE = ma.ID_MOTIABSE
  GROUP BY idBilaSociCons, ma.ID_MOTIABSE
  ORDER BY ma.BL_ABSECOMP DESC,  ma.BL_ABSEMEDI DESC, ma.BL_ABSEAUTRRAIS DESC, ma.ID_MOTIABSE;
  
  
  
  INSERT INTO ind_213_2 (ID_BILASOCICONS, ID_MOTIABSE, R_21321, R_21322, R_21323, R_21324, R_21325, R_21326, R_21327, R_21328, R_21329, R_213210)
  SELECT idBilaSociCons, ma.ID_MOTIABSE, 
    SUM(CASE WHEN t.ID_TRANAGE = 1 THEN t.NB_FONC ELSE 0 END) AS R_21321,
	SUM(CASE WHEN t.ID_TRANAGE = 2 THEN t.NB_FONC ELSE 0 END) AS R_21322,
	SUM(CASE WHEN t.ID_TRANAGE = 3 THEN t.NB_FONC ELSE 0 END) AS R_21323,
	SUM(CASE WHEN t.ID_TRANAGE = 4 THEN t.NB_FONC ELSE 0 END) AS R_21324,
	SUM(CASE WHEN t.ID_TRANAGE = 5 THEN t.NB_FONC ELSE 0 END) AS R_21325,
	SUM(CASE WHEN t.ID_TRANAGE = 6 THEN t.NB_FONC ELSE 0 END) AS R_21326,
	SUM(CASE WHEN t.ID_TRANAGE = 7 THEN t.NB_FONC ELSE 0 END) AS R_21327,
	SUM(CASE WHEN t.ID_TRANAGE = 8 THEN t.NB_FONC ELSE 0 END) AS R_21328,
	SUM(CASE WHEN t.ID_TRANAGE = 9 THEN t.NB_FONC ELSE 0 END) AS R_21329,
	SUM(CASE WHEN t.ID_TRANAGE = 10 THEN t.NB_FONC ELSE 0 END) AS R_213210    
  FROM ref_motif_absence ma 
  LEFT JOIN temp_apa2cons_ind213 t on t.ID_MOTIABSE = ma.ID_MOTIABSE
  WHERE (ma.BL_ABSECOMP = 1 OR ma.BL_ABSEMEDI = 1)
  GROUP BY idBilaSociCons, ma.ID_MOTIABSE
  ORDER BY ma.BL_ABSECOMP DESC,  ma.BL_ABSEMEDI DESC, ma.ID_MOTIABSE;
  
  
  INSERT INTO ind_213_3 (ID_BILASOCICONS, ID_MOTIABSE, R_21331, R_21332, R_21333, R_21334, R_21335, R_21336, R_21337, R_21338, R_21339, R_213310)
  SELECT idBilaSociCons, ma.ID_MOTIABSE, 
    SUM(CASE WHEN t.ID_TRANAGE = 1 THEN t.NB_JOURABSE ELSE 0 END) AS R_21331,
	SUM(CASE WHEN t.ID_TRANAGE = 2 THEN t.NB_JOURABSE ELSE 0 END) AS R_21332,
	SUM(CASE WHEN t.ID_TRANAGE = 3 THEN t.NB_JOURABSE ELSE 0 END) AS R_21333,
	SUM(CASE WHEN t.ID_TRANAGE = 4 THEN t.NB_JOURABSE ELSE 0 END) AS R_21334,
	SUM(CASE WHEN t.ID_TRANAGE = 5 THEN t.NB_JOURABSE ELSE 0 END) AS R_21335,
	SUM(CASE WHEN t.ID_TRANAGE = 6 THEN t.NB_JOURABSE ELSE 0 END) AS R_21336,
	SUM(CASE WHEN t.ID_TRANAGE = 7 THEN t.NB_JOURABSE ELSE 0 END) AS R_21337,
	SUM(CASE WHEN t.ID_TRANAGE = 8 THEN t.NB_JOURABSE ELSE 0 END) AS R_21338,
	SUM(CASE WHEN t.ID_TRANAGE = 9 THEN t.NB_JOURABSE ELSE 0 END) AS R_21339,
	SUM(CASE WHEN t.ID_TRANAGE = 10 THEN t.NB_JOURABSE ELSE 0 END) AS R_213310    
  FROM ref_motif_absence ma 
  LEFT JOIN temp_apa2cons_ind213 t on t.ID_MOTIABSE = ma.ID_MOTIABSE
  WHERE (ma.BL_ABSECOMP = 1 OR ma.BL_ABSEMEDI = 1)
  GROUP BY idBilaSociCons, ma.ID_MOTIABSE
  ORDER BY ma.BL_ABSECOMP DESC,  ma.BL_ABSEMEDI DESC, ma.ID_MOTIABSE;
  
  
  
END
$$

