DELIMITER $$

DROP PROCEDURE IF EXISTS apa2cons_ind211
$$

CREATE PROCEDURE apa2cons_ind211(idBilaSociCons INT, idColl INT, idEnqu INT)
COMMENT ''
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
BEGIN


  ### Création et remplissage de la table temporaire
  DROP TEMPORARY TABLE IF EXISTS temp_apa2cons_ind211;
  CREATE TEMPORARY TABLE temp_apa2cons_ind211 (INDEX(Q1))
    ENGINE = MEMORY
    AS (
      SELECT        
        bsa.CD_SEXE AS Q1,
		CASE WHEN   TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) < 25 
				THEN 1
			 WHEN   TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) >= 25 
				AND TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) <= 29
				THEN 2
			 WHEN   TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) >= 30
				AND TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) <= 34
				THEN 3
			 WHEN   TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) >= 35 
				AND TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) <= 39
				THEN 4
			 WHEN   TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) >= 40 
				AND TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) <= 44
				THEN 5
			 WHEN   TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) >= 45 
				AND TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) <= 49
				THEN 6
			 WHEN   TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) >= 50 
				AND TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) <= 54
				THEN 7
			 WHEN   TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) >= 55 
				AND TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) <= 59
				THEN 8
			 WHEN   TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) >= 60 
				AND TIMESTAMPDIFF(YEAR, CONVERT(CONCAT(SUBSTRING( bsa.lb_datenais  , 4, 4), CONCAT('-', CONCAT(SUBSTRING('05/1955', 1, 2), '-15'))), DATE ), CURDATE()) <= 64
				THEN 9
			 ELSE 10 END AS ID_TRANAGE,
		aaa.ID_MOTIABSE,
		count(DISTINCT aaa.ID_BILASOCIAGEN) AS NB_FONC,
		sum( CASE 
					WHEN aaa.ACCIDENT_AVEC_ARRET = 0 THEN 0
					WHEN aaa.ACCIDENT_AVEC_ARRET = 1 THEN 1
					ELSE COALESCE(aaa.NB_ARRE,1) END ) AS NB_ARRE,
		sum(aaa.NB_JOURABSE) AS NB_JOURABSE
      FROM bilan_social_agent AS bsa
        JOIN ref_statut AS rs ON bsa.ID_STAT = rs.ID_STAT  # Q2        
		JOIN absence_arret_agent AS aaa  ON bsa.ID_BILASOCIAGEN = aaa.ID_BILASOCIAGEN
		
      WHERE bsa.ID_COLL = idColl
		AND aaa.NB_JOURABSE > 0
        AND bsa.ID_ENQU = idEnqu
		AND rs.CD_STAT in ('TITU','STAG')   # Q2
        AND bsa.BL_AGENABSE = 1         	# Q20.1        
		AND bsa.LB_DATENAIS IS NOT NULL
	  GROUP BY Q1, bsa.lb_datenais, aaa.ID_MOTIABSE
		
    );
	

  ### Remplissage 
  INSERT INTO ind_211_1 (ID_BILASOCICONS, ID_MOTIABSE, R_21111, R_21112, R_21113, R_21114, R_21115, R_21116)
  SELECT idBilaSociCons, ma.ID_MOTIABSE, 
    SUM(CASE WHEN t.Q1 = 1 THEN t.NB_FONC ELSE 0 END) AS R_21111,
    SUM(CASE WHEN t.Q1 = 2 THEN t.NB_FONC ELSE 0 END) AS R_21112,
	SUM(CASE WHEN t.Q1 = 1 THEN t.NB_JOURABSE ELSE 0 END) AS R_21113,
	SUM(CASE WHEN t.Q1 = 2 THEN t.NB_JOURABSE ELSE 0 END) AS R_21114,
	SUM(CASE WHEN t.Q1 = 1 THEN t.NB_ARRE ELSE 0 END) AS R_21115,
	SUM(CASE WHEN t.Q1 = 2 THEN t.NB_ARRE ELSE 0 END) AS R_21116
  FROM ref_motif_absence ma 
  LEFT JOIN temp_apa2cons_ind211 t on t.ID_MOTIABSE = ma.ID_MOTIABSE
  GROUP BY idBilaSociCons, ma.ID_MOTIABSE
  ORDER BY ma.BL_ABSECOMP DESC,  ma.BL_ABSEMEDI DESC, ma.BL_ABSEAUTRRAIS DESC, ma.ID_MOTIABSE;
  
  
  
  INSERT INTO ind_211_2 (ID_BILASOCICONS, ID_MOTIABSE, R_21121, R_21122, R_21123, R_21124, R_21125, R_21126, R_21127, R_21128, R_21129, R_211210)
  SELECT idBilaSociCons, ma.ID_MOTIABSE, 
    SUM(CASE WHEN t.ID_TRANAGE = 1 THEN t.NB_FONC ELSE 0 END) AS R_21121,
	SUM(CASE WHEN t.ID_TRANAGE = 2 THEN t.NB_FONC ELSE 0 END) AS R_21122,
	SUM(CASE WHEN t.ID_TRANAGE = 3 THEN t.NB_FONC ELSE 0 END) AS R_21123,
	SUM(CASE WHEN t.ID_TRANAGE = 4 THEN t.NB_FONC ELSE 0 END) AS R_21124,
	SUM(CASE WHEN t.ID_TRANAGE = 5 THEN t.NB_FONC ELSE 0 END) AS R_21125,
	SUM(CASE WHEN t.ID_TRANAGE = 6 THEN t.NB_FONC ELSE 0 END) AS R_21126,
	SUM(CASE WHEN t.ID_TRANAGE = 7 THEN t.NB_FONC ELSE 0 END) AS R_21127,
	SUM(CASE WHEN t.ID_TRANAGE = 8 THEN t.NB_FONC ELSE 0 END) AS R_21128,
	SUM(CASE WHEN t.ID_TRANAGE = 9 THEN t.NB_FONC ELSE 0 END) AS R_21129,
	SUM(CASE WHEN t.ID_TRANAGE = 10 THEN t.NB_FONC ELSE 0 END) AS R_211210    
  FROM ref_motif_absence ma 
  LEFT JOIN temp_apa2cons_ind211 t on t.ID_MOTIABSE = ma.ID_MOTIABSE
  WHERE (ma.BL_ABSECOMP = 1 OR ma.BL_ABSEMEDI = 1)
  GROUP BY idBilaSociCons, ma.ID_MOTIABSE
  ORDER BY ma.BL_ABSECOMP DESC,  ma.BL_ABSEMEDI DESC, ma.ID_MOTIABSE;
  
  
  INSERT INTO ind_211_3 (ID_BILASOCICONS, ID_MOTIABSE, R_21131, R_21132, R_21133, R_21134, R_21135, R_21136, R_21137, R_21138, R_21139, R_211310)
  SELECT idBilaSociCons, ma.ID_MOTIABSE, 
    SUM(CASE WHEN t.ID_TRANAGE = 1 THEN t.NB_JOURABSE ELSE 0 END) AS R_21131,
	SUM(CASE WHEN t.ID_TRANAGE = 2 THEN t.NB_JOURABSE ELSE 0 END) AS R_21132,
	SUM(CASE WHEN t.ID_TRANAGE = 3 THEN t.NB_JOURABSE ELSE 0 END) AS R_21133,
	SUM(CASE WHEN t.ID_TRANAGE = 4 THEN t.NB_JOURABSE ELSE 0 END) AS R_21134,
	SUM(CASE WHEN t.ID_TRANAGE = 5 THEN t.NB_JOURABSE ELSE 0 END) AS R_21135,
	SUM(CASE WHEN t.ID_TRANAGE = 6 THEN t.NB_JOURABSE ELSE 0 END) AS R_21136,
	SUM(CASE WHEN t.ID_TRANAGE = 7 THEN t.NB_JOURABSE ELSE 0 END) AS R_21137,
	SUM(CASE WHEN t.ID_TRANAGE = 8 THEN t.NB_JOURABSE ELSE 0 END) AS R_21138,
	SUM(CASE WHEN t.ID_TRANAGE = 9 THEN t.NB_JOURABSE ELSE 0 END) AS R_21139,
	SUM(CASE WHEN t.ID_TRANAGE = 10 THEN t.NB_JOURABSE ELSE 0 END) AS R_211310    
  FROM ref_motif_absence ma 
  LEFT JOIN temp_apa2cons_ind211 t on t.ID_MOTIABSE = ma.ID_MOTIABSE
  WHERE (ma.BL_ABSECOMP = 1 OR ma.BL_ABSEMEDI = 1)
  GROUP BY idBilaSociCons, ma.ID_MOTIABSE
  ORDER BY ma.BL_ABSECOMP DESC,  ma.BL_ABSEMEDI DESC, ma.ID_MOTIABSE;
  
  
  
END
$$

