DELIMITER $$

DROP PROCEDURE IF EXISTS apa2cons_ind226
$$

CREATE PROCEDURE apa2cons_ind226(idBilaSociCons INT, idColl INT, idEnqu INT)
COMMENT ''
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
BEGIN
  ### Création et remplissage de la table temporaire
  DROP TEMPORARY TABLE IF EXISTS temp_apa2cons_dgcljourscarence;
  CREATE TEMPORARY TABLE temp_apa2cons_dgcljourscarence (INDEX(CD_SEXE,CD_STAT,ID_CATE))
    ENGINE = MEMORY
    AS (
      SELECT
        bsa.CD_SEXE AS CD_SEXE,
        rs.CD_STAT AS CD_STAT,         # Titulaire=TITU, Stagiaire=STAG, Contractuel sur emploi permanent=CONTPERM, Contractuel sur emploi non permanent=CONTNONPERM
        rc.CD_CATE AS CD_CATE,   # CatA, CatB, CatC, AOTM, ' H', HH
        rc.ID_CATE AS ID_CATE,
        bsad.BL_JOURS_CARENCE  AS BL_JOURS_CARENCE,
        bsad.NB_JOURS_CARENCE  AS NB_JOURS_CARENCE,
        bsad.NB_MONTANT_CARENCE  AS NB_MONTANT_CARENCE,
        aaa.NB_ARRE AS NB_ARRE,
        aaa.ID_MOTIABSE AS ID_MOTIABSE,
        bsa.BL_AGENREMU3112 AS BL_AGENREMU3112, # Q4.1
        bsa.BL_AGENREMUANNE AS BL_AGENREMUANNE  # Q4.2
      FROM bilan_social_agent AS bsa
        JOIN ref_statut AS rs ON bsa.ID_STAT = rs.ID_STAT  # Q2
        LEFT JOIN ref_categorie AS rc ON bsa.ID_CATE = rc.ID_CATE # Q2.8
        LEFT JOIN bilan_social_agent_dgcl bsad ON  bsad.ID_BILASOCIAGEN = bsa.ID_BILASOCIAGEN
        LEFT JOIN absence_arret_agent aaa ON  aaa.ID_BILASOCIAGEN = bsa.ID_BILASOCIAGEN
      WHERE bsa.ID_COLL = idColl
        AND bsa.ID_ENQU = idEnqu
    );

#'NJCP','MBSRDC','NTARSJC','NAAJC','NAMSJC'

  INSERT INTO ind_2261 (ID_BILASOCICONS, CD_JOUR_CARENCE, DT_CREA, CD_UTILCREA, DT_MODI, CD_UTILMODI, ORDRE,
        	R_22611, R_22612, R_22613, R_22614, R_22615, R_22616)
  SELECT idBilaSociCons, 'NJCP',  CURRENT_TIMESTAMP, 'APA', CURRENT_TIMESTAMP, 'APA', 0,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'A' THEN COALESCE(t.NB_JOURS_CARENCE, 0) ELSE 0 END) AS NB_JOURS_CARENCE_PRELEVES_H_A,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'B' THEN COALESCE(t.NB_JOURS_CARENCE, 0) ELSE 0 END) AS NB_JOURS_CARENCE_PRELEVES_H_B,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'C' THEN COALESCE(t.NB_JOURS_CARENCE, 0) ELSE 0 END) AS NB_JOURS_CARENCE_PRELEVES_H_C,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'A' THEN COALESCE(t.NB_JOURS_CARENCE, 0) ELSE 0 END) AS NB_JOURS_CARENCE_PRELEVES_F_A,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'B' THEN COALESCE(t.NB_JOURS_CARENCE, 0) ELSE 0 END) AS NB_JOURS_CARENCE_PRELEVES_F_B,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'C' THEN COALESCE(t.NB_JOURS_CARENCE, 0) ELSE 0 END) AS NB_JOURS_CARENCE_PRELEVES_F_C
  FROM ref_categorie rc
	LEFT JOIN temp_apa2cons_dgcljourscarence t ON rc.ID_CATE = t.ID_CATE
  WHERE  rc.bl_vali = 0
  GROUP BY idBilaSociCons;

  INSERT INTO ind_2261 (ID_BILASOCICONS, CD_JOUR_CARENCE, DT_CREA, CD_UTILCREA, DT_MODI, CD_UTILMODI, ORDRE,
        	R_22611, R_22612, R_22613, R_22614, R_22615, R_22616)
  SELECT idBilaSociCons, 'MBSRDC',  CURRENT_TIMESTAMP, 'APA', CURRENT_TIMESTAMP, 'APA', 1,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'A' THEN COALESCE(t.NB_MONTANT_CARENCE, 0) ELSE 0 END) AS NB_SOMME_DELAI_CARENCE_H_A,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'B' THEN COALESCE(t.NB_MONTANT_CARENCE, 0) ELSE 0 END) AS NB_SOMME_DELAI_CARENCE_H_B,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'C' THEN COALESCE(t.NB_MONTANT_CARENCE, 0) ELSE 0 END) AS NB_SOMME_DELAI_CARENCE_H_C,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'A' THEN COALESCE(t.NB_MONTANT_CARENCE, 0) ELSE 0 END) AS NB_SOMME_DELAI_CARENCE_F_A,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'B' THEN COALESCE(t.NB_MONTANT_CARENCE, 0) ELSE 0 END) AS NB_SOMME_DELAI_CARENCE_F_B,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'C' THEN COALESCE(t.NB_MONTANT_CARENCE, 0) ELSE 0 END) AS NB_SOMME_DELAI_CARENCE_F_C
  FROM ref_categorie rc
	LEFT JOIN temp_apa2cons_dgcljourscarence t ON rc.ID_CATE = t.ID_CATE
  WHERE  rc.bl_vali = 0
  GROUP BY idBilaSociCons;

  INSERT INTO ind_2261 (ID_BILASOCICONS, CD_JOUR_CARENCE, DT_CREA, CD_UTILCREA, DT_MODI, CD_UTILMODI, ORDRE,
        	R_22611, R_22612, R_22613, R_22614, R_22615, R_22616)
  SELECT idBilaSociCons, 'NTARSJC',  CURRENT_TIMESTAMP, 'APA', CURRENT_TIMESTAMP, 'APA', 2,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'A' AND (t.BL_AGENREMUANNE = 1 OR t.BL_AGENREMU3112 =1) THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_REMUNERES_H_A,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'B' AND (t.BL_AGENREMUANNE = 1 OR t.BL_AGENREMU3112 =1) THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_REMUNERES_H_B,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'C' AND (t.BL_AGENREMUANNE = 1 OR t.BL_AGENREMU3112 =1) THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_REMUNERES_H_C,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'A' AND (t.BL_AGENREMUANNE = 1 OR t.BL_AGENREMU3112 =1) THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_REMUNERES_F_A,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'B' AND (t.BL_AGENREMUANNE = 1 OR t.BL_AGENREMU3112 =1) THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_REMUNERES_F_B,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'C' AND (t.BL_AGENREMUANNE = 1 OR t.BL_AGENREMU3112 =1) THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_REMUNERES_F_C
  FROM ref_categorie rc
	LEFT JOIN temp_apa2cons_dgcljourscarence t ON rc.ID_CATE = t.ID_CATE
  WHERE  rc.bl_vali = 0
  GROUP BY idBilaSociCons;

  INSERT INTO ind_2261 (ID_BILASOCICONS, CD_JOUR_CARENCE, DT_CREA, CD_UTILCREA, DT_MODI, CD_UTILMODI, ORDRE,
        	R_22611, R_22612, R_22613, R_22614, R_22615, R_22616)
  SELECT idBilaSociCons, 'NAAJC',  CURRENT_TIMESTAMP, 'APA', CURRENT_TIMESTAMP, 'APA', 3,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'A' AND t.BL_JOURS_CARENCE = 1 THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_JOURS_CARENCE_H_A,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'B' AND t.BL_JOURS_CARENCE = 1 THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_JOURS_CARENCE_H_B,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'C' AND t.BL_JOURS_CARENCE = 1 THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_JOURS_CARENCE_H_C,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'A' AND t.BL_JOURS_CARENCE = 1 THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_JOURS_CARENCE_F_A,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'B' AND t.BL_JOURS_CARENCE = 1 THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_JOURS_CARENCE_F_B,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'C' AND t.BL_JOURS_CARENCE = 1 THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_JOURS_CARENCE_F_C
  FROM ref_categorie rc
	LEFT JOIN temp_apa2cons_dgcljourscarence t ON rc.ID_CATE = t.ID_CATE
  WHERE  rc.bl_vali = 0
  GROUP BY idBilaSociCons;


  INSERT INTO ind_2261 (ID_BILASOCICONS, CD_JOUR_CARENCE, DT_CREA, CD_UTILCREA, DT_MODI, CD_UTILMODI, ORDRE,
        	R_22611, R_22612, R_22613, R_22614, R_22615, R_22616)
  SELECT idBilaSociCons, 'NAMSJC',  CURRENT_TIMESTAMP, 'APA', CURRENT_TIMESTAMP, 'APA', 4,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'A' AND t.ID_MOTIABSE IN (1,2,9) THEN COALESCE(t.NB_ARRE, 0) ELSE 0 END) AS NB_ARRET_MALADIES_H_A,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'B' AND t.ID_MOTIABSE IN (1,2,9) THEN COALESCE(t.NB_ARRE, 0) ELSE 0 END) AS NB_ARRET_MALADIES_H_B,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'C' AND t.ID_MOTIABSE IN (1,2,9) THEN COALESCE(t.NB_ARRE, 0) ELSE 0 END) AS NB_ARRET_MALADIES_H_C,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'A' AND t.ID_MOTIABSE IN (1,2,9) THEN COALESCE(t.NB_ARRE, 0) ELSE 0 END) AS NB_ARRET_MALADIES_F_A,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'B' AND t.ID_MOTIABSE IN (1,2,9) THEN COALESCE(t.NB_ARRE, 0) ELSE 0 END) AS NB_ARRET_MALADIES_F_B,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'C' AND t.ID_MOTIABSE IN (1,2,9) THEN COALESCE(t.NB_ARRE, 0) ELSE 0 END) AS NB_ARRET_MALADIES_F_C
  FROM ref_categorie rc
	LEFT JOIN temp_apa2cons_dgcljourscarence t ON rc.ID_CATE = t.ID_CATE
  WHERE  rc.bl_vali = 0
  GROUP BY idBilaSociCons;





  INSERT INTO ind_2262 (ID_BILASOCICONS, CD_JOUR_CARENCE, DT_CREA, CD_UTILCREA, DT_MODI, CD_UTILMODI, ORDRE,
        	R_22621, R_22622, R_22623, R_22624, R_22625, R_22626)
  SELECT idBilaSociCons, 'NJCP',  CURRENT_TIMESTAMP, 'APA', CURRENT_TIMESTAMP, 'APA', 0,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'A' THEN COALESCE(t.NB_JOURS_CARENCE, 0) ELSE 0 END) AS NB_JOURS_CARENCE_PRELEVES_H_A,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'B' THEN COALESCE(t.NB_JOURS_CARENCE, 0) ELSE 0 END) AS NB_JOURS_CARENCE_PRELEVES_H_B,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'C' THEN COALESCE(t.NB_JOURS_CARENCE, 0) ELSE 0 END) AS NB_JOURS_CARENCE_PRELEVES_H_C,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'A' THEN COALESCE(t.NB_JOURS_CARENCE, 0) ELSE 0 END) AS NB_JOURS_CARENCE_PRELEVES_F_A,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'B' THEN COALESCE(t.NB_JOURS_CARENCE, 0) ELSE 0 END) AS NB_JOURS_CARENCE_PRELEVES_F_B,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'C' THEN COALESCE(t.NB_JOURS_CARENCE, 0) ELSE 0 END) AS NB_JOURS_CARENCE_PRELEVES_F_C
  FROM ref_categorie rc
	LEFT JOIN temp_apa2cons_dgcljourscarence t ON rc.ID_CATE = t.ID_CATE
  WHERE  rc.bl_vali = 0
  GROUP BY idBilaSociCons;

  INSERT INTO ind_2262 (ID_BILASOCICONS, CD_JOUR_CARENCE, DT_CREA, CD_UTILCREA, DT_MODI, CD_UTILMODI, ORDRE,
        	R_22621, R_22622, R_22623, R_22624, R_22625, R_22626)
  SELECT idBilaSociCons, 'MBSRDC',  CURRENT_TIMESTAMP, 'APA', CURRENT_TIMESTAMP, 'APA', 1,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'A' THEN COALESCE(t.NB_MONTANT_CARENCE, 0) ELSE 0 END) AS NB_SOMME_DELAI_CARENCE_H_A,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'B' THEN COALESCE(t.NB_MONTANT_CARENCE, 0) ELSE 0 END) AS NB_SOMME_DELAI_CARENCE_H_B,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'C' THEN COALESCE(t.NB_MONTANT_CARENCE, 0) ELSE 0 END) AS NB_SOMME_DELAI_CARENCE_H_C,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'A' THEN COALESCE(t.NB_MONTANT_CARENCE, 0) ELSE 0 END) AS NB_SOMME_DELAI_CARENCE_F_A,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'B' THEN COALESCE(t.NB_MONTANT_CARENCE, 0) ELSE 0 END) AS NB_SOMME_DELAI_CARENCE_F_B,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'C' THEN COALESCE(t.NB_MONTANT_CARENCE, 0) ELSE 0 END) AS NB_SOMME_DELAI_CARENCE_F_C
  FROM ref_categorie rc
	LEFT JOIN temp_apa2cons_dgcljourscarence t ON rc.ID_CATE = t.ID_CATE
  WHERE  rc.bl_vali = 0
  GROUP BY idBilaSociCons;

  INSERT INTO ind_2262 (ID_BILASOCICONS, CD_JOUR_CARENCE, DT_CREA, CD_UTILCREA, DT_MODI, CD_UTILMODI, ORDRE,
        	R_22621, R_22622, R_22623, R_22624, R_22625, R_22626)
  SELECT idBilaSociCons, 'NTARSJC',  CURRENT_TIMESTAMP, 'APA', CURRENT_TIMESTAMP, 'APA', 2,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'A' AND (t.BL_AGENREMUANNE = 1 OR t.BL_AGENREMU3112 =1) THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_REMUNERES_H_A,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'B' AND (t.BL_AGENREMUANNE = 1 OR t.BL_AGENREMU3112 =1) THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_REMUNERES_H_B,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'C' AND (t.BL_AGENREMUANNE = 1 OR t.BL_AGENREMU3112 =1) THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_REMUNERES_H_C,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'A' AND (t.BL_AGENREMUANNE = 1 OR t.BL_AGENREMU3112 =1) THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_REMUNERES_F_A,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'B' AND (t.BL_AGENREMUANNE = 1 OR t.BL_AGENREMU3112 =1) THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_REMUNERES_F_B,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'C' AND (t.BL_AGENREMUANNE = 1 OR t.BL_AGENREMU3112 =1) THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_REMUNERES_F_C
  FROM ref_categorie rc
	LEFT JOIN temp_apa2cons_dgcljourscarence t ON rc.ID_CATE = t.ID_CATE
  WHERE  rc.bl_vali = 0
  GROUP BY idBilaSociCons;

  INSERT INTO ind_2262 (ID_BILASOCICONS, CD_JOUR_CARENCE, DT_CREA, CD_UTILCREA, DT_MODI, CD_UTILMODI, ORDRE,
        	R_22621, R_22622, R_22623, R_22624, R_22625, R_22626)
  SELECT idBilaSociCons, 'NAAJC',  CURRENT_TIMESTAMP, 'APA', CURRENT_TIMESTAMP, 'APA', 3,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'A' AND t.BL_JOURS_CARENCE = 1 THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_JOURS_CARENCE_H_A,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'B' AND t.BL_JOURS_CARENCE = 1 THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_JOURS_CARENCE_H_B,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'C' AND t.BL_JOURS_CARENCE = 1 THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_JOURS_CARENCE_H_C,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'A' AND t.BL_JOURS_CARENCE = 1 THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_JOURS_CARENCE_F_A,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'B' AND t.BL_JOURS_CARENCE = 1 THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_JOURS_CARENCE_F_B,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'C' AND t.BL_JOURS_CARENCE = 1 THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_JOURS_CARENCE_F_C
  FROM ref_categorie rc
	LEFT JOIN temp_apa2cons_dgcljourscarence t ON rc.ID_CATE = t.ID_CATE
  WHERE  rc.bl_vali = 0
  GROUP BY idBilaSociCons;


  INSERT INTO ind_2262 (ID_BILASOCICONS, CD_JOUR_CARENCE, DT_CREA, CD_UTILCREA, DT_MODI, CD_UTILMODI, ORDRE,
        	R_22621, R_22622, R_22623, R_22624, R_22625, R_22626)
  SELECT idBilaSociCons, 'NAMSJC',  CURRENT_TIMESTAMP, 'APA', CURRENT_TIMESTAMP, 'APA', 4,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'A' AND t.ID_MOTIABSE IN (1,2,9) THEN COALESCE(t.NB_ARRE, 0) ELSE 0 END) AS NB_ARRET_MALADIES_H_A,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'B' AND t.ID_MOTIABSE IN (1,2,9) THEN COALESCE(t.NB_ARRE, 0) ELSE 0 END) AS NB_ARRET_MALADIES_H_B,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'C' AND t.ID_MOTIABSE IN (1,2,9) THEN COALESCE(t.NB_ARRE, 0) ELSE 0 END) AS NB_ARRET_MALADIES_H_C,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'A' AND t.ID_MOTIABSE IN (1,2,9) THEN COALESCE(t.NB_ARRE, 0) ELSE 0 END) AS NB_ARRET_MALADIES_F_A,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'B' AND t.ID_MOTIABSE IN (1,2,9) THEN COALESCE(t.NB_ARRE, 0) ELSE 0 END) AS NB_ARRET_MALADIES_F_B,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'C' AND t.ID_MOTIABSE IN (1,2,9) THEN COALESCE(t.NB_ARRE, 0) ELSE 0 END) AS NB_ARRET_MALADIES_F_C
  FROM ref_categorie rc
	LEFT JOIN temp_apa2cons_dgcljourscarence t ON rc.ID_CATE = t.ID_CATE
  WHERE  rc.bl_vali = 0
  GROUP BY idBilaSociCons;






  INSERT INTO ind_2263 (ID_BILASOCICONS, CD_JOUR_CARENCE, DT_CREA, CD_UTILCREA, DT_MODI, CD_UTILMODI, ORDRE,
        	R_22631, R_22632, R_22633, R_22634, R_22635, R_22636)
  SELECT idBilaSociCons, 'NJCP',  CURRENT_TIMESTAMP, 'APA', CURRENT_TIMESTAMP, 'APA', 0,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'A' THEN COALESCE(t.NB_JOURS_CARENCE, 0) ELSE 0 END) AS NB_JOURS_CARENCE_PRELEVES_H_A,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'B' THEN COALESCE(t.NB_JOURS_CARENCE, 0) ELSE 0 END) AS NB_JOURS_CARENCE_PRELEVES_H_B,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'C' THEN COALESCE(t.NB_JOURS_CARENCE, 0) ELSE 0 END) AS NB_JOURS_CARENCE_PRELEVES_H_C,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'A' THEN COALESCE(t.NB_JOURS_CARENCE, 0) ELSE 0 END) AS NB_JOURS_CARENCE_PRELEVES_F_A,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'B' THEN COALESCE(t.NB_JOURS_CARENCE, 0) ELSE 0 END) AS NB_JOURS_CARENCE_PRELEVES_F_B,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'C' THEN COALESCE(t.NB_JOURS_CARENCE, 0) ELSE 0 END) AS NB_JOURS_CARENCE_PRELEVES_F_C
  FROM ref_categorie rc
	LEFT JOIN temp_apa2cons_dgcljourscarence t ON rc.ID_CATE = t.ID_CATE
  WHERE  rc.bl_vali = 0
  GROUP BY idBilaSociCons;

  INSERT INTO ind_2263 (ID_BILASOCICONS, CD_JOUR_CARENCE, DT_CREA, CD_UTILCREA, DT_MODI, CD_UTILMODI, ORDRE,
        	R_22631, R_22632, R_22633, R_22634, R_22635, R_22636)
  SELECT idBilaSociCons, 'MBSRDC',  CURRENT_TIMESTAMP, 'APA', CURRENT_TIMESTAMP, 'APA', 1,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'A' THEN COALESCE(t.NB_MONTANT_CARENCE, 0) ELSE 0 END) AS NB_SOMME_DELAI_CARENCE_H_A,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'B' THEN COALESCE(t.NB_MONTANT_CARENCE, 0) ELSE 0 END) AS NB_SOMME_DELAI_CARENCE_H_B,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'C' THEN COALESCE(t.NB_MONTANT_CARENCE, 0) ELSE 0 END) AS NB_SOMME_DELAI_CARENCE_H_C,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'A' THEN COALESCE(t.NB_MONTANT_CARENCE, 0) ELSE 0 END) AS NB_SOMME_DELAI_CARENCE_F_A,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'B' THEN COALESCE(t.NB_MONTANT_CARENCE, 0) ELSE 0 END) AS NB_SOMME_DELAI_CARENCE_F_B,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'C' THEN COALESCE(t.NB_MONTANT_CARENCE, 0) ELSE 0 END) AS NB_SOMME_DELAI_CARENCE_F_C
  FROM ref_categorie rc
	LEFT JOIN temp_apa2cons_dgcljourscarence t ON rc.ID_CATE = t.ID_CATE
  WHERE  rc.bl_vali = 0
  GROUP BY idBilaSociCons;

  INSERT INTO ind_2263 (ID_BILASOCICONS, CD_JOUR_CARENCE, DT_CREA, CD_UTILCREA, DT_MODI, CD_UTILMODI, ORDRE,
        	R_22631, R_22632, R_22633, R_22634, R_22635, R_22636)
  SELECT idBilaSociCons, 'NTARSJC',  CURRENT_TIMESTAMP, 'APA', CURRENT_TIMESTAMP, 'APA', 2,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'A' AND (t.BL_AGENREMUANNE = 1 OR t.BL_AGENREMU3112 =1) THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_REMUNERES_H_A,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'B' AND (t.BL_AGENREMUANNE = 1 OR t.BL_AGENREMU3112 =1) THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_REMUNERES_H_B,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'C' AND (t.BL_AGENREMUANNE = 1 OR t.BL_AGENREMU3112 =1) THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_REMUNERES_H_C,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'A' AND (t.BL_AGENREMUANNE = 1 OR t.BL_AGENREMU3112 =1) THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_REMUNERES_F_A,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'B' AND (t.BL_AGENREMUANNE = 1 OR t.BL_AGENREMU3112 =1) THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_REMUNERES_F_B,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'C' AND (t.BL_AGENREMUANNE = 1 OR t.BL_AGENREMU3112 =1) THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_REMUNERES_F_C
  FROM ref_categorie rc
	LEFT JOIN temp_apa2cons_dgcljourscarence t ON rc.ID_CATE = t.ID_CATE
  WHERE  rc.bl_vali = 0
  GROUP BY idBilaSociCons;

  INSERT INTO ind_2263 (ID_BILASOCICONS, CD_JOUR_CARENCE, DT_CREA, CD_UTILCREA, DT_MODI, CD_UTILMODI, ORDRE,
        	R_22631, R_22632, R_22633, R_22634, R_22635, R_22636)
  SELECT idBilaSociCons, 'NAAJC',  CURRENT_TIMESTAMP, 'APA', CURRENT_TIMESTAMP, 'APA', 3,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'A' AND t.BL_JOURS_CARENCE = 1 THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_JOURS_CARENCE_H_A,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'B' AND t.BL_JOURS_CARENCE = 1 THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_JOURS_CARENCE_H_B,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'C' AND t.BL_JOURS_CARENCE = 1 THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_JOURS_CARENCE_H_C,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'A' AND t.BL_JOURS_CARENCE = 1 THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_JOURS_CARENCE_F_A,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'B' AND t.BL_JOURS_CARENCE = 1 THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_JOURS_CARENCE_F_B,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'C' AND t.BL_JOURS_CARENCE = 1 THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_JOURS_CARENCE_F_C
  FROM ref_categorie rc
	LEFT JOIN temp_apa2cons_dgcljourscarence t ON rc.ID_CATE = t.ID_CATE
  WHERE  rc.bl_vali = 0
  GROUP BY idBilaSociCons;


  INSERT INTO ind_2263 (ID_BILASOCICONS, CD_JOUR_CARENCE, DT_CREA, CD_UTILCREA, DT_MODI, CD_UTILMODI, ORDRE,
        	R_22631, R_22632, R_22633, R_22634, R_22635, R_22636)
  SELECT idBilaSociCons, 'NAMSJC',  CURRENT_TIMESTAMP, 'APA', CURRENT_TIMESTAMP, 'APA', 4,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'A' AND t.ID_MOTIABSE IN (1,2,9) THEN COALESCE(t.NB_ARRE, 0) ELSE 0 END) AS NB_ARRET_MALADIES_H_A,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'B' AND t.ID_MOTIABSE IN (1,2,9) THEN COALESCE(t.NB_ARRE, 0) ELSE 0 END) AS NB_ARRET_MALADIES_H_B,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '1' AND rc.CD_CATE = 'C' AND t.ID_MOTIABSE IN (1,2,9) THEN COALESCE(t.NB_ARRE, 0) ELSE 0 END) AS NB_ARRET_MALADIES_H_C,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'A' AND t.ID_MOTIABSE IN (1,2,9) THEN COALESCE(t.NB_ARRE, 0) ELSE 0 END) AS NB_ARRET_MALADIES_F_A,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'B' AND t.ID_MOTIABSE IN (1,2,9) THEN COALESCE(t.NB_ARRE, 0) ELSE 0 END) AS NB_ARRET_MALADIES_F_B,
    SUM(CASE WHEN t.CD_STAT IN ('CONTNONPERM') AND t.CD_SEXE = '2' AND rc.CD_CATE = 'C' AND t.ID_MOTIABSE IN (1,2,9) THEN COALESCE(t.NB_ARRE, 0) ELSE 0 END) AS NB_ARRET_MALADIES_F_C
  FROM ref_categorie rc
	LEFT JOIN temp_apa2cons_dgcljourscarence t ON rc.ID_CATE = t.ID_CATE
  WHERE  rc.bl_vali = 0
  GROUP BY idBilaSociCons;




END
$$