DELIMITER $$

DROP PROCEDURE IF EXISTS apa2cons_ind511
$$

CREATE PROCEDURE apa2cons_ind511(idBilaSociCons INT, idColl INT, idEnqu INT)
COMMENT ''
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
BEGIN


  ### Création et remplissage de la table temporaire
  DROP TEMPORARY TABLE IF EXISTS temp_apa2cons_ind5111;
  CREATE TEMPORARY TABLE temp_apa2cons_ind5111 (INDEX(Q3bis))
    ENGINE = MEMORY
    AS (
      SELECT        
		COALESCE(bsa.CD_SEXE, '-1') AS Q1,
		rs.CD_STAT AS Q2,
		bsa.ID_CATE AS Q3bis	
      FROM bilan_social_agent AS bsa   		
		LEFT OUTER JOIN ref_statut AS rs ON bsa.ID_STAT = rs.ID_STAT  # Q2
      WHERE bsa.ID_COLL = idColl 
        AND bsa.ID_ENQU = idEnqu 
		AND rs.CD_STAT IN ('TITU', 'STAG', 'CONTPERM')  # Q2  
        AND bsa.BL_FORMSUIV = 1       # Q33
		AND bsa.ID_CATE is not null			  # Q3bis	 
    );
	
  ### Remplissage 
  INSERT INTO ind_5111 (ID_BILASOCICONS, ID_CATE, R_51111, R_51112, R_51113, R_51114)
  SELECT idBilaSociCons, c.ID_CATE, 
		SUM(CASE WHEN t.Q1 = 1 AND t.Q2 in ('TITU', 'STAG') THEN 1 ELSE 0 END) AS R_51111,
		SUM(CASE WHEN t.Q1 = 2 AND t.Q2 in ('TITU', 'STAG') THEN 1 ELSE 0 END) AS R_51112,
		SUM(CASE WHEN t.Q1 = 1 AND t.Q2 = 'CONTPERM' THEN 1 ELSE 0 END) AS R_51113,
		SUM(CASE WHEN t.Q1 = 2 AND t.Q2 = 'CONTPERM' THEN 1 ELSE 0 END) AS R_51114
  FROM ref_categorie c
  LEFT JOIN temp_apa2cons_ind5111 t on t.Q3bis = c.ID_CATE
  WHERE c.BL_VALI = 0
  GROUP BY c.ID_CATE
  ORDER BY c.ID_CATE;
  
  
  
  DROP TEMPORARY TABLE IF EXISTS temp_apa2cons_ind5112;
  CREATE TEMPORARY TABLE temp_apa2cons_ind5112 (INDEX(Q3bis))
    ENGINE = MEMORY
    AS (
      SELECT        
		COALESCE(bsa.CD_SEXE, '-1') AS Q1,		
		bsa.ID_CATE AS Q3bis,
		rs.CD_STAT  AS Q2,
		fa.ID_FORM,
		rof.CD_ORGAFORM, 
		count(DISTINCT bsa.ID_BILASOCIAGEN) AS NB_AGEN,
		CASE WHEN fa.BL_CPF = 1 THEN count(DISTINCT bsa.ID_BILASOCIAGEN) ELSE 0 END AS NB_AGEN_CPF,
		sum(fa.NB_JOUR_FORM) AS NB_JOUR_FORM,
		SUM(CASE WHEN fa.BL_CPF = 1 THEN fa.NB_JOUR_FORM ELSE 0 END) AS NB_JOUR_FORM_CPF
      FROM bilan_social_agent AS bsa   		
		LEFT OUTER JOIN ref_statut AS rs ON bsa.ID_STAT = rs.ID_STAT  # Q2
		JOIN formation_agent AS fa ON fa.ID_BILASOCIAGEN = bsa.ID_BILASOCIAGEN
		JOIN ref_organisme_formation rof ON rof.ID_ORGAFORM = fa.ID_ORGAFORM
      WHERE bsa.ID_COLL = idColl 
        AND bsa.ID_ENQU = idEnqu 
		AND rs.CD_STAT IN ('TITU', 'STAG', 'CONTPERM')  
        AND bsa.BL_FORMSUIV = 1       		# Q33
		AND bsa.ID_CATE is not null			# Q3bis	 
	  GROUP BY Q1, Q2, Q3bis, ID_FORM, CD_ORGAFORM
    );
	
	
	 INSERT INTO ind_5112 (ID_BILASOCICONS, ID_CATE, ID_FORM , R_51121, R_51122, R_51123, R_51124, R_51125, R_51126, R_51127, R_51128)
	 SELECT idBilaSociCons, c.ID_CATE, f.ID_FORM,
			SUM(CASE WHEN t.CD_ORGAFORM = 'ORG001' AND t.Q2 IN ('TITU', 'STAG') THEN t.NB_JOUR_FORM ELSE 0 END) AS R_51121,
			SUM(CASE WHEN t.CD_ORGAFORM = 'ORG002' AND t.Q2 IN ('TITU', 'STAG') THEN t.NB_JOUR_FORM ELSE 0 END) AS R_51122,
			SUM(CASE WHEN t.CD_ORGAFORM = 'ORG005' AND t.Q2 IN ('TITU', 'STAG') THEN t.NB_JOUR_FORM ELSE 0 END) AS R_51123,
			SUM(CASE WHEN t.CD_ORGAFORM = 'ORG004' AND t.Q2 IN ('TITU', 'STAG') THEN t.NB_JOUR_FORM ELSE 0 END) AS R_51124,			
			SUM(CASE WHEN t.Q2 IN ('TITU', 'STAG') THEN t.NB_JOUR_FORM_CPF ELSE 0 END) AS R_51125,
			SUM(CASE WHEN t.Q1 = 1  AND t.Q2 IN ('TITU', 'STAG') THEN t.NB_AGEN ELSE 0 END) AS R_51126,
			SUM(CASE WHEN t.Q1 = 2  AND t.Q2 IN ('TITU', 'STAG') THEN t.NB_AGEN ELSE 0 END) AS R_51117,
			SUM(CASE WHEN t.Q2 IN ('TITU', 'STAG') THEN t.NB_AGEN_CPF ELSE 0 END) AS R_51128			
	  FROM ref_categorie c JOIN ref_formation f
	  LEFT JOIN temp_apa2cons_ind5112 t on t.Q3bis = c.ID_CATE and t.ID_FORM = f.ID_FORM
	  WHERE c.BL_VALI = 0
	  AND f.BL_VALI = 0
	  GROUP BY c.ID_CATE, f.ID_FORM
	  ORDER BY c.ID_CATE, f.ID_FORM;
	
	
	INSERT INTO ind_5113 (ID_BILASOCICONS, ID_CATE, ID_FORM , R_51131, R_51132, R_51133, R_51134, R_51135, R_51136, R_51137, R_51138)
	 SELECT idBilaSociCons, c.ID_CATE, f.ID_FORM,
			SUM(CASE WHEN t.CD_ORGAFORM = 'ORG001' AND t.Q2 = 'CONTPERM' THEN t.NB_JOUR_FORM ELSE 0 END) AS R_51131,
			SUM(CASE WHEN t.CD_ORGAFORM = 'ORG002' AND t.Q2 = 'CONTPERM' THEN t.NB_JOUR_FORM ELSE 0 END) AS R_51132,
			SUM(CASE WHEN t.CD_ORGAFORM = 'ORG005' AND t.Q2 = 'CONTPERM' THEN t.NB_JOUR_FORM ELSE 0 END) AS R_51133,
			SUM(CASE WHEN t.CD_ORGAFORM = 'ORG004' AND t.Q2 = 'CONTPERM' THEN t.NB_JOUR_FORM ELSE 0 END) AS R_51134,			
			SUM(CASE WHEN t.Q2 = 'CONTPERM' THEN t.NB_JOUR_FORM_CPF ELSE 0 END) AS R_51135,
			SUM(CASE WHEN t.Q1 = 1  AND t.Q2 = 'CONTPERM' THEN t.NB_AGEN ELSE 0 END) AS R_51136,
			SUM(CASE WHEN t.Q1 = 2  AND t.Q2 = 'CONTPERM' THEN t.NB_AGEN ELSE 0 END) AS R_51137,
			SUM(CASE WHEN t.Q2 = 'CONTPERM' THEN t.NB_AGEN_CPF ELSE 0 END) AS R_51138				
	  FROM ref_categorie c JOIN ref_formation f
	  LEFT JOIN temp_apa2cons_ind5112 t on t.Q3bis = c.ID_CATE and t.ID_FORM = f.ID_FORM
	  WHERE c.BL_VALI = 0
	  AND f.BL_VALI = 0
	  GROUP BY c.ID_CATE, f.ID_FORM
	  ORDER BY c.ID_CATE, f.ID_FORM;
	
	
  
  
END
$$

