DELIMITER $$

DROP PROCEDURE IF EXISTS apa2cons_dgcljourscarence
$$

CREATE PROCEDURE apa2cons_dgcljourscarence(idBilaSociCons INT, idColl INT, idEnqu INT)
COMMENT ''
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
BEGIN
  ### Création et remplissage de la table temporaire
  DROP TEMPORARY TABLE IF EXISTS temp_apa2cons_dgcljourscarence;
  CREATE TEMPORARY TABLE temp_apa2cons_dgcljourscarence (INDEX(CD_SEXE,CD_STAT,ID_CATE))
    ENGINE = MEMORY
    AS (
      SELECT
        bsa.CD_SEXE AS CD_SEXE,
        rs.CD_STAT AS CD_STAT,         # Titulaire=TITU, Stagiaire=STAG, Contractuel sur emploi permanent=CONTPERM, Contractuel sur emploi non permanent=CONTNONPERM
        rc.CD_CATE AS CD_CATE,   # CatA, CatB, CatC, AOTM, ' H', HH
        rc.ID_CATE AS ID_CATE,
        bsad.BL_JOURS_CARENCE  AS BL_JOURS_CARENCE,
        bsad.NB_JOURS_CARENCE  AS NB_JOURS_CARENCE,
        bsad.NB_MONTANT_CARENCE  AS NB_MONTANT_CARENCE,
        aaa.NB_ARRE AS NB_ARRE,
        aaa.ID_MOTIABSE AS ID_MOTIABSE,
        bsa.BL_AGENREMU3112 AS BL_AGENREMU3112, # Q4.1
        bsa.BL_AGENREMUANNE AS BL_AGENREMUANNE  # Q4.2
      FROM bilan_social_agent AS bsa
        JOIN ref_statut AS rs ON bsa.ID_STAT = rs.ID_STAT  # Q2
        LEFT JOIN ref_categorie AS rc ON bsa.ID_CATE = rc.ID_CATE # Q2.8
        LEFT JOIN bilan_social_agent_dgcl bsad ON  bsad.ID_BILASOCIAGEN = bsa.ID_BILASOCIAGEN
        LEFT JOIN absence_arret_agent aaa ON  aaa.ID_BILASOCIAGEN = bsa.ID_BILASOCIAGEN
      WHERE bsa.ID_COLL = idColl
        AND bsa.ID_ENQU = idEnqu
    );

  ### Remplissage de dgcl_jours_carence_titulaire
  INSERT INTO bsc_dgcl_jours_carence_titulaire (ID_BILASOCICONS, ID_CATE, NB_JOURS_CARENCE_PRELEVES_H, NB_JOURS_CARENCE_PRELEVES_F,
    NB_SOMME_DELAI_CARENCE_H, NB_SOMME_DELAI_CARENCE_F, NB_TOTAL_AGENT_REMUNERES_H, NB_TOTAL_AGENT_REMUNERES_F, NB_TOTAL_AGENT_JOURS_CARENCE_H, NB_TOTAL_AGENT_JOURS_CARENCE_F,
    NB_ARRET_MALADIES_H, NB_ARRET_MALADIES_F)
  SELECT idBilaSociCons, rc.ID_CATE,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '1' THEN COALESCE(t.NB_JOURS_CARENCE, 0) ELSE 0 END) AS NB_JOURS_CARENCE_PRELEVES_H,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '2' THEN COALESCE(t.NB_JOURS_CARENCE, 0) ELSE 0 END) AS NB_JOURS_CARENCE_PRELEVES_F,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '1' THEN COALESCE(t.NB_MONTANT_CARENCE, 0) ELSE 0 END) AS NB_SOMME_DELAI_CARENCE_H,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '2' THEN COALESCE(t.NB_MONTANT_CARENCE, 0) ELSE 0 END) AS NB_SOMME_DELAI_CARENCE_F,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '1' AND (t.BL_AGENREMUANNE = 1 OR t.BL_AGENREMU3112 =1) THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_REMUNERES_H,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '2' AND (t.BL_AGENREMUANNE = 1 OR t.BL_AGENREMU3112 =1) THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_REMUNERES_F,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '1' AND t.BL_JOURS_CARENCE = 1 THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_JOURS_CARENCE_H,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '2' AND t.BL_JOURS_CARENCE = 1 THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_JOURS_CARENCE_F,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '1' AND t.ID_MOTIABSE IN (1,2,9) THEN COALESCE(t.NB_ARRE, 0) ELSE 0 END) AS NB_ARRET_MALADIES_H,
    SUM(CASE WHEN t.CD_STAT IN ('TITU', 'STAG') AND t.CD_SEXE = '2' AND t.ID_MOTIABSE IN (1,2,9) THEN COALESCE(t.NB_ARRE, 0) ELSE 0 END) AS NB_ARRET_MALADIES_F
  FROM ref_categorie rc
	LEFT JOIN temp_apa2cons_dgcljourscarence t ON rc.ID_CATE = t.ID_CATE
  WHERE  rc.bl_vali = 0
  GROUP BY idBilaSociCons, rc.ID_CATE
  ORDER BY rc.ID_CATE;

  ### Remplissage de dgcl_jours_carence_titulaire
  INSERT INTO bsc_dgcl_jours_carence_contractuel (ID_BILASOCICONS, ID_CATE, NB_JOURS_CARENCE_PRELEVES_H, NB_JOURS_CARENCE_PRELEVES_F,
    NB_SOMME_DELAI_CARENCE_H, NB_SOMME_DELAI_CARENCE_F, NB_TOTAL_AGENT_REMUNERES_H, NB_TOTAL_AGENT_REMUNERES_F, NB_TOTAL_AGENT_JOURS_CARENCE_H, NB_TOTAL_AGENT_JOURS_CARENCE_F,
    NB_ARRET_MALADIES_H, NB_ARRET_MALADIES_F)
  SELECT idBilaSociCons, rc.ID_CATE,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM', 'CONTNONPERM') AND t.CD_SEXE = '1' THEN COALESCE(t.NB_JOURS_CARENCE, 0) ELSE 0 END) AS NB_JOURS_CARENCE_PRELEVES_H,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM', 'CONTNONPERM') AND t.CD_SEXE = '2' THEN COALESCE(t.NB_JOURS_CARENCE, 0) ELSE 0 END) AS NB_JOURS_CARENCE_PRELEVES_F,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM', 'CONTNONPERM') AND t.CD_SEXE = '1' THEN COALESCE(t.NB_MONTANT_CARENCE, 0) ELSE 0 END) AS NB_SOMME_DELAI_CARENCE_H,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM', 'CONTNONPERM') AND t.CD_SEXE = '2' THEN COALESCE(t.NB_MONTANT_CARENCE, 0) ELSE 0 END) AS NB_SOMME_DELAI_CARENCE_F,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM', 'CONTNONPERM') AND t.CD_SEXE = '1' AND (t.BL_AGENREMUANNE = 1 OR t.BL_AGENREMU3112 =1) THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_REMUNERES_H,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM', 'CONTNONPERM') AND t.CD_SEXE = '2' AND (t.BL_AGENREMUANNE = 1 OR t.BL_AGENREMU3112 =1) THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_REMUNERES_F,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM', 'CONTNONPERM') AND t.CD_SEXE = '1' AND t.BL_JOURS_CARENCE = 1 THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_JOURS_CARENCE_H,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM', 'CONTNONPERM') AND t.CD_SEXE = '2' AND t.BL_JOURS_CARENCE = 1 THEN 1 ELSE 0 END) AS NB_TOTAL_AGENT_JOURS_CARENCE_F,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM', 'CONTNONPERM') AND t.CD_SEXE = '1' AND t.ID_MOTIABSE IN (1,2,9) THEN COALESCE(t.NB_ARRE, 0) ELSE 0 END) AS NB_ARRET_MALADIES_H,
    SUM(CASE WHEN t.CD_STAT IN ('CONTPERM', 'CONTNONPERM') AND t.CD_SEXE = '2' AND t.ID_MOTIABSE IN (1,2,9) THEN COALESCE(t.NB_ARRE, 0) ELSE 0 END) AS NB_ARRET_MALADIES_F
  FROM ref_categorie rc
  LEFT JOIN temp_apa2cons_dgcljourscarence t ON rc.ID_CATE = t.ID_CATE
  WHERE  rc.bl_vali = 0
  GROUP BY idBilaSociCons, rc.ID_CATE
  ORDER BY rc.ID_CATE;


  UPDATE bilan_social_consolide SET MOYENNE_DGCL_JOURS_CARENCE = '100' WHERE ID_BILASOCICONS = idBilaSociCons AND ID_ENQU = idEnqu AND ID_COLL = idColl;

END
$$