<?php

namespace Bilan_Social\Bundle\FaqBundle\Repository;

use Doctrine\ORM\Query;

/**
 * faqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class faqRepository extends \Doctrine\ORM\EntityRepository
{
    function findCategoriesFaq() {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('f.categorie')
                ->from($this->_entityName, 'f')
                ->groupBy('f.categorie');



        try {
            $faqs = $qb->getQuery()->getScalarResult();
            $ids = array_map('current', $faqs);
        } catch (NoResultException $e) {
            // Pas de bilan pour cette enquete et coll
            return null;
        }
        return $ids;
    }

    function findFaqByCollectiviteorCdg($profil) {

        /* $profil doit etre égal:
         *
         *  0 pour une collectivite
         *  1 pour un CDG
         *  et d'office on selectionne aussi ceux qui sont a 2 qui signifie les deux.
         */

        $qb = $this->_em->createQueryBuilder();
        $qb->select('f')
                ->from($this->_entityName, 'f')
                ->where('f.profil = :profil')
                ->orWhere('f.profil = 2')
                ->setParameter(':profil', $profil);



        try {
            $faqs = $qb->getQuery()->getResult();

        } catch (NoResultException $e) {
            // Pas de bilan pour cette enquete et coll
            return null;
        }
        return $faqs;
    }

    public function searchFAQByFilter($profil, $param){

        $filtre = $param['filtre'];
        $value = $param['value'];

        $qb = $this->_em->createQueryBuilder();
        $qb->select('f')
                ->from($this->_entityName, 'f');

                if($profil !== 3){

                $qb->where('f.profil = :profil');
                $qb->orWhere('f.profil = 2');
                $qb->setParameter(':profil', $profil);
                }else{
                     $qb->where('f.profil = 1');
                     $qb->orWhere('f.profil = 2');
                     $qb->orWhere('f.profil = 0');
                }

                if($filtre === '2'){
                     $qb->andWhere('f.question LIKE :value');
                     $qb->setParameter(':value', $value);
                }
                if($filtre === '1'){
                     $qb->andWhere('f.question LIKE :value');
                     $qb->setParameter(':value', '%'.$value.'%');
                }




        try {
            $faqs = $qb->getQuery()->getResult();

        } catch (NoResultException $e) {
            // Pas de bilan pour cette enquete et coll
            return null;
        }
        return $faqs;


    }
}
