SELECT NB_DEPE, LB_ORGA,(
	SELECT COALESCE(SUM(COALESCE(R_5141,0) + COALESCE(R_5142,0) + COALESCE(R_5143,0) + COALESCE(R_5142,0)),0) NB_DEPETOTAL
	FROM bilan_social_consolide b_s_c
	WHERE b_s_c.ID_BILASOCICONS = 1
) NB_TOTAL
FROM(
	SELECT COALESCE(SUM(COALESCE(R_5141,0) + COALESCE(R_5142,0)),0) NB_DEPE, 'CNFPT' LB_ORGA
	FROM bilan_social_consolide
	WHERE ID_BILASOCICONS = 1
	UNION
	SELECT COALESCE(SUM(COALESCE(R_5144,0)),0) NB_DEPE, 'Autres organismes' LB_ORGA
	FROM bilan_social_consolide
	WHERE ID_BILASOCICONS = 1
	UNION
	SELECT COALESCE(SUM(COALESCE(R_5143,0)),0) NB_DEPE, 'En interne' LB_ORGA
	FROM bilan_social_consolide
	WHERE ID_BILASOCICONS = 1
) aggr_depense_formation_by_organisme