SELECT COALESCE(SUM(COALESCE(R_4122,0)),0) NB_JOUR,
COALESCE(SUM(COALESCE(R_4121,0)),0) NB_DEPE
FROM ind_412
JOIN ref_action_prevention  r_a_p ON r_a_p.ID_ACTIONPREV = ind_412.ID_ACTIONPREV
WHERE ID_BILASOCICONS = 87
	AND BL_NBJOUR = 1