SELECT NB_JOUR, LB_CATE, CD_CATE(
	SELECT SUM(NB_JOUR)
	FROM(
		SELECT COALESCE(SUM(COALESCE(R_51121,0) + COALESCE(R_51122,0) + COALESCE(R_51123,0) + COALESCE(R_51124,0)),0) NB_JOUR, 'fonctionnaire' LB_TYPE
		FROM ind_5112
		WHERE ID_BILASOCICONS = 1
		UNION
		SELECT COALESCE(SUM(COALESCE(R_51131,0) + COALESCE(R_51132,0) + COALESCE(R_51133,0) + COALESCE(R_51134,0)),0) NB_JOUR, 'contractuel' LB_TYPE
		FROM ind_5113
		WHERE ID_BILASOCICONS = 1
	) aggr_jour_formation
) NB_TOTAL
FROM(
	SELECT SUM(NB_JOUR) NB_JOUR, LB_CATE, CD_CATE
	FROM(
		SELECT COALESCE(SUM(COALESCE(R_51121,0) + COALESCE(R_51122,0) + COALESCE(R_51123,0) + COALESCE(R_51124,0)),0) NB_JOUR, LB_CATE, CD_CATE, 'fonctionnaire' LB_TYPE
		FROM ind_5112
		JOIN ref_categorie r_c ON r_c.ID_CATE = ind_5112.ID_CATE
		WHERE ID_BILASOCICONS = 1 AND r_c.LB_CATE IN ('A','B','C')
		GROUP BY r_c.ID_CATE
		UNION
		SELECT COALESCE(SUM(COALESCE(R_51131,0) + COALESCE(R_51132,0) + COALESCE(R_51133,0) + COALESCE(R_51134,0)),0) NB_JOUR, LB_CATE, CD_CATE, 'contractuel' LB_TYPE
		FROM ind_5113
		JOIN ref_categorie r_c ON r_c.ID_CATE = ind_5113.ID_CATE
		WHERE ID_BILASOCICONS = 1 AND r_c.LB_CATE IN ('A','B','C')
		GROUP BY r_c.ID_CATE 
	) aggr_formation_fonctionnarie_contractuel_ABC
	GROUP BY LB_CATE
	UNION 
	SELECT SUM(NB_JOUR) NB_JOUR, LB_CATE, CD_CATE
	FROM (
		SELECT COALESCE(SUM(COALESCE(R_51121,0) + COALESCE(R_51122,0) + COALESCE(R_51123,0) + COALESCE(R_51124,0)),0) NB_JOUR, LB_CATE, CD_CATE, 'fonctionnaire' LB_TYPE
		FROM ind_5112
		JOIN ref_categorie r_c ON r_c.ID_CATE = ind_5112.ID_CATE
		WHERE ID_BILASOCICONS = 1 AND r_c.LB_CATE NOT IN ('A','B','C')
		GROUP BY r_c.ID_CATE
		UNION
		SELECT COALESCE(SUM(COALESCE(R_51131,0) + COALESCE(R_51132,0) + COALESCE(R_51133,0) + COALESCE(R_51134,0)),0) NB_JOUR, LB_CATE, CD_CATE, 'contractuel' LB_TYPE
		FROM ind_5113
		JOIN ref_categorie r_c ON r_c.ID_CATE = ind_5113.ID_CATE
		WHERE ID_BILASOCICONS = 1 AND r_c.LB_CATE NOT IN ('A','B','C')
		GROUP BY r_c.ID_CATE 
	) aggr_formation_fonctionnarie_contractuel_other
	GROUP BY LB_CATE
) aggr_formation_by_categorie