SELECT COALESCE(SUM(COALESCE(R_1551,0) + COALESCE(R_1552,0)),0) NB_FONC, (
	SELECT COALESCE(SUM(COALESCE(R_1111,0) + COALESCE(R_1112,0) + COALESCE(R_1113,0) + COALESCE(R_1114,0)),0)
	FROM ind_111 
	WHERE ID_BILASOCICONS = 7
) NB_TOTAL,
COALESCE(r_apc.LB_AVANPROMCONC, "none") LB_PROMO,
r_apc.CD_AVANPROMCONC
FROM ref_avancement_promotion_concours r_apc
LEFT JOIN ind_155
ON r_apc.ID_AVANPROMCONC = ind_155.ID_AVANPROMCONC AND ind_155.ID_BILASOCICONS = 7
WHERE r_apc.CD_AVANPROMCONC NOT IN ("APC004")
GROUP BY r_apc.LB_AVANPROMCONC


