<?php

namespace Bilan_Social\Bundle\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Bilan_Social\Bundle\CoreBundle\Repository\AbstractRepository;

/**
 * ProfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilRepository extends \Doctrine\ORM\EntityRepository
{
	 public function getDefaultQb(){
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('p')
            ->addSelect('n')
            
            ->from($this->_entityName, 'p')
            ->leftJoin('p.nomProfil', 'n');
           
        return $qb;
    }

    public function getById($idProfil){
    
        $qb = $this->getDefaultQb();
        $qb->where('p.idProfil = :id')
            ->setParameter('id',$idProfil);

        return $qb->getQuery()->getOneOrNullResult();
    }
      
}