<?php

namespace Bilan_Social\Bundle\CollectiviteBundle\Repository;

/**
 * DepartementsGroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartementsGroupsRepository extends \Doctrine\ORM\EntityRepository
{
}
