<?php

namespace Bilan_Social\Bundle\ApaBundle\Repository;

/**
 * GpeecRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GpeecRepository extends \Doctrine\ORM\EntityRepository {
}
