<?php

namespace Bilan_Social\Bundle\ApaBundle\Repository;

/**
 * HanditorialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HanditorialRepository extends \Doctrine\ORM\EntityRepository
{
}
