<?php

namespace Bilan_Social\Bundle\ApaBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * BilanSocialAgent Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationGeneraleRepository extends EntityRepository {

    /**
     * @param int $idColl
     *
     * @return array
     */
    public function GetInformationGenerale($idColl, $idEnqu, $idCamp) {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('qg')
                ->from('ApaBundle:InformationGenerale', 'qg')
                ->leftJoin('EnqueteBundle:Enquete', 'e', 'WITH', 'qg.enquete = e.idEnqu')
                ->where('e.idEnqu = :enquete' )
                ->andWhere('qg.collectivite = :collectivite')
                ->andWhere('e.idCamp = :idCamp')
                ->setParameter('enquete', $idEnqu)
                ->setParameter('collectivite', $idColl)
                ->setParameter('idCamp', $idCamp);

        try {
            $informationGenerale = $qb->getQuery()->getOneOrNullResult();
        } catch (NoResultException $e) {
            // Pas de bilan pour cette enquete et coll
            return null;
        }
//        dump($informationGenerale);
//        exit();
        return $informationGenerale;
    }

}
