INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE001', 'Administrateur', 1, 1, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE002', 'Attach� territorial', 1, 1, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE003', 'Secr�taire de mairie', 1, 1, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE004', 'Autres emplois administratifs', 1, 1, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE005', 'Ing�nieur territorial', 1, 2, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE006', 'Autres emplois techniques', 1, 2, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE007', 'Conservateur patrimoine', 1, 3, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE008', 'Conservateur biblioth�ques', 1, 3, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE009', 'Attache de conservation du patrimoine', 1, 3, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE010', 'Biblioth�caire', 1, 3, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE011', 'Directeur etablissement enseignement artistique', 1, 3, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE012', 'Professeur enseignement artistique', 1, 3, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE013', 'Autres emplois culturels', 1, 3, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE014', 'Conseiller activit�s physiques et sportives', 1, 4, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE015', 'Autres emplois sportifs', 1, 4, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE016', 'Conseiller socio educatif', 1, 5, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE017', 'Autres emplois sociaux', 1, 5, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE018', 'M�decin', 1, 6, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE019', 'Psychologue', 1, 6, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE020', 'Sage-femme', 1, 6, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE021', 'Pu�ricultrice cadre de sant�', 1, 6, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE022', 'Pu�ricultrice ancien cadre d''emploi', 1, 6, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE023', 'Pu�ricultrice nouveau cadre d''emploi', 1, 6, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE024', 'Cadre de sant� infirmier r��ducateur et assistant m�dico technique', 1, 6, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE025', 'infirmier en soins g�n�raux', 1, 6, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE026', 'Autres emplois m�dico sociaux', 1, 6, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE027', 'Biologiste v�t�rinaire pharmacien', 1, 7, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE028', 'Autres emplois m�dico techniques', 1, 7, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE029', 'Directeur de police municipale', 1, 8, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE030', 'Autres emplois police municipale', 1, 8, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE031', 'Autres emplois animation', 1, 9, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE032', 'Capitaines, commandants, Lieutenants-colonels, colonels sapeurs pompiers professionnels', 1, 10, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE033', 'M�decins et pharmaciens sapeurs pompiers professionnels', 1, 10, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE034', 'Infirmiers encadrement sapeurs pompiers professionnels', 1, 10, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE035', 'Autres emplois incendie et secours', 1, 10, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE036', 'R�dacteur', 2, 1, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE037', 'Technicien territorial', 2, 2, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE038', 'Assistant conservation patrimoine et biblioth�ques', 2, 3, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE039', 'Assistant enseignement artistique', 2, 3, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE040', 'Edicateur activit�s physiques et sportives', 2, 4, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE041', 'Assistant socio �ducatif', 2, 5, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE042', 'Educateur de jeunes enfants', 2, 5, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE043', 'Moniteur �ducateur et intervenant familial', 2, 5, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE044', 'Infirmier', 2, 6, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE045', 'Technicien param�dical', 2, 7, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE046', 'Chef de service de police municipale', 2, 8, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE047', 'Animateur', 2, 9, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE048', 'Lieutenants sapeurs pompiers professionnels', 2, 10, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE049', 'Infirmiers sapeurs pompiers professionnels', 2, 10, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE050', 'Adjoint administratif', 3, 1, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE051', 'Agent de maitrise', 3, 2, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE052', 'Adjoint technique', 3, 2, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE053', 'Adjoint technique des �tablissements d''enseignement', 3, 2, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE054', 'Adjoint du patrimoine', 3, 3, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE055', 'Op�rateur activit�s physiques et sportives', 3, 4, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE056', 'Agent sp�cialis� des �coles maternelles', 3, 5, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE057', 'Agent social', 3, 5, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE058', 'Auxiliaire pu�riculture', 3, 6, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE059', 'Auxiliaire soins', 3, 6, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE060', 'Agent de police municipale', 3, 8, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE061', 'Garde champ�tre', 3, 8, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE062', 'Adjoint animation', 3, 9, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE063', 'Sous-officiers sapeurs pompiers professionnels', 3, 10, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE064', 'Sapeurs et caporaux sapeurs pompiers professionnels', 3, 10, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE065', 'Autres emplois hors fili�res', 4, 11, 'ADMIN', 0);
INSERT INTO ref_cadre_emploi (CD_CADREMPL, LB_CADREMPL, ID_CATE, ID_FILI, CD_UTILCREA, BL_VALI) VALUES ('CE066', 'Autres', 4, 12, 'ADMIN', 0);
