INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de l''Ain (01)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de l''Aisne (02)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de l''Allier (03)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG des Alpes de Hautes Provence (04)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG des Hautes-Alpes (05)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG des Alpes Maritimes (06)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de l''Ardèche (07)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG des Ardennes (08)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de l''Ariège (09)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de l''Aube (10)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de l''Aude (11)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de l''Aveyron (12)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG des Bouches du Rhône (13)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG du Calvados (14)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG du Cantal (15)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de Charente (16)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de Charente Maritime (17)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG du Cher (18)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Correze (19)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Corse du Sud (2A)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Corse de la Haute Corse (2B)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Côte d''Or (21)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG des Côtes d''Armor (22)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Creuse (23)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Dordogne (24)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG du Doubs (25)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Drôme (26)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de l''Eure (27)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG d''Eure-et-Loir (28)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG du Finistère (29)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG du Gard (30)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Haute-Garonne (31)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG du Gers(32)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Gironde (33)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de l''Hérault (34)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG d''Ille-et-vilaine (35)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de l''Indre (36)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG d''Indre et Loire (37)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de l''Isère (38)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG du Jura (39)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG des Landes (40)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de Loir-et-Cher (41)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Loire (42)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Haute-Loire (43)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Loire-Atlantique (44)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG du Loiret(45)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG du Lot (46)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG du Lot-et-Garonne (47)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Lozère (48)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG du Maine-et-Loire (49)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Manche (50)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Marne (51)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Haute-Marne (52)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Mayenne (53)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Meurthe-et-Moselle (54)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Meuse (55)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG du Morbihan (56)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Moselle (57)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Nièvre (58)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG du Nord (59)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de l''Oise (60)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de l''Orne (61)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG du Pas-de-Calais (62)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG du Puy-de-Dome (63)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG des Pyrénées-Atlantiques (64)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG des Hautes Pyrénées (65)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG des Pyrénées-Orientales (66)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG du Bas-Rhin (67)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG du Haut-Rhin (68)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG du Rhône (69)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Haute-Saône (70)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Saône-et-Loire (71)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Sarthe (72)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Savoie (73)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Haute-Savoie (74)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Seine-Maritime (76)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Seine-et-Marne (77)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG des Deux-Sèvres (79)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Somme (80)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG du Tarn (81)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG du Tarn-et-Garonne (82)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG du Var (83)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG du Vaucluse (84)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Vendée (85)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Vienne (86)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Haute-Vienne (87)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG des Vosges(88)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de l''Yonne (89)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG du Territoire de Belfort (90)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CIG de la Grande Couronne (78-91-95)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CIG de la Petite Couronne (92-93-94)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de Guadeloupe (971)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Martinique (972)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Guyane (973)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de la Réunion (974)', 'ADMIN', now());
INSERT INTO cdg(LB_CDG, CD_UTILCREA, DT_CREA) VALUES ('CDG de Mayotte (976)', 'ADMIN', now());
