INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('111','Administrateur g�n�ral', 1, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('112','Administrateur hors classe', 1, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('113','Administrateur', 1, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('114','Administrateur stagiaire', 1, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('121','Directeur territorial', 2, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('122','Attach� principal', 2, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('123','Attach� territorial', 2, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('124','Attach�', 2, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('131','Secr�taire de mairie', 3, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_1','Emploi sp�cifique A+ fili�re administrative', 4, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_2','Emploi sp�cifique A fili�re administrative', 4, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_3','Temps non complet inf�rieur � 17h30 A+ fili�re administrative ', 4, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_4','Temps non complet inf�rieur � 17h30 A fili�re administrative', 4, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_5','Contractuel sans r�f�rence � un cadre d emploi A+ fili�re administrative', 4, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_6','Contractuel sans r�f�rence � un cadre d emploi A fili�re administrative', 4, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_8','Contractuel CDI A+ fili�re administrative', 4, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_9','Contractuel CDI A fili�re administrative', 4, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('211','Ing�nieur en chef de classe exceptionnelle', 5, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('212','Ing�nieur en chef de classe normale', 5, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('214','Ing�nieur principal', 5, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('215','Ing�nieur', 5, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('213','Ing�nieur en chef', 5, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_10','Emploi sp�cifique A+ fili�re technique', 6, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_11','Emploi sp�cifique A fili�re technique', 6, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_12','Temps non complet inf�rieur � 17h30 A+ fili�re technique ', 6, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_13','Temps non complet inf�rieur � 17h30 A fili�re technique ', 6, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_14','Contractuel sans r�f�rence � un cadre d emploi A+ fili�re technique', 6, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_15','Contractuel sans r�f�rence � un cadre d emploi A fili�re technique', 6, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_16','Contractuel CDI A+ fili�re technique', 6, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_17','Contractuel CDI A fili�re technique', 6, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('311','Conservateur du patrimoine en chef', 7, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('312','Conservateur du patrimoine', 7, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('313','Conservateur du patrimoine stagiaire', 7, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('321','Conservateur des biblioth�ques en chef', 8, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('322','Conservateur des biblioth�ques', 8, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('323','Conservateur des biblioth�ques stagiaire', 8, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('331','Attach� de conservation du patrimoine', 9, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('332','Attach� de conservation du patrimoine stagiaire', 9, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('341','Biblioth�caire', 10, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('342','Biblioth�caire stagiaire', 10, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('351','Directeur �tablissement enseignement artistique 1�re cat�gorie', 11, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('352','Directeur �tablissement enseignement artistique 2�me  cat�gorie', 11, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('353','Directeur �tablissement enseignement artistique stagiaire', 11, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('361','Professeur enseignement artistique hors classe', 12, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('362','Professeur enseignement artistique classe normale', 12, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('363','Professeur enseignement artistique stagiaire', 12, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_18','Emploi sp�cifique A+ fili�re culturelle', 13, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_19','Emploi sp�cifique A fili�re culturelle', 13, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_20','Temps non complet inf�rieur � 17h30 A+ fili�re culturelle', 13, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_21','Temps non complet inf�rieur � 17h30 A fili�re culturelle', 13, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_22','Contractuel sans r�f�rence � un cadre d emploi A+ fili�re culturelle', 13, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_23','Contractuel sans r�f�rence � un cadre d emploi A fili�re culturelle', 13, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_24','Contractuel CDI A+ fili�re culturelle', 13, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_25','Contractuel CDI A fili�re culturelle', 13, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('411','Conseiller activit�s physiques et sportives principal 1�re classe', 14, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('412','Conseiller activit�s physiques et sportives principal 2�me classe', 14, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('413','Conseiller activit�s physiques et sportives', 14, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('414','Conseiller activit�s physiques et sportives stagiaire', 14, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_26','Emploi sp�cifique A+ fili�re sportive', 15, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_27','Emploi sp�cifique A fili�re sportive', 15, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_28','Temps non complet inf�rieur � 17h30 fili�re A+ sportive', 15, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_29','Temps non complet inf�rieur � 17h30 A fili�re sportive', 15, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_30','Contractuel sans r�f�rence � un cadre d emploi A+ fili�re sportive', 15, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_31','Contractuel sans r�f�rence � un cadre d emploi A fili�re sportive', 15, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_32','Contractuel CDI A+ fili�re sportive', 15, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_33','Contractuel CDI A fili�re sportive', 15, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('511','Conseiller socio �ducatif sup�rieur', 16, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('512','Conseiller socio �ducatif', 16, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('513','Conseiller socio �ducatif stagiaire', 16, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_34','Emploi sp�cifique A+ fili�re sociale', 17, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_35','Emploi sp�cifique A fili�re sociale', 17, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_36','Temps non complet inf�rieur � 17h30 A+ fili�re sociale', 17, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_37','Temps non complet inf�rieur � 17h30 A fili�re sociale', 17, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_38','Contractuel sans r�f�rence � un cadre d emploi A+ fili�re sociale', 17, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_39','Contractuel sans r�f�rence � un cadre d emploi A fili�re sociale', 17, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_40','Contractuel CDI A+ fili�re sociale', 17, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_41','Contractuel CDI A fili�re sociale', 17, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('611','M�decin hors classe', 18, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('612','M�decin 1�re classe', 18, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('613','M�decin 2�me classe', 18, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('614','M�decin stagiaire', 18, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('621','Psychologue hors classe', 19, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('622','Psychologue classe normale', 19, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('623','Psychologue stagiaire', 19, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('631','Sage femme classe exceptionnelle', 20, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('632','Sage femme classe sup�rieure', 20, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('633','Sage femme classe normale', 20, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('634','Sage femme stagiaire', 20, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('641','Pu�ricultrice cadre de sant� sup�rieur', 21, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('642','Pu�ricultrice cadre de sant�', 21, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('643','Pu�ricultrice cadre de sant� stagiaire', 21, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('651','Pu�ricultrice classe sup�rieure', 22, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('652','Pu�ricultrice classe normale', 22, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('653','Pu�ricultrice stagiaire', 22, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('65B4','Pu�ricultrice hors classe', 23, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('65B5','Pu�ricultrice classe sup�rieure', 23, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('65B6','Pu�ricultrice classe normale', 23, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('65B7','Pu�ricultrice classe normale stagiaire', 23, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('661','Cadre de sant�', 24, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('662','Cadre de sant� stagiaire', 24, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('671','Infirmier en soins g�n�raux hors classe', 25, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('672','Infirmier en soins g�n�raux classe sup�rieure', 25, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('673','Infirmier en soins g�n�raux classe normale', 25, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('674','Infirmier en soins g�n�raux classe normale stagiaire', 25, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_42','Emploi sp�cifique A+ fili�re m�dico sociale', 26, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_43','Emploi sp�cifique A fili�re m�dico sociale', 26, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_44','Temps non complet inf�rieur � 17h30 A+ fili�re m�dico sociale', 26, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_45','Temps non complet inf�rieur � 17h30 A fili�re m�dico sociale', 26, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_46','Contractuel sans r�f�rence � un cadre d emploi A+ fili�re m�dico sociale', 26, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_47','Contractuel sans r�f�rence � un cadre d emploi A fili�re m�dico sociale', 26, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_48','Contractuel CDI A+ fili�re m�dico sociale', 26, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_49','Contractuel CDI A fili�re m�dico sociale', 26, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('711','Biologiste v�t�rinaire pharmacien classe exceptionnelle', 27, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('712','Biologiste v�t�rinaire pharmacien hors classe', 27, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('713','Biologiste v�t�rinaire pharmacien classe normale', 27, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('714','Biologiste v�t�rinaire pharmacien classe normale stagiaire', 27, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_50','Emploi sp�cifique A+ fili�re m�dico technique', 28, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_51','Emploi sp�cifique A fili�re m�dico technique', 28, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_52','Temps non complet inf�rieur � 17h30 A+ fili�re m�dico technique', 28, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_53','Temps non complet inf�rieur � 17h30 A fili�re m�dico technique', 28, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_54','Contractuel sans r�f�rence � un cadre d emploi A+ fili�re m�dico technique', 28, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_55','Contractuel sans r�f�rence � un cadre d emploi A fili�re m�dico technique', 28, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_56','Contractuel CDI A+ fili�re m�dico technique', 28, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_57','Contractuel CDI A fili�re m�dico technique', 28, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('811','Directeur police municipale principal', 29, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('812','Directeur police municipale', 29, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('813','Directeur police municipale stagiaire', 29, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_58','Emploi sp�cifique A+ fili�re police municipale', 30, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_59','Emploi sp�cifique A fili�re police municipale', 30, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_60','Temps non complet inf�rieur � 17h30 A+ fili�re police municipale', 30, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_61','Temps non complet inf�rieur � 17h30 A fili�re police municipale', 30, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_62','Contractuel sans r�f�rence � un cadre d emploi A+ fili�re police municipale', 30, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_63','Contractuel sans r�f�rence � un cadre d emploi A fili�re police municipale', 30, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_64','Contractuel CDI A+ fili�re police municipale', 30, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_65','Contractuel CDI A fili�re police municipale', 30, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_66','Emploi sp�cifique A+ fili�re animation', 31, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_67','Emploi sp�cifique A fili�re animation', 31, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_68','Temps non complet inf�rieur � 17h30 A+ fili�re animation', 31, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_69','Temps non complet inf�rieur � 17h30 A fili�re animation', 31, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_70','Contractuel sans r�f�rence � un cadre d emploi A+ fili�re animation', 31, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_71','Contractuel sans r�f�rence � un cadre d emploi A fili�re animation', 31, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_72','Contractuel CDI A+ fili�re animation', 31, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_73','Contractuel CDI A fili�re animation', 31, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('1011','Colonel sapeur pompier professionnel', 32, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('1012','Lieutenant colonel sapeur pompier professionnel', 32, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('1013','Commandant sapeur pompier professionnel', 32, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('1014','Capitaine sapeur pompier professionnel', 32, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('1021','M�decin et pharmacien sapeur pompier professionnel classe exceptionnelle', 33, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('1022','M�decin et pharmacien sapeur pompier professionnel hors classe', 33, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('1023','M�decin et pharmacien sapeur pompier professionnel 1�re classe', 33, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('1024','M�decin et pharmacien sapeur pompier professionnel 2�me classe', 33, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('1025','M�decin et pharmacien sapeur pompier professionnel stagiaire', 33, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('1041','Infirmier encadrement sapeur pompier professionnel', 34, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('1042','Infirmier encadrement sapeur pompier professionnel stagiaire', 34, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_74','Emploi sp�cifique A+ fili�re incendie et secours', 35, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_75','Emploi sp�cifique A fili�re incendie et secours', 35, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_76','Temps non complet inf�rieur � 17h30 A+ fili�re incendie et secours', 35, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_77','Temps non complet inf�rieur � 17h30 A fili�re incendie et secours', 35, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_78','Contractuel sans r�f�rence � un cadre d emploi A+ fili�re incendie et secours', 35, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_79','Contractuel sans r�f�rence � un cadre d emploi A fili�re incendie et secours', 35, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_80','Contractuel CDI A+ fili�re incendie et secours', 35, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_81','Contractuel CDI A fili�re incendie et secours', 35, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('141','R�dacteur principal 1�re classe', 36, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('142','R�dacteur principal 2�me classe', 36, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('144','R�dacteur', 36, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('143','R�dacteur principal 2�me classe stagiaire', 36, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('145','R�dacteur stagiaire', 36, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_82','Emploi sp�cifique B fili�re administrative', 4, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_83','Temps non complet inf�rieur � 17h30 B fili�re administrative', 4, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_84','Contractuel sans r�f�rence � un cadre d''emploi B fili�re administrative', 4, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_85','Contractuel CDI B fili�re administrative', 4, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('221','Technicien principal 1�re classe', 37, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('222','Technicien principal 2�me classe', 37, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('224','Technicien', 37, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('223','Technicien principal 2�me classe stagiaire', 37, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('225','Technicien stagiaire', 37, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_86','Emploi sp�cifique B fili�re technique', 6, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_87','Temps non complet inf�rieur � 17h30 B fili�re technique ', 6, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_88','Contractuel sans r�f�rence � un cadre d emploi B fili�re technique', 6, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_89','Contractuel CDI B fili�re technique', 6, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('371','Assistant conservation patrimoine et biblioth�ques principal 1�re classe', 38, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('372','Assistant conservation patrimoine et biblioth�ques principal 2�me classe', 38, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('374','Assistant conservation patrimoine et bilioth�ques', 38, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('373','Assistant conservation patrimoine et biblioth�ques principal 2�me classe stagiaire', 38, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('375','Assistant conservation patrimoine et bilioth�ques stagiaire', 38, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('381','Assistant enseignement artistique principal 1�re classe', 39, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('383','Assistant enseignement artistique principal 2�me classe', 39, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('385','Assistant enseignement artistique', 39, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('384','Assistant enseignement artistique principal 1�re classe stagiaire', 39, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('386','Assistant enseignement artistique stagiaire', 39, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_90','Emploi sp�cifique B fili�re culturelle', 13, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_91','Temps non complet inf�rieur � 17h30 B fili�re culturelle', 13, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_92','Contractuel sans r�f�rence � un cadre d emploi B fili�re culturelle', 13, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_93','Contractuel CDI B fili�re culturelle', 13, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('421','Educateur activit�s physiques et sportives principal 1�re classe', 40, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('422','Educateur activit�s physiques et sportives principal 2�me classe', 40, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('424','Educateur activit�s physiques et sportives', 40, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('423','Educateur activit�s physiques et sportives principal 2�me classe stagiaire', 40, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('425','Educateur activit�s physiques et sportives stagiaire', 40, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_94','Emploi sp�cifique B fili�re sportive', 15, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_95','Temps non complet inf�rieur � 17h30 B fili�re sportive', 15, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_96','Contractuel sans r�f�rence � un cadre d emploi B fili�re sportive', 15, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_97','Contractuel CDI B fili�re sportive', 15, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('521','Assistant socio �ducatif principal', 41, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('522','Assistant socio �ducatif', 41, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('523','Assistant socio �ducatif stagiaire', 41, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('531','Educateur de jeunes enfants principal', 42, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('532','Educateur de jeunes enfants', 42, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('533','Educateur de jeunes enfants stagiaire', 42, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('541','Moniteur �ducateur et intervenant familial principal', 43, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('542','Moniteur �ducateur et intervenant familial', 43, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('543','Moniteur �ducateur et intervenant familial stagiaire', 43, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_95','Emploi sp�cifique B fili�re sociale', 17, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_96','Temps non complet inf�rieur � 17h30 B fili�re sociale', 17, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_97','Contractuel sans r�f�rence � un cadre d emploi B fili�re sociale', 17, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_98','Contractuel CDI B fili�re sociale', 17, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('681','Infirmier classe sup�rieure', 44, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('682','Infirmier classe normale', 44, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('683','Infirmier stagiaire', 44, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_99','Emploi sp�cifique B fili�re m�dico sociale', 26, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_100','Temps non complet inf�rieur � 17h30 B fili�re m�dico sociale', 26, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_101','Contractuel sans r�f�rence � un cadre d emploi B fili�re m�dico sociale', 26, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_102','Contractuel CDI B fili�re m�dico sociale', 26, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('721','Technicien param�dical classe sup�rieure', 45, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('722','Technicien param�dical classe normale', 45, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('723','Technicien param�dical classe normale stagiaire', 45, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_103','Emploi sp�cifique B fili�re m�dico technique', 28, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_104','Temps non complet inf�rieur � 17h30 B fili�re m�dico technique', 28, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_105','Contractuel sans r�f�rence � un cadre d emploi B fili�re m�dico technique', 28, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_106','Contractuel CDI B fili�re m�dico technique', 28, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('821','Chef de service police municipale principal 1�re classe', 46, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('822','Chef de service police municipale principal 2�me classe', 46, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('823','Chef de service police municipale', 46, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_107','Emploi sp�cifique B fili�re police municipale', 30, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_108','Temps non complet inf�rieur � 17h30 B fili�re police municipale', 30, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_109','Contractuel sans r�f�rence � un cadre d emploi B fili�re police municipale', 30, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_110','Contractuel CDI B fili�re police municipale', 30, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('911','Animateur principal 1�re classe', 47, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('912','Animateur principal 2�me classe', 47, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('914','Animateur', 47, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('913','Animateur principal 2�me classe stagiaire', 47, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('915','Animateur stagiaire', 47, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_111','Emploi sp�cifique B fili�re animation', 31, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_112','Temps non complet inf�rieur � 17h30 B fili�re animation', 31, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_113','Contractuel sans r�f�rence � un cadre d emploi B fili�re animation', 31, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_114','Contractuel CDI B fili�re animation', 31, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('1031','Lieutenant sapeur pompier professionnel hors classe', 48, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('1032','Lieutenant sapeur pompier professionnel 1�re classe', 48, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('1033','Lieutenant sapeur pompier professionnels 2�me classe', 48, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('1051','Infirmier sapeur pompier professionnel chef', 49, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('1052','Infirmier sapeur pompier professionnel principal', 49, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('1053','Infirmier sapeur pompier professionnel', 49, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('1054','Infirmier sapeur pompier professionnel stagiaire', 49, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_115','Emploi sp�cifique B fili�re incendie et secours', 35, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_116','Temps non complet inf�rieur � 17h30 B fili�re incendie et secours', 35, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_117','Contractuel sans r�f�rence � un cadre d emploi B fili�re incendie et secours', 35, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_118','Contractuel CDI B fili�re incendie et secours', 35, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('151','Adjoint administratif principal 1�re classe', 50, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('152','Adjoint administratif principal 2�me classe', 50, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('153','Adjoint administratif 1�re classe ', 50, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('154','Adjoint administratif 2�me classe', 50, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_119','Emploi sp�cifique C fili�re administrative', 4, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_120','Temps non complet inf�rieur � 17h30 C fili�re administrative', 4, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_121','Contractuel sans r�f�rence � un cadre d emploi C fili�re administrative', 4, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_122','Contractuel CDI C fili�re administrative', 4, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('231','Agent de ma�trise principal', 51, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('232','Agent de ma�trise', 51, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('241','Adjoint technique principal 1�re classe', 52, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('242','Adjoint technique principal 2�me classe', 52, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('243','Adjoint technique 1�re classe', 52, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('244','Adjoint technique 2�me classe', 52, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('251','Adjoint technique des �tablissements d''enseignement principal 1�re classe', 53, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('252','Adjoint technique des �tablissements d''enseignement principal 2�me classe', 53, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('253','Adjoint technique des �tablissements d''enseignement 1�re classe', 53, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('254','Adjoint technique des �tablissements d''enseignement 2�me classe', 53, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_123','Emploi sp�cifique C fili�re technique', 6, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_124','Temps non complet inf�rieur � 17h30 C fili�re technique ', 6, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_125','Contractuel sans r�f�rence � un cadre d emploi C fili�re technique', 6, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_126','Contractuel CDI C fili�re technique', 6, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('391','Adjoint patrimoine principal 1�re classe', 54, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('392','Adjoint patrimoine principal 2�me classe', 54, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('393','Adjoint patrimoine 1�re classe', 54, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('394','Adjoint patrimoine 2�me classe', 54, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_127','Emploi sp�cifique C fili�re culturelle', 13, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_128','Temps non complet inf�rieur � 17h30 C fili�re culturelle', 13, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_129','Contractuel sans r�f�rence � un cadre d emploi C fili�re culturelle', 13, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_130','Contractuel CDI C fili�re culturelle', 13, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('431','Op�rateur activit�s physiques et sportives principal', 55, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('432','Op�rateur activit�s physiques et sportives qualifi�', 55, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('433','Op�rateur activit�s physiques et sportives', 55, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('434','Aide op�rateur activit�s physiques et sportives', 55, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_131','Emploi sp�cifique C fili�re sportive', 15, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_132','Temps non complet inf�rieur � 17h30 C fili�re sportive', 15, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_133','Contractuel sans r�f�rence � un cadre d emploi C fili�re sportive', 15, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_134','Contractuel CDI C fili�re sportive', 15, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('551','Agent sp�cialis� des �coles maternelles principal 1�re classe', 56, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('552','Agent sp�cialis� des �coles maternelles principal 2�me classe', 56, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('553','Agent sp�cialis� des �coles maternelles 1�re classe', 56, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('561','Agent social principal 1�re classe', 57, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('562','Agent social principal 2�me classe', 57, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('563','Agent social 1�re classe', 57, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('564','Agent social 2�me classe', 57, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_135','Emploi sp�cifique C fili�re sociale', 17, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_136','Temps non complet inf�rieur � 17h30 C fili�re sociale', 17, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_137','Contractuel sans r�f�rence � un cadre d emploi C fili�re sociale', 17, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_138','Contractuel CDI C fili�re sociale', 17, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('691','Auxiliaire pu�riculture principal 1�re classe', 58, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('692','Auxiliaire pu�riculture principal 2�me classe', 58, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('693','Auxiliaire pu�riculture 1�re classe', 58, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('69Z1','Auxiliaire soins principal 1�re classe', 59, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('69Z2','Auxiliaire soins principal 2�me classe', 59, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('69Z3','Auxiliaire soins 1�re classe', 59, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_139','Emploi sp�cifique C fili�re m�dico sociale', 26, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_140','Temps non complet inf�rieur � 17h30 C fili�re m�dico sociale', 26, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_141','Contractuel sans r�f�rence � un cadre d emploi C fili�re m�dico sociale', 26, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_142','Contractuel CDI C fili�re m�dico sociale', 26, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_143','Emploi sp�cifique C fili�re m�dico technique', 28, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_144','Temps non complet inf�rieur � 17h30 C fili�re m�dico technique', 28, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_145','Contractuel sans r�f�rence � un cadre d emploi C fili�re m�dico technique', 28, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_146','Contractuel CDI C fili�re m�dico technique', 28, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('831','Chef de police municipale', 60, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('832','Brigadier chef principal', 60, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('833','Brigadier', 60, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('834','Gardien', 60, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('841','Garde champ�tre chef principal', 61, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('842','Garde champ�tre chef', 61, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('843','Garde champ�tre principal', 61, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_147','Emploi sp�cifique C fili�re police municipale', 30, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_148','Temps non complet inf�rieur � 17h30 C fili�re police municipale', 30, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_149','Contractuel sans r�f�rence � un cadre d emploi C fili�re police municipale', 30, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_150','Contractuel CDI C fili�re police municipale', 30, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('921','Adjoint animation principal 1�re classe', 62, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('922','Adjoint animation principal de 2�me classe', 62, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('923','Adjoint animation 1�re classe', 62, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('924','Adjoint animation 2�me classe', 62, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_151','Emploi sp�cifique C fili�re animation', 31, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_152','Temps non complet inf�rieur � 17h30 C fili�re animation', 31, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_153','Contractuel sans r�f�rence � un cadre d emploi C fili�re animation', 31, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_154','Contractuel CDI C fili�re animation', 31, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('1061','Adjudant sapeur pompier professionnel', 63, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('1062','Sergent sapeur pompier professionnel', 63, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('1071','Caporal chef sapeur pompier professionnel', 64, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('1072','Caporal sapeur pompier professionnel', 64, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('1073','Sapeur sapeur pompier professionnel 1�re classe', 64, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('1074','Sapeur pompier professionnel 2�me classe', 64, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_154','Emploi sp�cifique C fili�re incendie et secours', 35, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_155','Temps non complet inf�rieur � 17h30 C fili�re incendie et secours', 35, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_156','Contractuel sans r�f�rence � un cadre d emploi C fili�re incendie et secours', 35, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_157','Contractuel CDI C fili�re incendie et secours', 35, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_158','Agent sur contrat d''insertion dans la vie sociale (CIVIS) fili�re administrative', 4, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_159','Agent sur contrat unique d''insertion (CUI CAE) fili�re administrative', 4, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_160','Agent sur contrat emploi d avenir fili�re administrative', 4, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_161','Agent sur PACTE fili�re administrative', 4, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_162','Agent sur emploi � statut inconnu fili�re administrative', 4, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_163','Agent sur contrat d''insertion dans la vie sociale (CIVIS) fili�re technique', 6, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_164','Agent sur contrat unique d''insertion (CUI CAE) fili�re technique', 6, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_165','Agent sur contrat emploi d avenir fili�re technique', 6, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_166','Agent sur PACTE fili�re technique', 6, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_167','Agent sur emploi � statut inconnu fili�re technique', 6, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_168','Agent sur contrat d''insertion dans la vie sociale (CIVIS) fili�re culturelle', 13, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_169','Agent sur contrat unique d''insertion (CUI CAE) fili�re culturelle', 13, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_170','Agent sur contrat emploi d avenir fili�re culturelle', 13, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_171','Agent sur PACTE fili�re culturelle', 13, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_172','Agent sur emploi � statut inconnu fili�re culturelle', 13, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_173','Agent sur contrat d''insertion dans la vie sociale (CIVIS) fili�re sportive', 15, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_174','Agent sur contrat unique d''insertion (CUI CAE) fili�re sportive', 15, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_175','Agent sur contrat emploi d avenir fili�re sportive', 15, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_176','Agent sur PACTE fili�re sportive', 15, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_177','Agent sur emploi � statut inconnu fili�re sportive', 15, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_178','Agent sur contrat d''insertion dans la vie sociale (CIVIS) fili�re sociale', 17, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_179','Agent sur contrat unique d''insertion (CUI CAE) fili�re sociale', 17, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_180','Agent sur contrat emploi d avenir fili�re sociale', 17, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_181','Agent sur PACTE fili�re sociale', 17, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_182','Agent sur emploi � statut inconnu fili�re sociale', 17, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_183','Agent sur contrat d''insertion dans la vie sociale (CIVIS) fili�re m�dico sociale', 26, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_184','Agent sur contrat unique d''insertion (CUI CAE) fili�re m�dico sociale', 26, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_185','Agent sur contrat emploi d avenir fili�re m�dico sociale', 26, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_186','Agent sur PACTE fili�re m�dico sociale', 26, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_187','Agent sur emploi � statut inconnu fili�re m�dico sociale', 26, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_188','Agent sur contrat d''insertion dans la vie sociale (CIVIS) fili�re m�dico technique', 28, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_189','Agent sur contrat unique d''insertion (CUI CAE) fili�re m�dico technique', 28, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_190','Agent sur contrat emploi d avenir fili�re m�dico technique', 28, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_191','Agent sur PACTE fili�re m�dico technique', 28, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_192','Agent sur emploi � statut inconnu fili�re m�dico technique', 28, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_193','Agent sur contrat d''insertion dans la vie sociale (CIVIS) fili�re police municipale', 30, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_194','Agent sur contrat unique d''insertion (CUI CAE) fili�re police municipale', 30, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_195','Agent sur contrat emploi d avenir fili�re police municipale', 30, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_196','Agent sur PACTE fili�re police municipale', 30, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_197','Agent sur emploi � statut inconnu fili�re police municipale', 30, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_198','Agent sur contrat d''insertion dans la vie sociale (CIVIS) fili�re animation', 31, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_199','Agent sur contrat unique d''insertion (CUI CAE) fili�re animation', 31, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_200','Agent sur contrat emploi d avenir fili�re animation', 31, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_201','Agent sur PACTE fili�re animation', 31, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_202','Agent sur emploi � statut inconnu fili�re animation', 31, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_203','Agent sur contrat d''insertion dans la vie sociale (CIVIS) fili�re incendie et secours', 35, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_204','Agent sur contrat unique d''insertion (CUI CAE) fili�re incendie et secours', 35, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_205','Agent sur contrat emploi d avenir fili�re incendie et secours', 35, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_206','Agent sur PACTE fili�re incendie et secours', 35, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_207','Agent sur emploi � statut inconnu fili�re incendie et secours', 35, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_207','Fonctionnaire ou contractuel non classable dans une fili�re', 65, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_208','Collaborateur de cabinet', 65, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_209','Assistante maternelle', 65, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_210','Agent territorial de Mayotte', 65, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_211','Ouvrier territorial de Mayotte', 65, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_212','Agent sur contrat d''insertion dans la vie sociale (CIVIS) emplois hors fili�re', 65, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_213','Agent sur contrat unique d''insertion (CUI CAE) emplois hors fili�re', 65, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_214','Agent sur contrat emploi d avenir emplois hors fili�re', 65, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_215','Agent sur PACTE fili�re incendie et secours', 65, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_216','Agent sur emploi � statut inconnu emplois hors fili�re', 65, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_217','Apprenti', 66, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_218','Agent en cong� de fin d''activit�, retrait� du cadre local', 66, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_219','Agent exer�ant des activit�s accessoires autoris�es par la r�glementation sur le cumul d''emploi', 66, 0, 'ADMIN', now());
INSERT INTO ref_grade (CD_GRAD, LB_GRAD, ID_CADREMPL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AUT_220','Autre (non classable dans les rubriques pr�c�dentes)', 66, 0, 'ADMIN', now());
