-- phpMyAdmin SQL Dump
-- version 3.4.10.1deb1
-- http://www.phpmyadmin.net
--
-- Client: localhost
-- Généré le : Mer 22 Novembre 2017 à 15:13
-- Version du serveur: 5.5.24
-- Version de PHP: 5.3.10-1ubuntu3.4

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
--
-- Structure de la table `ref_metier`
--

CREATE TABLE IF NOT EXISTS `ref_metier` (
  `ID_METIER` int(4) unsigned NOT NULL AUTO_INCREMENT,
  `ID_FAMILLE_METIER` int(11) unsigned NULL,
  `CD_METIER` varchar(10) DEFAULT NULL,
  `LB_METIER` varchar(255) NOT NULL,
  `LB_AUTRES_APPELLATIONS_COLLECTIVITES` varchar(255) NOT NULL,
  `CD_N4DS` varchar(50) DEFAULT NULL,
  `BL_METIER_PRINCIPAL` tinyint(1) NOT NULL DEFAULT '1',
  `BL_CONSOLIDE` tinyint(1) NOT NULL DEFAULT '1',
  `BL_VALIDE` tinyint(1) NOT NULL DEFAULT '1',
  `CD_UTILCREA` varchar(50) NOT NULL,
  `created_at` datetime NOT NULL,
  `CD_UTILMODI` varchar(50) NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`ID_METIER`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 COMMENT='Métiers' AUTO_INCREMENT=8 ;

--
-- Contenu de la table `ref_metier`
--

INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (1, "01/A/01",'Directrice / Directeur général-e de collectivité ou d''établissement public', 'DGS', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (1, "02/A/01",'Directrice / Directeur général-e adjoint-e de collectivité ou d''établissement public', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (1, "03/A/01",'Contrôleuse / Contrôleur de gestion', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (1, "04/A/01",'Conseillère / Conseiller en organisation', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (1, "05/A/01",'Chargée / Chargé d''évaluation des politiques publiques', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (2, "01/A/02",'Responsable des affaires générales', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (2, "02/A/02",'Secrétaire de mairie', '', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (2, "03/A/02",'Assistante / Assistant de direction', '', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (2, "05/A/02",'Assistante / Assistant de gestion administrative', 'Agente / Agent administratif Employée / Employé administratif Secrétaire', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (2, "06/A/02",'Chargée / Chargé d''accueil', '', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (2, "07/A/02",'Responsable des services techniques', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (3, "01/A/03",'Responsable des affaires juridiques', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (3, "04/A/03",'Gestionnaire des assurances', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (3, "08/A/03",'Chargée / Chargé de la commande publique', 'Gestionnaire des marchés publics Acheteuse / Acheteur public', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (4, "01/A/04",'Directrice / Directeur financier-ère', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (4, "03/A/04",'Responsable de gestion budgétaire et financière', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (4, "04/A/04",'Responsable de gestion comptable', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (4, "06/A/04",'Coordonnatrice / Coordonnateur budgétaire et comptable', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (4, "07/A/04",'Assistante / Assistant de gestion financière, budgétaire ou comptable', 'Gestionnaires carrière-paie
Assistante / Assitant emploi-formation
Assistante / Assitant de gestion du personnel
', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (5, "01/A/05",'Directrice / Directeur des ressources humaines', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (5, "02/A/05",'Chargée / Chargé du recrutement', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (5, "03/A/05",'Chargée / Chargé de projet GPEEC', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (5, "04/A/05",'Responsable de la gestion administrative du personnel', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (5, "05/A/05",'Responsable de la formation', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (5, "06/A/05",'Conseillère / Conseiller de prévention des risques professionnels', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (5, "07/A/05",'Assistante / Assistant de gestion ressources humaines', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (5, "08/A/05",'Chargée / Chargé de l''inspection en santé et sécurité au travail', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (6, "01/A/06",'Directrice / Directeur des systèmes d''information', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (6, "02/A/06",'Cheffe / Chef de projet des systèmes d''information géographique', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (6, "03/A/06",'Responsable production et support des systèmes d''information', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (6, "04/A/06",'Administratrice / Administrateur systèmes et bases de données', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (6, "05/A/06",'Cheffe / Chef de projet technique des systèmes d''information', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (6, "07/A/06",'Responsable sécurité des systèmes d''information', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (6, "09/A/06",'Cheffe / Chef de projet études et développement des systèmes d''information', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (6, "10/A/06",'Chargée / Chargé des réseaux et télécommunications', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (6, "12/A/06",'Chargée / Chargé de support et services des systèmes d''information', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (6, "13/A/06",'Responsable des études et applications des systèmes d''information', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (7, "01/A/07",'Directrice / Directeur de la communication', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (7, "02/A/07",'Chargée / Chargé de communication', '', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (7, "03/A/07",'Chargée / Chargé de publication', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (7, "04/A/07",'Photographe-vidéaste', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (7, "05/A/07",'Cheffe / Chef de projet communication numérique', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (7, "06/A/07",'Chargée / Chargé de création graphique', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (8, "01/B/08",'Directrice / Directeur du développement territorial', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (8, "02/B/08",'Cheffe / Chef de projet développement territorial', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (8, "03/B/08",'Chargée / Chargé de développement touristique', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (8, "05/B/08",'Chargée / Chargé d''études', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (8, "06/B/08",'Développeuse / Développeur économique', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (8, "07/B/08",'Chargée / Chargé de développement territorial', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (8, "11/B/08",'Chargée / Chargé des affaires européennes et internationales', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (9, "01/B/09",'Directrice / Directeur de l''environnement', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (9, "02/B/09",'Responsable des espaces naturels protégés', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (9, "03/B/09",'Chargée / Chargé d''animation à l''éducation au développement durable', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (9, "04/B/09",'Chargée / Chargé d''études environnement', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (9, "05/B/09",'Garde gestionnaire des espaces naturels', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (9, "06/B/09",'Cheffe / Chef de projet paysage', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (9, "07/B/09",'Cheffe / Chef de projet rivière et milieux aquatiques', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (10, "01/B/10",'Directrice / Directeur de l''urbanisme et de l''aménagement durable', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (10, "02/B/10",'Cheffe / Chef de projet foncier, urbanisme et aménagement', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (10, "04/B/10",'Instructrice / Instructeur des autorisations d''urbanisme', 'Instructrice / Instructeur des permis de construire', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (10, "05/B/10",'Responsable des affaires immobilières et foncières', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (11, "01/B/11",'Responsable des transports et déplacements', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (11, "03/B/11",'Chargée / Chargé de la gestion du réseau de transport', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (11, "04/B/11",'Contrôleuse / Contrôleur du service public de voyageurs', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (11, "05/B/11",'Chargée / Chargé de projet mobilité durable', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (12, "01/B/12",'Directrice / Directeur des politiques de formation professionnelle et de l''apprentissage', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (12, "02/B/12",'Chargée / Chargé des dispositifs de formation professionnelle et d''apprentissage', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (13, "01/B/13",'Responsable de l''habitat et du logement', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (13, "02/B/13",'Directrice / Directeur de la gestion locative', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (13, "04/B/13",'Chargée / Chargé de gestion locative', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (13, "05/B/13",'Gardienne / Gardien d''immeuble', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (14, "01/C/14",'Coordonnatrice / Coordonnateur d''entretien des locaux', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (14, "02/C/14",'Chargée / Chargé de propreté des locaux', 'Agente / Agent d''entretien / de nettoyage polyvalent
Agente / Agent de ménage', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (14, "03/C/14",'Magasinière / Magasinier', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (14, "04/C/14",'Manutentionnaire', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (14, "05/C/14",'Agente / Agent de services polyvalent-e en milieu rural', '', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (14, "06/C/14",'Agente / Agent des interventions techniques polyvalent-e en milieu rural', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (15, "01/C/15",'Responsable d''atelier', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (15, "02/C/15",'Opératrice / Opérateur en maintenance des véhicules et matériels roulants', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (15, "04/C/15",'Carrossière-peintre / Carrossier-peintre', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (15, "05/C/15",'Responsable de flotte de véhicules', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (15, "06/C/15",'Conductrice / Conducteur de véhicule poids lourds', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (15, "07/C/15",'Conductrice / Conducteur d''engins', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (15, "08/C/15",'Conductrice / Conducteur de transports en commun', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (15, "09/C/15",'Chauffeuse / Chauffeur', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (16, "01/C/16",'Cheffe / Chef d''atelier d''imprimerie', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (16, "02/C/16",'Imprimeuse-reprographe / Imprimeur-reprographe', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (16, "03/C/16",'Façonnière / Façonnier', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (17, "01/C/17",'Responsable du partimoine de la voirie et des réseaux divers', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (17, "02/C/17",'Chargée / Chargé de réalisation de travaux voirie et réseaux divers', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (17, "03/C/17",'Cheffe / Chef d''équipe d''entretien et d''exploitation voirie et réseaux divers', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (17, "05/C/17",'Chargée / Chargé d''études et de conception en voirie et réseaux divers', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (17, "06/C/17",'Agente / Agent d''exploitation et d''entretien de la voirie et des réseaux divers', 'Agente / Agent de voirie
Agente / Agent d''entretien de la voirie
Agente / Agent d''exploiration de la voirie', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (17, "07/C/17",'Responsable de port', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (17, "08/C/17",'Agente / Agent de port', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (18, "01/C/18",'Directrice / Directeur espaces verts et biodiversité', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (18, "03/C/18",'Conceptrice / Concepteur paysagiste', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (18, "06/C/18",'Responsable de parc animalier', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (18, "07/C/18",'Animalière / Animalier', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (18, "11/C/18",'Responsable de production végétale', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (18, "14/C/18",'Grimpeuse-élagueuse / Grimpeur-élagueur', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (18, "16/C/18",'Jardinière / Jardinier', 'Agente / Agent des espaces verts', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (18, "17/C/18",'Chargée / Chargé de travaux espaces verts', '', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (19, "02/C/19",'Responsable des bâtiments', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (19, "04/C/19",'Responsable de conception et de réalisation de construction', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (19, "05/C/19",'Chargée / Chargé d''opération de construction', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (19, "07/C/19",'Gestionnaire technique bâtiment', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (19, "08/C/19",'Assistante / Assistant de suivi de travaux bâtiment', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (19, "09/C/19",'Ouvrière / Ouvrier de maintenance des bâtiments', 'Agente / Agent de maintenance polyvalent', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (19, "10/C/19",'Responsable énergie', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (19, "11/C/19",'Responsable d''exploitation des installations de chauffage, ventilation, climatisation', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (19, "12/C/19",'Gestionnaire de flux', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (19, "15/C/19",'Opératrice / Opérateur de maintenance chauffage, ventilation et climatisation', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (19, "16/C/19",'Spécialiste fluides', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (19, "17/C/19",'Dessinatrice / Dessinateur CAO-DAO', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (20, "01/C/20",'Responsable propreté des espaces publics', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (20, "02/C/20",'Agente / Agent de propreté des espaces publics', '', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (20, "04/C/20",'Coordonnatrice / Coordonnateur de collecte', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (20, "05/C/20",'Agente / Agent de collecte', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (20, "09/C/20",'Agente / Agent de déchèterie', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (20, "10/C/20",'Responsable de la gestion des déchets', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (20, "11/C/20",'Responsable traitement des déchets', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (21, "01/C/21",'Directrice / Directeur eau potable et assainissement', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (21, "04/C/21",'Responsable d''exploitation eau potable et assainissement', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (21, "05/C/21",'Agente / Agent chargé-e de contrôle en assainissement collectif et non collectif', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (21, "06/C/21",'Responsable de station de traitement d''eau potable ou d''épuration', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (21, "08/C/21",'Agente / Agent d''entretien réseaux d''eau potable et d''assainissement', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (21, "10/C/21",'Agente / Agent d''entretien stations d''eau potable et d''épuration', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (22, "01/D/22",'Directrice / Directeur de l''action sociale', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (22, "02/D/22",'Cadre en charge de la direction d''établissement et de service social ou médico-social', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (22, "03/D/22",'Responsable de l''aide sociale à l''enfance', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (22, "04/D/22",'Responsable territorial-e d''action sociale', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (22, "05/D/22",'Conseillère / Conseiller d''action sociale', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (22, "06/D/22",'Psychologue', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (22, "07/D/22",'Travailleuse / Travailleur social-e', 'Assistante / Assistant socio-éducatif', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (22, "08/D/22",'Chargée / Chargé d''accueil social', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (22, "09/D/22",'Agente / Agent d''intervention sociale et familiale', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (22, "10/D/22",'Assistante / Assistant familial-e en protection de l''enfance', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (22, "11/D/22",'Aide à domicile', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (22, "12/D/22",'Référente / Référent insertion socioprofessionnelle et professionnelle', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (23, "01/D/23",'Directrice / Directeur enfance-jeunesse-éducation', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (23, "02/D/23",'Coordonnatrice / Coordonnateur enfance-jeunesse-éducation', '', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (23, "03/D/23",'Responsable d''établissement d''accueil du jeune enfant', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (23, "04/D/23",'Animatrice / Animateur de relais assistantes maternelles', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (23, "05/D/23",'Educatrice / Educateur de jeunes enfants', '', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (23, "06/D/23",'Assistante / Assistant éducatif-ve petite enfance', 'Auxiliare de puériculture', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (23, "07/D/23",'Agente / Agent d''accompagnement à l''éducation de l''enfant', 'ATSEM', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (23, "08/D/23",'Directrice / Directeur d''équipement socioculturel', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (23, "09/D/23",'Responsable de structure d''accueil de loisirs', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (23, "10/D/23",'Animatrice / Animateur enfance-jeunesse', '', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (23, "11/D/23",'Animatrice / Animateur éducatif-ve accompagnement périscolaire', '', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (24, "01/D/24",'Directrice / Directeur de la restauration collective', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (24, "03/D/24",'Responsable qualité en restauration collective', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (24, "04/D/24",'Responsable de production culinaire', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (24, "06/D/24",'Cuisinière / Cuisinier', '', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (24, "08/D/24",'Responsable des sites de distribution de repas', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (24, "09/D/24",'Responsable d''office', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (24, "11/D/24",'Agente / Agent de restauration', '', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (25, "01/D/25",'Directrice / Directeur de la santé publique', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (25, "02/D/25",'Médecin', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (25, "03/D/25",'Médecin de médecine préventive', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (25, "04/D/25",'Pharmacienne / Pharmacien', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (25, "05/D/25",'Sage-femme', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (25, "06/D/25",'Coordonnatrice / Coordonnateur de santé', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (25, "07/D/25",'Infirmière / Infirmier', '', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (25, "08/D/25",'Masseuse-kinésithérapeute / Masseur-kinésithérapeute', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (25, "09/D/25",'Orthophoniste', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (25, "10/D/25",'Ergothérapeute', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (25, "11/D/25",'Psychomotricienne / Psychomotricien', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (25, "12/D/25",'Manipulatrice / Manipulateur d''électroradiologie', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (25, "13/D/25",'Puéricultrice / Puériculteur', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (25, "14/D/25",'Aide-soignante / Aide-soignant', 'Auxiliaire de soins', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (25, "16/D/25",'Responsable en santé environnementale', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (25, "17/D/25",'Technicienne / Technicien de santé environnementale', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (25, "18/D/25",'Agente / Agent de santé environnementale', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (26, "01/D/26",'Directrice / Directeur de laboratoire', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (26, "02/D/26",'Responsable qualité en laboratoire', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (26, "03/D/26",'Responsable métrologie', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (26, "04/D/26",'Technicienne / Technicien de laboratoire', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (26, "05/D/26",'Préleveuse / Préleveur', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (26, "06/D/26",'Aide de laboratoire', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (27, "01/D/27",'Responsable du service population', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (27, "02/D/27",'Officière / Officier d''état civil', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (27, "03/D/27",'Directrice / Directeur de régie funéraire', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (27, "04/D/27",'Conservatrice / Conservateur de cimetière', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (27, "05/D/27",'Conseillère / Conseiller funéraire', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (27, "07/D/27",'Maîtresse / Maître de cérémonie', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (27, "08/D/27",'Opératrice / Opérateur de crémation', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (27, "10/D/27",'Agente / Agent funéraire', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (28, "01/D/28",'Directrice / Directeur de l''action culturelle', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (28, "02/D/28",'Cheffe / Chef de projet culturel', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (29, "01/D/29",'Directrice / Directeur d''établissement culturel', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (29, "02/D/29",'Régisseuse / Régisseur de spectacle', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (29, "03/D/29",'Technicienne / technicien du spectacle et de l''évènementiel', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (30, "01/D/30",'Directrice / Directeur de bibliothèque', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (30, "02/D/30",'Bibliothécaire', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (30, "03/D/30",'Chargée / Chargé d''accueil en bibliothèque', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (30, "04/D/30",'Documentaliste', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (31, "01/D/31",'Directrice / Directeur d''établissement d''enseignement artistique', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (31, "02/D/31",'Directrice / Directeur d''établissement d''arts plastiques', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (31, "03/D/31",'Enseignante / Enseignant artistique', '', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (31, "04/D/31",'Enseignante / Enseignant en arts plastiques', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (32, "01/D/32",'Directrice / Directeur d''établissement patrimonial', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (32, "02/D/32",'Archéologue', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (32, "03/D/32",'Archiviste', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (32, "04/D/32",'Médiatrice / Médiateur cultrel-le', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (32, "05/D/32",'Régisseuse / Régisseur d''œuvres', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (32, "06/D/32",'Restauratrice / Restaurateur d''œuvres', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (32, "07/D/32",'Chargée / Chargé d''accueil et de surveillance du patrimoine', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (33, "01/D/33",'Directrice / Directeur du service des sports', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (33, "02/D/33",'Responsable d''équipement sportif', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (33, "03/D/33",'Responsable des activités physiques et sportives', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (33, "04/D/33",'Animatrice-éducatrice / Animateur-éducateur sportif-ve', '', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (33, "05/D/33",'Agente / Agent d''exploitation des équipements sportifs et ludiques', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (34, "01/E/34",'Responsable du service de police municipale', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (34, "02/E/34",'Policière / Policier municipal-e', 'Agent de police municipale
Gardien de police municipale', 1, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (34, "03/E/34",'Garde champêtre', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (34, "04/E/34",'Opératrice / Opérateur de vidéoprotection', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (34, "05/E/34",'Agente / Agent de médiation et de prévention', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (34, "06/E/34",'Agente / Agent de surveillance des voies publiques', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (34, "07/E/34",'Agente / Agent de gardiennage et de surveillance', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (34, "01/E/35",'Directrice / Directeur départemental-e des services d''incendie et de secours', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (35, "02/E/35",'Cheffe / Chef de groupement', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (35, "03/E/35",'Cheffe / Chef de centre d''incendie et secours', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (35, "11/E/35",'Encadrante / Encadrant des opérations de secours', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (35, "12/E/35",'Intervenante / Intervenant des opérations de secours', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (35, "13/E/35",'Prévisionniste', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (35, "14/E/35",'Préventionniste', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (35, "15/E/35",'Opératrice / Opérateur en CTA-CODIS', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (35, "16/E/35",'Médecin Cheffe / Médecin Chef de SDIS', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (35, "17/E/35",'Médecin de SDIS', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (35, "18/E/35",'Pharmacienne / Pharmacien de SDIS', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (35, "19/E/35",'Infirmière / Infirmier de SDIS', '', 0, 1, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (NULL, "FONC/01",'Correspondante / Correspondant informatique et liberté', '', 0, 0, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (NULL, "FONC/02",'Assistante / Assistant en prévention des risques professionnels', '', 0, 0, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (NULL, "FONC/03",'Surveillante / Surveillant de port maritime', '', 0, 0, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (NULL, "FONC/04",'Auxiliaire de surveillance de port maritime', '', 0, 0, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (NULL, "FONC/05",'Tutrice / Tuteur', '', 0, 0, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (NULL, "FONC/06",'Formatrice / Formateur occasionnel-le', '', 0, 0, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (36, "SUP",'Management / Encadrement supérieur', '', 0, 0, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (37, "INTER",'Management / Encadrement intermédiaire', '', 0, 0, 0, 'ADMIN', now(), 'ADMIN', now());
INSERT INTO ref_metier(ID_FAMILLE_METIER, CD_METIER, LB_METIER, LB_AUTRES_APPELLATIONS_COLLECTIVITES, BL_METIER_PRINCIPAL, BL_CONSOLIDE,BL_VALIDE, CD_UTILCREA, created_at, CD_UTILMODI, updated_at) VALUES (38, "PROXI",'Management / Encadrement de proximité', '', 0, 0, 0, 'ADMIN', now(), 'ADMIN', now());


/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
