INSERT INTO ref_motif_depart (CD_MOTIDEPA, LB_MOTIDEPA, BL_VALI, CD_UTILCREA, created_at, BL_DEPATEMP, BL_DEPADEFI, BL_FONC, BL_CONTPERM) VALUES ('MD001', 'Mise � disposition dans une autre collectivit� 
ou structure (Ne prendre en compte que les mises � disposition compl�tes)', 0, 'ADMIN', now(), 1, 0, 1, 1);
INSERT INTO ref_motif_depart (CD_MOTIDEPA, LB_MOTIDEPA, BL_VALI, CD_UTILCREA, created_at, BL_DEPATEMP, BL_DEPADEFI, BL_FONC, BL_CONTPERM) VALUES ('MD002', 'D�charge totale de service pour exercice de mandats syndicaux (article 100)', 0, 'ADMIN', now(), 1, 0, 1, 0);
INSERT INTO ref_motif_depart (CD_MOTIDEPA, LB_MOTIDEPA, BL_VALI, CD_UTILCREA, created_at, BL_DEPATEMP, BL_DEPADEFI, BL_FONC, BL_CONTPERM) VALUES ('MD003', 'Cong� formation encore r�mun�r� par la collectivit� (max 1 an)', 0, 'ADMIN', now(), 1, 0, 1, 1);
INSERT INTO ref_motif_depart (CD_MOTIDEPA, LB_MOTIDEPA, BL_VALI, CD_UTILCREA, created_at, BL_DEPATEMP, BL_DEPADEFI, BL_FONC, BL_CONTPERM) VALUES ('MD004', 'Cong� formation au-del� d''un an', 0, 'ADMIN', now(), 1, 0, 1, 1);
INSERT INTO ref_motif_depart (CD_MOTIDEPA, LB_MOTIDEPA, BL_VALI, CD_UTILCREA, created_at, BL_DEPATEMP, BL_DEPADEFI, BL_FONC, BL_CONTPERM) VALUES ('MD005', 'D�tachement dans une autre structure. Agents de la collectivit� qui ont �t� d�tach�s dans l''ann�e 2017 dans une autre structure (fonction publique d''Etat, fonction publique hospitali�re)', 0, 'ADMIN', now(), 1, 0, 1, 0);
INSERT INTO ref_motif_depart (CD_MOTIDEPA, LB_MOTIDEPA, BL_VALI, CD_UTILCREA, created_at, BL_DEPATEMP, BL_DEPADEFI, BL_FONC, BL_CONTPERM) VALUES ('MD006', 'Mise en disponibilit�', 0, 'ADMIN', now(), 1, 0, 1, 1);
INSERT INTO ref_motif_depart (CD_MOTIDEPA, LB_MOTIDEPA, BL_VALI, CD_UTILCREA, created_at, BL_DEPATEMP, BL_DEPADEFI, BL_FONC, BL_CONTPERM) VALUES ('MD007', 'Cong� parental', 0, 'ADMIN', now(), 1, 0, 1, 1);
INSERT INTO ref_motif_depart (CD_MOTIDEPA, LB_MOTIDEPA, BL_VALI, CD_UTILCREA, created_at, BL_DEPATEMP, BL_DEPADEFI, BL_FONC, BL_CONTPERM) VALUES ('MD008', 'Mutation (changement de collectivit�)', 0, 'ADMIN', now(), 0, 1, 1, 0);
INSERT INTO ref_motif_depart (CD_MOTIDEPA, LB_MOTIDEPA, BL_VALI, CD_UTILCREA, created_at, BL_DEPATEMP, BL_DEPADEFI, BL_FONC, BL_CONTPERM) VALUES ('MD009', 'Fin de d�tachement dans votre collectivit� (agents originaires d''autres structures:fonction publique d''Etat, fonction publique hospitali�re, �dont le d�tachement dans votre collectivit� s''est termin� dans l''ann�e 2017)', 0, 'ADMIN', now(), 0, 1, 1, 0);
INSERT INTO ref_motif_depart (CD_MOTIDEPA, LB_MOTIDEPA, BL_VALI, CD_UTILCREA, created_at, BL_DEPATEMP, BL_DEPADEFI, BL_FONC, BL_CONTPERM) VALUES ('MD010', 'D�charge d''emploi et de fonctions ou agent pris en 
charge par le CNFPT ou le CDG', 0, 'ADMIN', now(), 0, 1, 1, 0);
INSERT INTO ref_motif_depart (CD_MOTIDEPA, LB_MOTIDEPA, BL_VALI, CD_UTILCREA, created_at, BL_DEPATEMP, BL_DEPADEFI, BL_FONC, BL_CONTPERM) VALUES ('MD011', 'Fin de contrat (inclure les d�parts de rempla�ants, ne pas inclure les agents contractuels mis en stage dans l''ann�e 2017)', 0, 'ADMIN', now(), 0, 1, 0, 1);
INSERT INTO ref_motif_depart (CD_MOTIDEPA, LB_MOTIDEPA, BL_VALI, CD_UTILCREA, created_at, BL_DEPATEMP, BL_DEPADEFI, BL_FONC, BL_CONTPERM) VALUES ('MD012', 'D�mission', 0, 'ADMIN', now(), 0, 1, 1, 1);
INSERT INTO ref_motif_depart (CD_MOTIDEPA, LB_MOTIDEPA, BL_VALI, CD_UTILCREA, created_at, BL_DEPATEMP, BL_DEPADEFI, BL_FONC, BL_CONTPERM) VALUES ('MD013', 'D�part � la retraite', 0, 'ADMIN', now(), 0, 1, 1, 1);
INSERT INTO ref_motif_depart (CD_MOTIDEPA, LB_MOTIDEPA, BL_VALI, CD_UTILCREA, created_at, BL_DEPATEMP, BL_DEPADEFI, BL_FONC, BL_CONTPERM) VALUES ('MD014', 'Licenciement', 0, 'ADMIN', now(), 0, 1, 1, 1);
INSERT INTO ref_motif_depart (CD_MOTIDEPA, LB_MOTIDEPA, BL_VALI, CD_UTILCREA, created_at, BL_DEPATEMP, BL_DEPADEFI, BL_FONC, BL_CONTPERM) VALUES ('MD015', 'D�c�s', 0, 'ADMIN', now(), 0, 1, 1, 1);
INSERT INTO ref_motif_depart (CD_MOTIDEPA, LB_MOTIDEPA, BL_VALI, CD_UTILCREA, created_at, BL_DEPATEMP, BL_DEPADEFI, BL_FONC, BL_CONTPERM) VALUES ('MD016', 'Autres cas  (r�vocation, abandon de 
poste, perte de la nationalit� fran�aise, etc.)', 0, 'ADMIN', now(), 0, 1, 1, 1);
INSERT INTO ref_motif_depart (CD_MOTIDEPA, LB_MOTIDEPA, BL_VALI, CD_UTILCREA, created_at, BL_DEPATEMP, BL_DEPADEFI, BL_FONC, BL_CONTPERM) VALUES ('MD017', 'Transfert de comp�tence', 0, 'ADMIN', now(), 0, 1, 1, 1);
INSERT INTO ref_motif_depart (CD_MOTIDEPA, LB_MOTIDEPA, BL_VALI, CD_UTILCREA, created_at, BL_DEPATEMP, BL_DEPADEFI, BL_FONC, BL_CONTPERM) VALUES ('MD018', 'Agent contractuel nomm� stagiaire au sein de la collectivit� au cours de l''ann�e y compris dans le cadre de la loi sauvadet', 0, 'ADMIN', now(), 0, 1, 0, 1);
