INSERT INTO ref_type_collectivite (CD_TYPECOLL, LB_TYPE_COLL, BL_VALI, CD_UTILCREA, created_at) VALUES ('CCN', 'Commune et commune nouvelle', 0, 'ADMIN', now());
INSERT INTO ref_type_collectivite (CD_TYPECOLL, LB_TYPE_COLL, BL_VALI, CD_UTILCREA, created_at) VALUES ('CCAS', 'CCAS', 0, 'ADMIN', now());
INSERT INTO ref_type_collectivite (CD_TYPECOLL, LB_TYPE_COLL, BL_VALI, CD_UTILCREA, created_at) VALUES ('CD', 'Caisse des �coles', 0, 'ADMIN', now());
INSERT INTO ref_type_collectivite (CD_TYPECOLL, LB_TYPE_COLL, BL_VALI, CD_UTILCREA, created_at) VALUES ('CDM', 'Caisse de cr�dit municipal', 0, 'ADMIN', now());
INSERT INTO ref_type_collectivite (CD_TYPECOLL, LB_TYPE_COLL, BL_VALI, CD_UTILCREA, created_at) VALUES ('CIAS', 'Centre Intercommunal d''action sociale (CIAS)', 0, 'ADMIN', now());
INSERT INTO ref_type_collectivite (CD_TYPECOLL, LB_TYPE_COLL, BL_VALI, CD_UTILCREA, created_at) VALUES ('SIVOM', 'SIVOM', 0, 'ADMIN', now());
INSERT INTO ref_type_collectivite (CD_TYPECOLL, LB_TYPE_COLL, BL_VALI, CD_UTILCREA, created_at) VALUES ('SIVU', 'SIVU', 0, 'ADMIN', now());
INSERT INTO ref_type_collectivite (CD_TYPECOLL, LB_TYPE_COLL, BL_VALI, CD_UTILCREA, created_at) VALUES ('SM', 'Syndicat mixte', 0, 'ADMIN', now());
INSERT INTO ref_type_collectivite (CD_TYPECOLL, LB_TYPE_COLL, BL_VALI, CD_UTILCREA, created_at) VALUES ('CCO', 'Communaut� de communes', 0, 'ADMIN', now());
INSERT INTO ref_type_collectivite (CD_TYPECOLL, LB_TYPE_COLL, BL_VALI, CD_UTILCREA, created_at) VALUES ('CAG', 'Communaut� d''agglom�ration', 0, 'ADMIN', now());
INSERT INTO ref_type_collectivite (CD_TYPECOLL, LB_TYPE_COLL, BL_VALI, CD_UTILCREA, created_at) VALUES ('CUR', 'Communaut� urbaine', 0, 'ADMIN', now());
INSERT INTO ref_type_collectivite (CD_TYPECOLL, LB_TYPE_COLL, BL_VALI, CD_UTILCREA, created_at) VALUES ('MET', 'M�tropole', 0, 'ADMIN', now());
INSERT INTO ref_type_collectivite (CD_TYPECOLL, LB_TYPE_COLL, BL_VALI, CD_UTILCREA, created_at) VALUES ('PM', 'P�le m�tropolitain', 0, 'ADMIN', now());
INSERT INTO ref_type_collectivite (CD_TYPECOLL, LB_TYPE_COLL, BL_VALI, CD_UTILCREA, created_at) VALUES ('PETR', 'P�le d''�quilibre territorial et rural (PETR)', 0, 'ADMIN', now());
INSERT INTO ref_type_collectivite (CD_TYPECOLL, LB_TYPE_COLL, BL_VALI, CD_UTILCREA, created_at) VALUES ('DEP', 'D�partement', 0, 'ADMIN', now());
INSERT INTO ref_type_collectivite (CD_TYPECOLL, LB_TYPE_COLL, BL_VALI, CD_UTILCREA, created_at) VALUES ('REG', 'R�gion', 0, 'ADMIN', now());
INSERT INTO ref_type_collectivite (CD_TYPECOLL, LB_TYPE_COLL, BL_VALI, CD_UTILCREA, created_at) VALUES ('SDIS', 'SDIS', 0, 'ADMIN', now());
INSERT INTO ref_type_collectivite (CD_TYPECOLL, LB_TYPE_COLL, BL_VALI, CD_UTILCREA, created_at) VALUES ('CDG', 'CDG', 0, 'ADMIN', now());
INSERT INTO ref_type_collectivite (CD_TYPECOLL, LB_TYPE_COLL, BL_VALI, CD_UTILCREA, created_at) VALUES ('OPH', 'OPHLM - OPAC', 0, 'ADMIN', now());
INSERT INTO ref_type_collectivite (CD_TYPECOLL, LB_TYPE_COLL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AEPC', 'Autre �tablissement public communal*', 0, 'ADMIN', now());
INSERT INTO ref_type_collectivite (CD_TYPECOLL, LB_TYPE_COLL, BL_VALI, CD_UTILCREA, created_at) VALUES ('GIP', 'GIP', 0, 'ADMIN', now());
INSERT INTO ref_type_collectivite (CD_TYPECOLL, LB_TYPE_COLL, BL_VALI, CD_UTILCREA, created_at) VALUES ('AEPI', 'Autre �tablissement public intercommunal', 0, 'ADMIN', now());
INSERT INTO ref_type_collectivite (CD_TYPECOLL, LB_TYPE_COLL, BL_VALI, CD_UTILCREA, created_at) VALUES ('CTOM', 'Collectivit� et territoire d''Outre-Mer', 0, 'ADMIN', now());
INSERT INTO ref_type_collectivite (CD_TYPECOLL, LB_TYPE_COLL, BL_VALI, CD_UTILCREA, created_at) VALUES ('ACT', '(Autre) Collectivit� territoriale **', 0, 'ADMIN', now());
INSERT INTO ref_type_collectivite (CD_TYPECOLL, LB_TYPE_COLL, BL_VALI, CD_UTILCREA, created_at) VALUES ('CNFPT', 'CNFPT', 0, 'ADMIN', now());
