<?php

namespace Bilan_Social\Bundle\ModelMailBundle\Repository;

/**
 * ModelMailCdgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelMailCdgRepository extends \Doctrine\ORM\EntityRepository
{
}
