<?php

namespace Bilan_Social\Bundle\ModelMailBundle\Repository;

/**
 * ModelMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelMailRepository extends \Doctrine\ORM\EntityRepository
{
}
