<?php

namespace Bilan_Social\Bundle\ModelMailBundle\Repository;

/**
 * ModelMailInterneAppliRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelMailInterneAppliCdgRepository extends \Doctrine\ORM\EntityRepository {
}
