-- Mise à jour de la colonne CD_MOTI_N4DS sur le référentiel des grades
UPDATE ref_grade SET CD_MOTI_N4DS = 'TAD3-EAD3-HAD3-MAD3-BAD3' WHERE CD_GRAD = '111';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TAD2-EAD2-HAD2-MAD2-BAD2' WHERE CD_GRAD = '112';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TAD1-EAD1-HAD1-MAD1-BAD1' WHERE CD_GRAD = '113';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SAD1' WHERE CD_GRAD = '114';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TAT3-EAT3-HAT3-MAT3-BAT3' WHERE CD_GRAD = '121';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TAT2-EAT2-HAT2-MAT2-BAT2' WHERE CD_GRAD = '122';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TAT1-EAT1-HAT1-MAT1-BAT1' WHERE CD_GRAD = '123';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SAT1' WHERE CD_GRAD = '124';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TAS1-EAS1-HAS1-MAS1-BAS1' WHERE CD_GRAD = '131';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TAX4-EAX4-HAX4-MAX4' WHERE CD_GRAD = 'AUT_1';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TAX3-EAX3-HAX3-MAX3' WHERE CD_GRAD = 'AUT_2';
UPDATE ref_grade SET CD_MOTI_N4DS = 'EAY4-TAY4-HAY4-MAY4' WHERE CD_GRAD = 'AUT_3';
UPDATE ref_grade SET CD_MOTI_N4DS = 'EAY3-TAY3-HAY3-MAY3' WHERE CD_GRAD = 'AUT_4';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BAX4' WHERE CD_GRAD = 'AUT_5';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BAX3' WHERE CD_GRAD = 'AUT_6';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BAW4' WHERE CD_GRAD = 'AUT_8';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BAW3' WHERE CD_GRAD = 'AUT_9';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TTG4-ETG4-HTG4-MTG4-BTG4' WHERE CD_GRAD = '211';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TTG3-ETG3-HTG3-MTG3-BTG3' WHERE CD_GRAD = '212';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TTG2-ETG2-HTG2-MTG2-BTG2' WHERE CD_GRAD = '214';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TTG1-ETG1-HTG1-MTG1-BTG1-STG1' WHERE CD_GRAD = '215';
UPDATE ref_grade SET CD_MOTI_N4DS = 'STG2' WHERE CD_GRAD = '213';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TTX4-ETX4-HTX4-MTX4' WHERE CD_GRAD = 'AUT_10';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TTX3-ETX3-HTX3-MTX3' WHERE CD_GRAD = 'AUT_11';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TTY4-ETY4-HTY4-MTY4' WHERE CD_GRAD = 'AUT_12';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TTY3-ETY3-HTY3-MTY3' WHERE CD_GRAD = 'AUT_13';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BTX4' WHERE CD_GRAD = 'AUT_14';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BTX3' WHERE CD_GRAD = 'AUT_15';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BTW4' WHERE CD_GRAD = 'AUT_16';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BTW3' WHERE CD_GRAD = 'AUT_17';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCM3-ECM3-HCM3-MCM3-BCM3' WHERE CD_GRAD = '311';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCM2-ECM2-HCM2-MCM2-BCM2' WHERE CD_GRAD = '312';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SCM1' WHERE CD_GRAD = '313';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCH2-ECH2-HCH2-MCH2-BCH2' WHERE CD_GRAD = '321';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCH1-ECH1-HCH1-MCH1-BCH1' WHERE CD_GRAD = '322';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SCH1' WHERE CD_GRAD = '323';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCA1-ECA1-HCA1-MCA1-BCA1' WHERE CD_GRAD = '331';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SCA1' WHERE CD_GRAD = '332';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCB1-ECB1-HCB1-MCB1-BCB1' WHERE CD_GRAD = '341';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SCB1' WHERE CD_GRAD = '342';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCD2-ECD2-HCD2-MCD2-BCD2' WHERE CD_GRAD = '351';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCD1-ECD1-HCD1-MCD1-BCD1' WHERE CD_GRAD = '352';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SCD1' WHERE CD_GRAD = '353';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCP2-ECP2-HCP2-MCP2-BCP2' WHERE CD_GRAD = '361';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCP1-ECP1-HCP1-MCP1-BCP1' WHERE CD_GRAD = '362';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SCP1' WHERE CD_GRAD = '363';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCX4-ECX4-HCX4-MCX4' WHERE CD_GRAD = 'AUT_18';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCX3-ECX3-HCX3-MCX3' WHERE CD_GRAD = 'AUT_19';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCY4-ECY4-HCY4-MCY4' WHERE CD_GRAD = 'AUT_20';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCY3-ECY3-HCY3-MCY3' WHERE CD_GRAD = 'AUT_21';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BCX4' WHERE CD_GRAD = 'AUT_22';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BCX3' WHERE CD_GRAD = 'AUT_23';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BCW4' WHERE CD_GRAD = 'AUT_24';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BCW3' WHERE CD_GRAD = 'AUT_25';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TSC3-ESC3-HSC3-MSC3-BSC3' WHERE CD_GRAD = '411';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TSC2-ESC2-HSC2-MSC2-BSC2' WHERE CD_GRAD = '412';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TSC1-ESC1-HSC1-MSC1-BSC1' WHERE CD_GRAD = '413';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SSC1' WHERE CD_GRAD = '414';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TSX4-ESX4-HSX4-MSX4' WHERE CD_GRAD = 'AUT_26';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TSX3-ESX3-HSX3-MSX3' WHERE CD_GRAD = 'AUT_27';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TSY4-ESY4-HSY4-MSY4' WHERE CD_GRAD = 'AUT_28';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TSY3-ESY3-HSY-MSY3' WHERE CD_GRAD = 'AUT_29';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BSX4' WHERE CD_GRAD = 'AUT_30';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BSX3' WHERE CD_GRAD = 'AUT_31';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BSW4' WHERE CD_GRAD = 'AUT_32';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BSW3' WHERE CD_GRAD = 'AUT_33';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TMM2-EMM2-HMM2-MMM2-BMM2' WHERE CD_GRAD = '511';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TMM1-EMM1-HMM1-MMM1-BMM1' WHERE CD_GRAD = '512';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SMM1' WHERE CD_GRAD = '513';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TMX4-EMX4-HMX4-MMX4' WHERE CD_GRAD = 'AUT_34';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TMX3-EMX3-HMX3-MMX3' WHERE CD_GRAD = 'AUT_35';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TMY4-EMY4-HMY4-MMY4' WHERE CD_GRAD = 'AUT_36';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TMY3-EMY3-HMY3-MMY3' WHERE CD_GRAD = 'AUT_37';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BMX4' WHERE CD_GRAD = 'AUT_38';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BMX3' WHERE CD_GRAD = 'AUT_39';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BMW4' WHERE CD_GRAD = 'AUT_40';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BMW3' WHERE CD_GRAD = 'AUT_41';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOD3-EOD3-HOD3-MOD3-BOD3' WHERE CD_GRAD = '611';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOD2-EOD2-HOD2-MOD2-BOD2' WHERE CD_GRAD = '612';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOD1-EOD1-HOD1-MOD1-BOD1' WHERE CD_GRAD = '613';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SOD1' WHERE CD_GRAD = '614';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOH2-EOH2-HOH2-MOH2-BOH2' WHERE CD_GRAD = '621';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOH1-EOH1-HOH1-MOH1-BOH1' WHERE CD_GRAD = '622';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SOH1' WHERE CD_GRAD = '623';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOF3-EOF3-HOF3-MOF3-BOF3' WHERE CD_GRAD = '631';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOF2-EOF2-HOF2-MOF2-BOF2' WHERE CD_GRAD = '632';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOF1-EOF1-HOF1-MOF1-BOF1' WHERE CD_GRAD = '633';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SOF1' WHERE CD_GRAD = '634';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOC2-EOC2-HOC2-MOC2-BOC2' WHERE CD_GRAD = '641';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOC1-EOC1-HOC1-MOC1-BOC1' WHERE CD_GRAD = '642';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SOC1' WHERE CD_GRAD = '643';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOP2-EOP2-HOP2-MOP2-BOP2' WHERE CD_GRAD = '651';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOP1-EOP1-HOP1-MOP1-BOP1' WHERE CD_GRAD = '652';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SOP1' WHERE CD_GRAD = '653';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOU3-EOU3-HOU3-MOU3-BOU3' WHERE CD_GRAD = '65B4';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOU2-EOU2-HOU2-MOU2-BOU2' WHERE CD_GRAD = '65B5';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOU1-EOU1-HOU1-MOU1-BOU1' WHERE CD_GRAD = '65B6';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SOU1' WHERE CD_GRAD = '65B7';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOA1-EOA1-HOA1-MOA1-BOA1' WHERE CD_GRAD = '661';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SOA1' WHERE CD_GRAD = '662';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOB3-EOB3-HOB3-MOB3-BOB3' WHERE CD_GRAD = '671';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOB2-EOB2-HOB2-MOB2-BOB2' WHERE CD_GRAD = '672';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOB1-EOB1-HOB1-MOB1-BOB1' WHERE CD_GRAD = '673';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SOB1' WHERE CD_GRAD = '674';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TON2-EON2-HON2-MON2-BON2' WHERE CD_GRAD = 'AUT_42';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TON1-EON1-HON1-MON1-BON1' WHERE CD_GRAD = 'AUT_43';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SON1' WHERE CD_GRAD = 'AUT_44';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOY3-EOY3-HOY3-MOY3' WHERE CD_GRAD = 'AUT_45';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BOX4' WHERE CD_GRAD = 'AUT_46';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BOX3' WHERE CD_GRAD = 'AUT_47';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BOW4' WHERE CD_GRAD = 'AUT_48';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BOW3' WHERE CD_GRAD = 'AUT_49';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TEB3-EEB3-HEB3-MEB3-BEB3' WHERE CD_GRAD = '711';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TEB2-EEB2-HEB2-MEB2-BEB2' WHERE CD_GRAD = '712';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TEB1-EEB1-HEB1-MEB1-BEB1' WHERE CD_GRAD = '713';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SEB1' WHERE CD_GRAD = '714';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TEX4-EEX4-HEX4-MEX4' WHERE CD_GRAD = 'AUT_50';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TEX3-EEX3-HEX3-MEX3' WHERE CD_GRAD = 'AUT_51';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TEY4-EEY4-HEY4-MEY4' WHERE CD_GRAD = 'AUT_52';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TEY3-EEY3-HEY3-MEY3' WHERE CD_GRAD = 'AUT_53';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BEX4' WHERE CD_GRAD = 'AUT_54';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BEX3' WHERE CD_GRAD = 'AUT_55';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BEW4' WHERE CD_GRAD = 'AUT_56';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BEW3' WHERE CD_GRAD = 'AUT_57';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TPU2-EPU2-HPU2-MPU2-BPU2' WHERE CD_GRAD = '811';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TPU1-EPU1-HPU1-MPU1-BPU1' WHERE CD_GRAD = '812';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SPU1' WHERE CD_GRAD = '813';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TPX4-EPX4-HPX4-MPX4' WHERE CD_GRAD = 'AUT_58';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TPX3-EPX3-HPX3-MPX3' WHERE CD_GRAD = 'AUT_59';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TPY4-EPY4-HPY4-MPY4' WHERE CD_GRAD = 'AUT_60';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TPY3-EPY3-HPY3-MPY3' WHERE CD_GRAD = 'AUT_61';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BPX4' WHERE CD_GRAD = 'AUT_62';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BPX3' WHERE CD_GRAD = 'AUT_63';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BPW4' WHERE CD_GRAD = 'AUT_64';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BPW3' WHERE CD_GRAD = 'AUT_65';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TNX4-ENX4-HNX4-MNX4' WHERE CD_GRAD = 'AUT_66';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TNX3-ENX3-HNX3-MNX3' WHERE CD_GRAD = 'AUT_67';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TNY4-ENY4-HNY4-MNY4' WHERE CD_GRAD = 'AUT_68';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TNY3-ENY3-HNY3-MNY3' WHERE CD_GRAD = 'AUT_69';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BNX4' WHERE CD_GRAD = 'AUT_70';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BNX3' WHERE CD_GRAD = 'AUT_71';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BNW4' WHERE CD_GRAD = 'AUT_72';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BNW3' WHERE CD_GRAD = 'AUT_73';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRC4-ERC4-HRC4-MRC4-BRC4' WHERE CD_GRAD = '1011';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRC3-ERC3-HRC3-MRC3-BRC3' WHERE CD_GRAD = '1012';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRC2-ERC2-HRC2-MRC2-BRC2' WHERE CD_GRAD = '1013';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRC1-ERC1-HRC1-MRC1-BRC1' WHERE CD_GRAD = '1014';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRD4-ERD4-HRD4-MRD4-BRD4' WHERE CD_GRAD = '1021';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRD3-ERD3-HRD3-MRD3-BRD3' WHERE CD_GRAD = '1022';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRD2-ERD2-HRD2-MRD2-BRD2' WHERE CD_GRAD = '1023';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRD1-ERD1-HRD1-MRD1-BRD1' WHERE CD_GRAD = '1024';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SRD1' WHERE CD_GRAD = '1025';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRA1-ERA1-HRA1-MRA1-BRA1' WHERE CD_GRAD = '1041';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SRA1' WHERE CD_GRAD = '1042';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRX4-ERX4-HRX4-MRX4' WHERE CD_GRAD = 'AUT_74';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRX3-ERX3-HRX3-MRX3' WHERE CD_GRAD = 'AUT_75';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRY4-ERY4-HRY4-MRY4' WHERE CD_GRAD = 'AUT_76';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRY3-ERY3-HRY3-MRY3' WHERE CD_GRAD = 'AUT_77';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BRX4' WHERE CD_GRAD = 'AUT_78';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BRX3' WHERE CD_GRAD = 'AUT_79';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BRW4' WHERE CD_GRAD = 'AUT_80';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BRW3' WHERE CD_GRAD = 'AUT_81';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TAR3-EAR3-HAR3-MAR3-BAR3' WHERE CD_GRAD = '141';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TAR2-EAR2-HAR2-MAR2-BAR2' WHERE CD_GRAD = '142';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TAR1-EAR1-HAR1-MAR1-BAR1' WHERE CD_GRAD = '144';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SAR2' WHERE CD_GRAD = '143';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SAR1' WHERE CD_GRAD = '145';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TAX2-EAX2-HAX2-MAX2' WHERE CD_GRAD = 'AUT_82';
UPDATE ref_grade SET CD_MOTI_N4DS = 'EAY2-TAY2-HAY2-MAY2' WHERE CD_GRAD = 'AUT_83';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BAX2' WHERE CD_GRAD = 'AUT_84';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BAW2' WHERE CD_GRAD = 'AUT_85';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TTT3-ETT3-HTT3-MTT3-BTT3' WHERE CD_GRAD = '221';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TTT2-ETT2-HTT2-MTT2-BTT2' WHERE CD_GRAD = '222';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TTT1-ETT1-HTT1-MTT1-BTT1' WHERE CD_GRAD = '224';
UPDATE ref_grade SET CD_MOTI_N4DS = 'STT2' WHERE CD_GRAD = '223';
UPDATE ref_grade SET CD_MOTI_N4DS = 'STT1' WHERE CD_GRAD = '225';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TTX2-ETX2-HTX2-MTX2' WHERE CD_GRAD = 'AUT_86';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TTY2-ETY2-HTY2-MTY2' WHERE CD_GRAD = 'AUT_87';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BTX2' WHERE CD_GRAD = 'AUT_88';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BTW2' WHERE CD_GRAD = 'AUT_89';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCG3-ECG3-HCG3-MCG3-BCG3' WHERE CD_GRAD = '371';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCG2-ECG2-HCG2-MCG2-BCG2' WHERE CD_GRAD = '372';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCG1-ECG1-HCG1-MCG1-BCG1' WHERE CD_GRAD = '374';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SCG2' WHERE CD_GRAD = '373';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SCG1' WHERE CD_GRAD = '375';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCS3-ECS3-HCS3-MCS3-BCS3' WHERE CD_GRAD = '381';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCS2-ECS2-HCS2-MCS2-BCS2' WHERE CD_GRAD = '383';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCS1-ECS1-HCS1-MCS1-BCS1' WHERE CD_GRAD = '385';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SCS3' WHERE CD_GRAD = '384';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SCS2' WHERE CD_GRAD = '386';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCX2-ECX2-HCX2-MCX2' WHERE CD_GRAD = 'AUT_90';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCY2-ECY2-HCY2-MCY2' WHERE CD_GRAD = 'AUT_91';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BCX2' WHERE CD_GRAD = 'AUT_92';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BCW2' WHERE CD_GRAD = 'AUT_93';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TSE3-ESE3-HSE3-MSE3-BSE3' WHERE CD_GRAD = '421';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TSE2-ESE2-HSE2-MSE2-BSE2' WHERE CD_GRAD = '422';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TSE1-ESE1-HSE1-MSE1-BSE1' WHERE CD_GRAD = '424';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SSE2' WHERE CD_GRAD = '423';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SSE1' WHERE CD_GRAD = '425';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TSX2-ESX2-HSX2-MSX2' WHERE CD_GRAD = 'AUT_94';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TSY2-ESY2-HSY2-MSY2' WHERE CD_GRAD = 'AUT_95';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BSX2' WHERE CD_GRAD = 'AUT_96';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BSW2' WHERE CD_GRAD = 'AUT_97';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TMH2-EMH2-HMH2-MMH2-BMH2' WHERE CD_GRAD = '521';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TMH1-EMH1-HMH1-MMH1-BMH1' WHERE CD_GRAD = '522';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SMH1' WHERE CD_GRAD = '523';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TMA2-EMA2-HMA2-MMA2-BMA2' WHERE CD_GRAD = '531';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TMA1-EMA1-HMA1-MMA1-BMA1' WHERE CD_GRAD = '532';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SMA1' WHERE CD_GRAD = '533';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TMB2-EMB2-HMB2-MMB2-BMB2' WHERE CD_GRAD = '541';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TMB1-EMB1-HMB1-MMB1-BMB1' WHERE CD_GRAD = '542';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SMB1' WHERE CD_GRAD = '543';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TMX2-EMX2-HMX2-MMX2' WHERE CD_GRAD = 'AUT_95';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TMY2-EMY2-HMY2-MMY2' WHERE CD_GRAD = 'AUT_96';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BMX2' WHERE CD_GRAD = 'AUT_97';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BMW2' WHERE CD_GRAD = 'AUT_98';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TON2-EON2-HON2-MON2-BON2' WHERE CD_GRAD = '681';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TON1-EON1-HON1-MON1-BON1' WHERE CD_GRAD = '682';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SON1' WHERE CD_GRAD = '683';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOX2-EOX2-HOX2-MOX2' WHERE CD_GRAD = 'AUT_99';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOY2-EOY2-HOY2-MOY2' WHERE CD_GRAD = 'AUT_100';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BOX2' WHERE CD_GRAD = 'AUT_101';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BOW2' WHERE CD_GRAD = 'AUT_102';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TET2-EET2-HET2-MET2-BET2' WHERE CD_GRAD = '721';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TET1-EET1-HET1-MET1-BET1' WHERE CD_GRAD = '722';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SET1' WHERE CD_GRAD = '723';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TEX2-EEX2-HEX2-MEX2' WHERE CD_GRAD = 'AUT_103';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TEY2-EEY2-HEY2-MEY2' WHERE CD_GRAD = 'AUT_104';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BEX2' WHERE CD_GRAD = 'AUT_105';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BEW2' WHERE CD_GRAD = 'AUT_106';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TPC3-EPC3-HPC3-MPC3-BPC3' WHERE CD_GRAD = '821';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TPC2-EPC2-HPC2-MPC2-BPC2' WHERE CD_GRAD = '822';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TPC1-EPC1-HPC1-MPC1-BPC1-SPC1' WHERE CD_GRAD = '823';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SPC1' WHERE CD_GRAD = 'AUT_107';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TPY2-EPY2-HPY2-MPY2' WHERE CD_GRAD = 'AUT_108';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BPX2' WHERE CD_GRAD = 'AUT_109';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BPW2' WHERE CD_GRAD = 'AUT_110';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TNN3-ENN3-HNN3-MNN3-BNN3' WHERE CD_GRAD = '911';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TNN2-ENN2-HNN2-MNN2-BNN2' WHERE CD_GRAD = '912';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TNN1-ENN1-HNN1-MNN1-BNN1' WHERE CD_GRAD = '914';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SNN2' WHERE CD_GRAD = '913';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SNN1' WHERE CD_GRAD = '915';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TNX2-ENX2-HNX2-MNX2' WHERE CD_GRAD = 'AUT_111';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TNY2-ENY2-HNY2-MNY2' WHERE CD_GRAD = 'AUT_112';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BNX2' WHERE CD_GRAD = 'AUT_113';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BNW2' WHERE CD_GRAD = 'AUT_114';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRL3-ERL3-HRL3-MRL3-BRL3' WHERE CD_GRAD = '1031';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRL2-ERL2-HRL2-MRL2-BRL2-SRL2' WHERE CD_GRAD = '1032';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRL1-ERL1-HRL1-MRL1-BRL1-SRL1' WHERE CD_GRAD = '1033';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRN3-ERN3-HRN3-MRN3-BRN3' WHERE CD_GRAD = '1051';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRN2-ERN2-HRN2-MRN2-BRN2' WHERE CD_GRAD = '1052';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRN1-ERN1-HRN1-MRN1-BRN1' WHERE CD_GRAD = '1053';
UPDATE ref_grade SET CD_MOTI_N4DS = 'SRS1' WHERE CD_GRAD = '1054';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRX2-ERX2-HRX2-MRX2' WHERE CD_GRAD = 'AUT_115';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRY2-ERY2-HRY2-MRY2' WHERE CD_GRAD = 'AUT_116';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BRX2' WHERE CD_GRAD = 'AUT_117';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BRW2' WHERE CD_GRAD = 'AUT_118';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TAJ4-EAJ4-HAJ4-MAJ4-BAJ4' WHERE CD_GRAD = '151';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TAJ3-EAJ3-HAJ3-MAJ3-BAJ3' WHERE CD_GRAD = '152';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TAJ2-EAJ2-HAJ2-MAJ2-BAJ2-SAJ2' WHERE CD_GRAD = '153';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TAJ1-EAJ1-HAJ1-MAJ1-BAJ1-SAJ1' WHERE CD_GRAD = '154';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TAX1-EAX1-HAX1-MAX1' WHERE CD_GRAD = 'AUT_119';
UPDATE ref_grade SET CD_MOTI_N4DS = 'EAY1-TAY1-HAY1-MAY1' WHERE CD_GRAD = 'AUT_120';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BAX2' WHERE CD_GRAD = 'AUT_121';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BAW1' WHERE CD_GRAD = 'AUT_122';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TTM2-ETM2-HTM2-MTM2-BTM2' WHERE CD_GRAD = '231';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TTM1-ETM1-HTM1-MTM1-BTM1-STM1' WHERE CD_GRAD = '232';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TTH4-ETH4-HTH4-MTH4-BTH4' WHERE CD_GRAD = '241';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TTH3-ETH3-HTH3-MTH3-BTH3' WHERE CD_GRAD = '242';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TTH2-ETH2-HTH2-MTH2-BTH2-STH2' WHERE CD_GRAD = '243';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TTH1-ETH1-HTH1-MTH1-BTH1-STH1' WHERE CD_GRAD = '244';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TTA4-ETA4-HTA4-MTA4-BTA4' WHERE CD_GRAD = '251';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TTA3-ETA3-HTA3-MTA3-BTA3-STA3' WHERE CD_GRAD = '252';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TTA2-ETA2-HTA2-MTA2-BTA2-STA2' WHERE CD_GRAD = '253';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TTA1-ETA1-HTA1-MTA1-BTA1-STA1' WHERE CD_GRAD = '254';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TTX1-ETX1-HTX1-MTX1' WHERE CD_GRAD = 'AUT_123';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TTY1-ETY1-HTY1-MTY1' WHERE CD_GRAD = 'AUT_124';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BTX1' WHERE CD_GRAD = 'AUT_125';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BTW1' WHERE CD_GRAD = 'AUT_126';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCJ4-ECJ4-HCJ4-MCJ4-BCJ4' WHERE CD_GRAD = '391';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCJ3-ECJ3-HCJ3-MCJ3-BCJ3' WHERE CD_GRAD = '392';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCJ2-ECJ2-HCJ2-MCJ2-BCJ2-SCJ2' WHERE CD_GRAD = '393';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCJ1-ECJ1-HCJ1-MCJ1-BCJ1-SCJ1' WHERE CD_GRAD = '394';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCX1-ECX1-HCX1-MCX1' WHERE CD_GRAD = 'AUT_127';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TCY1-ECY1-HCY1-MCY1' WHERE CD_GRAD = 'AUT_128';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BCX1' WHERE CD_GRAD = 'AUT_129';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BCW1' WHERE CD_GRAD = 'AUT_130';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TSP4-ESP4-HSP4-MSP4-BSP4' WHERE CD_GRAD = '431';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TSP3-ESP3-HSP3-MSP3-BSP3' WHERE CD_GRAD = '432';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TSP2-ESP2-HSP2-MSP2-BSP2-SSP1' WHERE CD_GRAD = '433';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TSP1-ESP1-HSP1-MSP1-BSP1' WHERE CD_GRAD = '434';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TSX1-ESX1-HSX1-MSX1' WHERE CD_GRAD = 'AUT_131';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TSY1-ESY1-HSY1-MSY1' WHERE CD_GRAD = 'AUT_132';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BSX1' WHERE CD_GRAD = 'AUT_133';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BSW1' WHERE CD_GRAD = 'AUT_134';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TMD3-EMD3-HMD3-MMD3-BMD3' WHERE CD_GRAD = '551';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TMD2-EMD2-HMD2-MMD2-BMD2' WHERE CD_GRAD = '552';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TMD1-EMD1-HMD1-MMD1-BMD1-SMD1' WHERE CD_GRAD = '553';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TMP4-EMP4-HMP4-MMP4-BMP4' WHERE CD_GRAD = '561';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TMP3-EMP3-HMP3-MMP3-BMP3' WHERE CD_GRAD = '562';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TMP2-EMP2-HMP2-MMP2-BMP2-SMP2' WHERE CD_GRAD = '563';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TMP1-EMP1-HMP1-MMP1-BMP1-SMP1' WHERE CD_GRAD = '564';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TMX1-EMX1-HMX1-MMX1' WHERE CD_GRAD = 'AUT_135';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TMY1-EMY1-HMY1-MMY1' WHERE CD_GRAD = 'AUT_136';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BMX1' WHERE CD_GRAD = 'AUT_137';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BMW1' WHERE CD_GRAD = 'AUT_138';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOJ3-EOJ3-HOJ3-MOJ3-BOJ3' WHERE CD_GRAD = '691';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOJ2-EOJ2-HOJ2-MOJ2-BOJ2' WHERE CD_GRAD = '692';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOJ1-EOJ1-HOJ1-MOJ1-BOJ1-SOJ1' WHERE CD_GRAD = '693';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOK3-EOK3-HOK3-MOK3-BOK3' WHERE CD_GRAD = '69Z1';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOK2-EOK2-HOK2-MOK2-BOK2' WHERE CD_GRAD = '69Z2';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOK1-EOK1-HOK1-MOK1-BOK1-SOK1' WHERE CD_GRAD = '69Z3';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOX1-EOX1-HOX1-MOX1' WHERE CD_GRAD = 'AUT_139';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TOY1-EOY1-HOY1-MOY1' WHERE CD_GRAD = 'AUT_140';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BOX1' WHERE CD_GRAD = 'AUT_141';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BOW1' WHERE CD_GRAD = 'AUT_142';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TEX1-EEX1-HEX1-MEX1' WHERE CD_GRAD = 'AUT_143';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TEY1-EEY1-HEY1-MEY1' WHERE CD_GRAD = 'AUT_144';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BEX1' WHERE CD_GRAD = 'AUT_145';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BEW1' WHERE CD_GRAD = 'AUT_146';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TPG4-EPG4-HPG4-MPG4-BPG4' WHERE CD_GRAD = '831';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TPG3-EPG3-HPG3-MPG3-BPG3' WHERE CD_GRAD = '832';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TPG2-EPG2-HPG2-MPG2-BPG2' WHERE CD_GRAD = '833';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TPG1-EPG1-HPG1-MPG1-BPG1-SPG1' WHERE CD_GRAD = '834';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TPH3-EPH3-HPH3-MPH3-BPH3' WHERE CD_GRAD = '841';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TPH2-EPH2-HPH2-MPH2-BPH2' WHERE CD_GRAD = '842';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TPH1-EPH1-HPH1-MPH1-BPH1-SPH1' WHERE CD_GRAD = '843';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TPX1-EPX1-HPX1-MPX1' WHERE CD_GRAD = 'AUT_147';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TPY1-EPY1-HPY1-MPY1' WHERE CD_GRAD = 'AUT_148';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BPX1' WHERE CD_GRAD = 'AUT_149';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BPW1' WHERE CD_GRAD = 'AUT_150';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TNJ4-ENJ4-HNJ4-MNJ4-BNJ4' WHERE CD_GRAD = '921';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TNJ3-ENJ3-HNJ3-MNJ3-BNJ3' WHERE CD_GRAD = '922';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TNJ2-ENJ2-HNJ2-MNJ2-BNJ2-SNJ2' WHERE CD_GRAD = '923';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TNJ1-ENJ1-HNJ1-MNJ1-BNJ1-SNJ1' WHERE CD_GRAD = '924';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TNX1-ENX1-HNX1-MNX1' WHERE CD_GRAD = 'AUT_151';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TNY1-ENY1-HNY1-MNY1' WHERE CD_GRAD = 'AUT_152';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BNX1' WHERE CD_GRAD = 'AUT_153';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BNW1' WHERE CD_GRAD = 'AUT_154';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRS2-ERS2-HRS2-MRS2-BRS2' WHERE CD_GRAD = '1061';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRS1-ERS1-HRS1-MRS1-BRS1-SRS1' WHERE CD_GRAD = '1062';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRU4-ERU4-HRU4-MRU4-BRU4' WHERE CD_GRAD = '1071';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRU3-ERU3-HRU3-MRU3-BRU3' WHERE CD_GRAD = '1072';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRU2-ERU2-HRU2-MRU2-BRU2-SRU2' WHERE CD_GRAD = '1073';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRU1-ERU1-HRU1-MRU1-BRU1-SRU1' WHERE CD_GRAD = '1074';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRX1-ERX1-HRX1-MRX1' WHERE CD_GRAD = 'AUT_154';
UPDATE ref_grade SET CD_MOTI_N4DS = 'TRY1-ERY1-HRY1-MRY1' WHERE CD_GRAD = 'AUT_155';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BRX1' WHERE CD_GRAD = 'AUT_156';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BRW1' WHERE CD_GRAD = 'AUT_157';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NAX1' WHERE CD_GRAD = 'AUT_158';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NAX2' WHERE CD_GRAD = 'AUT_159';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NAX3' WHERE CD_GRAD = 'AUT_160';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NAX4' WHERE CD_GRAD = 'AUT_161';
UPDATE ref_grade SET CD_MOTI_N4DS = 'XAX1' WHERE CD_GRAD = 'AUT_162';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NTX1' WHERE CD_GRAD = 'AUT_163';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NTX2' WHERE CD_GRAD = 'AUT_164';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NTX3' WHERE CD_GRAD = 'AUT_165';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NTX4' WHERE CD_GRAD = 'AUT_166';
UPDATE ref_grade SET CD_MOTI_N4DS = 'XTX1' WHERE CD_GRAD = 'AUT_167';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NCX1' WHERE CD_GRAD = 'AUT_168';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NCX2' WHERE CD_GRAD = 'AUT_169';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NCX3' WHERE CD_GRAD = 'AUT_170';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NCX4' WHERE CD_GRAD = 'AUT_171';
UPDATE ref_grade SET CD_MOTI_N4DS = 'XCX1' WHERE CD_GRAD = 'AUT_172';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NSX1' WHERE CD_GRAD = 'AUT_173';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NSX2' WHERE CD_GRAD = 'AUT_174';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NSX3' WHERE CD_GRAD = 'AUT_175';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NSX4' WHERE CD_GRAD = 'AUT_176';
UPDATE ref_grade SET CD_MOTI_N4DS = 'XSX1' WHERE CD_GRAD = 'AUT_177';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NMX1' WHERE CD_GRAD = 'AUT_178';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NMX2' WHERE CD_GRAD = 'AUT_179';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NMX3' WHERE CD_GRAD = 'AUT_180';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NMX4' WHERE CD_GRAD = 'AUT_181';
UPDATE ref_grade SET CD_MOTI_N4DS = 'XMX1' WHERE CD_GRAD = 'AUT_182';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NOX1' WHERE CD_GRAD = 'AUT_183';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NOX2' WHERE CD_GRAD = 'AUT_184';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NOX3' WHERE CD_GRAD = 'AUT_185';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NOX4' WHERE CD_GRAD = 'AUT_186';
UPDATE ref_grade SET CD_MOTI_N4DS = 'XOX1' WHERE CD_GRAD = 'AUT_187';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NEX1' WHERE CD_GRAD = 'AUT_188';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NEX2' WHERE CD_GRAD = 'AUT_189';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NEX3' WHERE CD_GRAD = 'AUT_190';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NEX4' WHERE CD_GRAD = 'AUT_191';
UPDATE ref_grade SET CD_MOTI_N4DS = 'XEX1' WHERE CD_GRAD = 'AUT_192';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NPX1' WHERE CD_GRAD = 'AUT_193';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NPX2' WHERE CD_GRAD = 'AUT_194';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NPX3' WHERE CD_GRAD = 'AUT_195';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NPX4' WHERE CD_GRAD = 'AUT_196';
UPDATE ref_grade SET CD_MOTI_N4DS = 'XPX1' WHERE CD_GRAD = 'AUT_197';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NNX1' WHERE CD_GRAD = 'AUT_198';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NNX2' WHERE CD_GRAD = 'AUT_199';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NNX3' WHERE CD_GRAD = 'AUT_200';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NNX4' WHERE CD_GRAD = 'AUT_201';
UPDATE ref_grade SET CD_MOTI_N4DS = 'XNX1' WHERE CD_GRAD = 'AUT_202';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NRX1' WHERE CD_GRAD = 'AUT_203';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NRX2' WHERE CD_GRAD = 'AUT_204';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NRX3' WHERE CD_GRAD = 'AUT_205';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NRX4' WHERE CD_GRAD = 'AUT_206';
UPDATE ref_grade SET CD_MOTI_N4DS = 'XRX1' WHERE CD_GRAD = 'AUT_207';
UPDATE ref_grade SET CD_MOTI_N4DS = 'THW1-EHW1-HHW1-MHW1-BHW1' WHERE CD_GRAD = 'AUT_207';
UPDATE ref_grade SET CD_MOTI_N4DS = 'THC1-EHC1-HHC1-MHC1-BHC1' WHERE CD_GRAD = 'AUT_208';
UPDATE ref_grade SET CD_MOTI_N4DS = 'BHM1' WHERE CD_GRAD = 'AUT_209';
UPDATE ref_grade SET CD_MOTI_N4DS = 'THA1' WHERE CD_GRAD = 'AUT_210';
UPDATE ref_grade SET CD_MOTI_N4DS = 'THO1' WHERE CD_GRAD = 'AUT_211';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NHX1' WHERE CD_GRAD = 'AUT_212';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NHX2' WHERE CD_GRAD = 'AUT_213';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NHX3' WHERE CD_GRAD = 'AUT_214';
UPDATE ref_grade SET CD_MOTI_N4DS = 'NHX4' WHERE CD_GRAD = 'AUT_215';
UPDATE ref_grade SET CD_MOTI_N4DS = 'XHX1' WHERE CD_GRAD = 'AUT_216';
UPDATE ref_grade SET CD_MOTI_N4DS = 'YYX1' WHERE CD_GRAD = 'AUT_217';
UPDATE ref_grade SET CD_MOTI_N4DS = 'YYX3' WHERE CD_GRAD = 'AUT_218';
UPDATE ref_grade SET CD_MOTI_N4DS = 'YYX4' WHERE CD_GRAD = 'AUT_219';
UPDATE ref_grade SET CD_MOTI_N4DS = 'YYX9' WHERE CD_GRAD = 'AUT_220';

-- Update du référentiel emploi_fonctionnel pour affecter la filière
UPDATE ref_emploi_fonctionnel SET ID_FILI = 1 WHERE CD_EMPLFONC IN ('EF001', 'EF002');
UPDATE ref_emploi_fonctionnel SET ID_FILI = 2 WHERE CD_EMPLFONC IN ('EF003', 'EF004');

-- Update du référentiel des filières pour sélectionner celles qui sont concernées par les emplois fonctionnels
UPDATE ref_filiere SET BL_EMPFONC = 1 WHERE CD_FILI IN ('AD', 'TE');
	
-- Update du référentiel emploi non permanent pour le code motif N4DS
UPDATE ref_emploi_non_permanent SET CD_MOTI_N4DS = '' WHERE CD_EMPLNONPERM = 'EF001';
UPDATE ref_emploi_non_permanent SET CD_MOTI_N4DS = '' WHERE CD_EMPLNONPERM = 'EF002';
UPDATE ref_emploi_non_permanent SET CD_MOTI_N4DS = '' WHERE CD_EMPLNONPERM = 'EF003';
UPDATE ref_emploi_non_permanent SET CD_MOTI_N4DS = '' WHERE CD_EMPLNONPERM = 'EF004';
UPDATE ref_emploi_non_permanent SET CD_MOTI_N4DS = '' WHERE CD_EMPLNONPERM = 'EF005';
UPDATE ref_emploi_non_permanent SET CD_MOTI_N4DS = '21-30-41-42' WHERE CD_EMPLNONPERM = 'EF006';
UPDATE ref_emploi_non_permanent SET CD_MOTI_N4DS = '50-51' WHERE CD_EMPLNONPERM = 'EF007';
UPDATE ref_emploi_non_permanent SET CD_MOTI_N4DS = '55-71-80-90' WHERE CD_EMPLNONPERM = 'EF008';
UPDATE ref_emploi_non_permanent SET CD_MOTI_N4DS = '' WHERE CD_EMPLNONPERM = 'EF009';
UPDATE ref_emploi_non_permanent SET CD_MOTI_N4DS = '30-31-61-100' WHERE CD_EMPLNONPERM = 'EF010';
UPDATE ref_emploi_non_permanent SET CD_MOTI_N4DS = '' WHERE CD_EMPLNONPERM = 'EF011';
UPDATE ref_emploi_non_permanent SET CD_MOTI_N4DS = '070' WHERE CD_EMPLNONPERM = 'EF012';

-- Update du référrentiel temps non complet
UPDATE ref_temps_non_complet SET NB_MIN_BORNMIN = 0, NB_MIN_BORNMAX = 1050 WHERE CD_TEMPNONCOMP = 'TNC001';
UPDATE ref_temps_non_complet SET NB_MIN_BORNMIN = 1050, NB_MIN_BORNMAX = 1680 WHERE CD_TEMPNONCOMP = 'TNC002';
UPDATE ref_temps_non_complet SET NB_MIN_BORNMIN = 1680, NB_MIN_BORNMAX = NULL WHERE CD_TEMPNONCOMP = 'TNC003';

-- Update du référentiel pourcentage temps partiel
UPDATE ref_pourcentage_tempa_partiel SET PC_BORNMIN = NULL, PC_BORNMAX=80 WHERE CD_POURTEMPPART = 'PTPSP001';
UPDATE ref_pourcentage_tempa_partiel SET PC_BORNMIN = 80, PC_BORNMAX=90 WHERE CD_POURTEMPPART = 'PTPSP002';
UPDATE ref_pourcentage_tempa_partiel SET PC_BORNMIN = 90, PC_BORNMAX=NULL WHERE CD_POURTEMPPART = 'PTPSP003';

-- Update du référentiel temps partiel
UPDATE ref_temps_partiel SET CD_MODA_N4DS='21' WHERE CD_TEMPPART = 'PARTAUTO';
UPDATE ref_temps_partiel SET CD_MODA_N4DS='22-23-24-25-26-27-28-29-30-31-32-33-40-41-42' WHERE CD_TEMPPART = 'PARTDROI';

-- Update référentiel motif départ nd4s
UPDATE ref_motif_depart SET CD_MOTI_N4DS = '' WHERE CD_MOTIDEPA = 'MD001';
UPDATE ref_motif_depart SET CD_MOTI_N4DS = '' WHERE CD_MOTIDEPA = 'MD002';
UPDATE ref_motif_depart SET CD_MOTI_N4DS = '' WHERE CD_MOTIDEPA = 'MD003';
UPDATE ref_motif_depart SET CD_MOTI_N4DS = '' WHERE CD_MOTIDEPA = 'MD004';
UPDATE ref_motif_depart SET CD_MOTI_N4DS = '' WHERE CD_MOTIDEPA = 'MD005';
UPDATE ref_motif_depart SET CD_MOTI_N4DS = '122' WHERE CD_MOTIDEPA = 'MD006';
UPDATE ref_motif_depart SET CD_MOTI_N4DS = '070' WHERE CD_MOTIDEPA = 'MD007';
UPDATE ref_motif_depart SET CD_MOTI_N4DS = '' WHERE CD_MOTIDEPA = 'MD008';
UPDATE ref_motif_depart SET CD_MOTI_N4DS = '008F' WHERE CD_MOTIDEPA = 'MD009';
UPDATE ref_motif_depart SET CD_MOTI_N4DS = '' WHERE CD_MOTIDEPA = 'MD010';
UPDATE ref_motif_depart SET CD_MOTI_N4DS = '008C-096-138' WHERE CD_MOTIDEPA = 'MD011';
UPDATE ref_motif_depart SET CD_MOTI_N4DS = '010' WHERE CD_MOTIDEPA = 'MD012';
UPDATE ref_motif_depart SET CD_MOTI_N4DS = '134-136' WHERE CD_MOTIDEPA = 'MD013';
UPDATE ref_motif_depart SET CD_MOTI_N4DS = '012' WHERE CD_MOTIDEPA = 'MD014';
UPDATE ref_motif_depart SET CD_MOTI_N4DS = '018' WHERE CD_MOTIDEPA = 'MD015';
UPDATE ref_motif_depart SET CD_MOTI_N4DS = '' WHERE CD_MOTIDEPA = 'MD016';
UPDATE ref_motif_depart SET CD_MOTI_N4DS = '' WHERE CD_MOTIDEPA = 'MD017';
UPDATE ref_motif_depart SET CD_MOTI_N4DS = '' WHERE CD_MOTIDEPA = 'MD018';

-- Update référentiel arrivée n4ds
UPDATE ref_motif_arrivee SET CD_MOTI_N4DS = '' WHERE CD_MOTIARRI = 'MA001';
UPDATE ref_motif_arrivee SET CD_MOTI_N4DS = '' WHERE CD_MOTIARRI = 'MA002';
UPDATE ref_motif_arrivee SET CD_MOTI_N4DS = '' WHERE CD_MOTIARRI = 'MA003';
UPDATE ref_motif_arrivee SET CD_MOTI_N4DS = '' WHERE CD_MOTIARRI = 'MA004';
UPDATE ref_motif_arrivee SET CD_MOTI_N4DS = '' WHERE CD_MOTIARRI = 'MA005';
UPDATE ref_motif_arrivee SET CD_MOTI_N4DS = '' WHERE CD_MOTIARRI = 'MA006';
UPDATE ref_motif_arrivee SET CD_MOTI_N4DS = '' WHERE CD_MOTIARRI = 'MA007';
UPDATE ref_motif_arrivee SET CD_MOTI_N4DS = '' WHERE CD_MOTIARRI = 'MA008';
UPDATE ref_motif_arrivee SET CD_MOTI_N4DS = '' WHERE CD_MOTIARRI = 'MA009';
UPDATE ref_motif_arrivee SET CD_MOTI_N4DS = '' WHERE CD_MOTIARRI = 'MA010';
UPDATE ref_motif_arrivee SET CD_MOTI_N4DS = '' WHERE CD_MOTIARRI = 'MA011';
UPDATE ref_motif_arrivee SET CD_MOTI_N4DS = '451' WHERE CD_MOTIARRI = 'MA012';
UPDATE ref_motif_arrivee SET CD_MOTI_N4DS = '' WHERE CD_MOTIARRI = 'MA013';
UPDATE ref_motif_arrivee SET CD_MOTI_N4DS = '' WHERE CD_MOTIARRI = 'MA015';
UPDATE ref_motif_arrivee SET CD_MOTI_N4DS = '' WHERE CD_MOTIARRI = 'MA016';
UPDATE ref_motif_arrivee SET CD_MOTI_N4DS = '' WHERE CD_MOTIARRI = 'MA017';
UPDATE ref_motif_arrivee SET CD_MOTI_N4DS = '' WHERE CD_MOTIARRI = 'MA018';
UPDATE ref_motif_arrivee SET CD_MOTI_N4DS = '' WHERE CD_MOTIARRI = 'MA019';

-- Update référentiel statut
UPDATE ref_statut SET CD_MOTI_N4DS='011' WHERE CD_STAT = 'TITU';
UPDATE ref_statut SET CD_MOTI_N4DS='012' WHERE CD_STAT = 'STAG';
UPDATE ref_statut SET CD_MOTI_N4DS='030' WHERE CD_STAT = 'CONTPERM';
UPDATE ref_statut SET CD_MOTI_N4DS='040-052-054-060-070-110-150-160' WHERE CD_STAT = 'CONTNONPERM';

-- Liste blanche pour import N4DS
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Siret', 'S10.G01.00.001.001', 0, 1, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('NIC', 'S10.G01.00.001.002', 0, 1, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Cd insee', 'S10.G01.00.003.007', 0, 1, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Dt deb ref', 'S20.G01.00.003.001', 0, 1, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Dt fin ref', 'S20.G01.00.003.002', 0, 1, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Code type périodicité', 'S20.G01.00.018', 0, 1, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Numéro d inscription au répertoire', 'S30.G01.00.001', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Nom', 'S30.G01.00.002', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Prenom', 'S30.G01.00.003', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Civilité', 'S30.G01.00.007', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Dt Nais', 'S30.G01.00.009', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Dt debut Periode activite', 'S40.G01.00.001', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Cd Motif Debut Periode Activite', 'S40.G01.00.002.001', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Dt fin Periode activite', 'S40.G01.00.003', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Cd Motif fin Periode Activite', 'S40.G01.00.004.001', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Code intitulé du contrat de travail', 'S40.G10.05.012.003', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Code statut juridique', 'S40.G10.08.002.002', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Code emploi statutaire (Droit statut d emploi privé) grade 1','S40.G10.08.002.004', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Code statut juridique', 'S40.G10.10.002.002', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Code emploi statutaire (Statut d emploi public)', 'S40.G10.10.002.004', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Code catégorie statutaire', 'S40.G10.10.002.006', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Code profession et catégorie socioprofessionnelle', 'S40.G10.10.011.001', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Code nature du contrat de travail', 'S40.G10.10.012.001', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Code position statutaire', 'S40.G10.10.024', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Code détaillé de la position de détachement', 'S40.G10.24.025.004', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Code statut d appartenance à une fonction publique', 'S40.G10.25.002.001', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Code emploi statutaire', 'S40.G10.25.002.004', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Temps de travail payé', 'S40.G15.00.003', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Taux de travail à temps partiel (numérateur)', 'S40.G15.00.020.001', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Total des heures payées', 'S40.G15.00.022.001', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Total des heures payées (sans les heures supplémen...', 'S40.G15.00.022.002', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Code modalité d exercice du travail', 'S40.G15.10.013.001', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Duree hebdo', 'S40.G15.10.025.004', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Code type de l indemnité ou de la prime versée aux...', 'S40.G28.20.001', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Montant de l indemnité ou de la prime versée', 'S40.G28.20.002', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Base brute fiscale', 'S40.G40.00.035.001', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Code nature de la cotisation', 'S65.G43.10.001', 0, 0, now(), 'admin', now(), 'admin');
insert into ref_n4ds (cd_n4ds, cd_valeur, bl_vali, bl_obli, created_at, cd_utilcrea, updated_at, cd_utilmodi) values('Montant des retenues', 'S65.G43.10.002.001', 0, 0, now(), 'admin', now(), 'admin');

-- Motif départ dépendant du statut
-- Mise à disposition dans une autre coll
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (1,1);
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (1,2);
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (1,3);
-- Décharge totale du service pour exercice de mandat
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (2,1);
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (2,2);
--  Congé de formation encore rémunéré par la collectivité
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (3,1);
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (3,2);
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (3,3);
-- Congé de formation au-delà d'un an
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (4,1);
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (4,2);
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (4,3);
-- Détachement dans une autre structure
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (5,1);
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (5,2);
-- Mise en disponibilité
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (6,1);
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (6,2);
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (6,3);
-- Congé parental
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (7,1);
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (7,2);
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (7,3);
-- Mutation
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (8,1);
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (8,2);
-- Fin de détachement
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (9,1);
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (9,2);
-- Décharge d'emploi
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (10,1);
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (10,2);
-- Fin de contrat (inclure remplaçants)
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (11,3);
-- Démission
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (12,1);
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (12,2);
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (12,3);
-- Départ à la retraite
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (13,1);
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (13,2);
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (13,3);
-- Licenciement
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (14,1);
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (14,2);
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (14,3);
-- Décès
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (15,1);
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (15,2);
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (15,3);
-- Autres cas
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (16,1);
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (16,2);
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (16,3);
-- Transfert de compétences
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (17,1);
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (17,2);
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (17,3);
-- Agent contractuel nommé stagiaire
INSERT INTO statut_Motif_Depart(motif_depart_id, status_id) VALUES (18,3);

-- Motif d'arrivée
-- Recrutement direct lauréat nouvel arrivant
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (1,1);
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (1,2);
-- Recrutement direct lauréat déjà présent
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (2,1);
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (2,2);
-- Voie de concours, sélection pro nouvel arrivant
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (3,1);
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (3,2);
-- Voie de concours, sélection pro déjà présent
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (4,1);
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (4,2);
-- Article 38
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (5,1);
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (5,2);
-- Intégration direct
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (6,1);
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (6,2);
-- Voie de mutation
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (7,1);
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (7,2);
-- Voie de détachement FPE
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (8,1);
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (8,2);
-- Voie de détachement FPH
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (9,1);
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (9,2);
-- Par voie de détachment d'agents d'autres collectivités territoriales
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (10,1);
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (10,2);
-- Par voie de détachment d'agents d'autres organismes (ex: FPEEU)
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (11,1);
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (11,2);
-- Réintégration agent non rémunéré pendant la période d'absence
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (12,1);
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (12,2);
-- Transfert de compétence
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (13,1);
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (13,2);
-- Réintégration d'agents en positions particulières ayant été rémunéré pendant la période d'absence
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (14,1);
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (14,2);
-- Remplaçants
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (15,3);
-- Réintégration (agent non rémunéré pendant la période)
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (16,3);
-- Retours (agent rémunéré pendant la période)
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (17,3);
-- Article 3
INSERT INTO statut_Motif_Arrivee(motif_arrivee_id, status_id) VALUES (18,3);

-- Position statutaire
-- Détaché dans une autre structure
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(1,1);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(1,2);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(2,1);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(2,2);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(3,1);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(3,2);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(4,1);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(4,2);
-- Détachés au sein de leur propre collectivité
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(5,1);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(5,2);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(6,1);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(6,2);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(7,1);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(7,2);
-- Mise à disposition d'une autre structure
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(8,1);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(8,2);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(9,1);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(9,2);
-- En congé parental
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(10,1);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(10,2);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(10,3);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(10,4);

-- En disponibilité (article 72) hors ceux mis en disponibilité d'office ou bénéficiaires d'un congé équivalent pour les non titulaires
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(11,1);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(11,2);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(11,3);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(11,4);

-- En disponibilité dont disponibilité de droit
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(12,1);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(12,2);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(12,3);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(12,4);

-- En disponibilité d'office ou bénéficiaires d'un congé équivalent
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(13,1);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(13,2);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(13,3);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(13,4);

-- En position hors cadres (article 70)
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(14,1);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(14,2);

-- En congé spécial (article 99)
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(15,1);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(15,2);

-- Mis à disposition de votre collectivité
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(16,1);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(16,2);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(16,3);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(16,4);

--- Mis à disposition de votre collectivité dont originaire de la fonction publique d'Etat
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(17,1);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(17,2);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(17,3);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(17,4);


-- Détachés dans votre collectivité et issus de :
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(18,1);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(18,2);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(18,3);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(18,4);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(19,1);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(19,2);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(19,3);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(19,4);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(20,1);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(20,2);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(20,3);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(20,4);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(21,1);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(21,2);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(21,3);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(21,4);

-- Fonctionnaires pris en charge par le CDG ou le CNFPT
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(22,1);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(22,2);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(23,1);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(23,2);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(24,1);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(24,2);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(25,1);
INSERT INTO statut_positionstatutaire(positionstatutaire_id,statut_id) VALUES(25,2);


-- Modification de la configuration de php
upload_max_filesize  = 20M
MAX_EXECUTION_TIME = 600
POST_MAX_SIZE = 20M